### ISSUE TITLE
Database upgrade/versioning support

### ISSUE THREAD

**Issue by satyan** [satyan/sugar#10]
Need database upgrade/versioning support.
- feature requested in community

**Comment by rastoarpit** [comment]
After upgrading my sugar[using 1.3] record, with alter table query i am adding a column to existing table.
Column is there but when i add a value and save it then it does not work rather it takes a null/default value even after the upgrade. While everything works great on fresh install where table gets created with this column already.

**Comment by refaelsh** [comment]
I have exactly the same problem as rastoarpit.

**Comment by 8manuel** [comment]
I have the same problem as @rastoarpit and @refaelsh 
Even in the log it appears the alter table
`I/Sugar: ALTER TABLE ROSCA ADD COLUMN PHOTO TEXT`
However debugging the new column not appears
