### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by alaskan12** [satyan/sugar#117]
Could you please improve the documentation? and with examples,

Thanks :)

**Comment by whoshuu** [comment]
Improved documentation will be forthcoming. For now, the tests in the example project included with the file should provide pretty good usage scenarios for most situations. I'll slowly be adding more tests over time to capture more of the interface surface of the library. As always, feel free to send in a pull request with documentation if you'd like and I'll take a look there.

Marking this issue for closing as this is a problem area we're constantly going to try to improve on.
