### ISSUE TITLE
No Such Table A

### ISSUE THREAD

**Issue by saopayne** [satyan/sugar#122]
Sugar orm works perfectly for me when running and installing the android apk from my pc on my phone but it crashes when after being published on the play store.
I re-checked the apk severally but it just doesn't work on publish mode.
I am using version 1.3 and I have an empty constructor like this :: 
public Artisan(){
     super();
}
 and this is the error output I get from play store ::
Caused by: android.database.sqlite.SQLiteException: no such table: A: , while compiling: SELECT \* FROM A WHERE artisan_id = ?

I have my manifest like this :: 
<meta-data
            android:name="DATABASE"
            android:value="artfind.db" />
        <meta-data
            android:name="VERSION"
            android:value="1" />
        <meta-data
            android:name="QUERY_LOG"
            android:value="true" />
        <meta-data
            android:name="DOMAIN_PACKAGE_NAME"
            android:value="com.enaxio.artifind.model" />
where the model class is Artisan but it returns it as "A" as seen above in the query.
Thanks.

**Comment by zainul** [comment]
Yes thank you , this issues help me

**Comment by mouhsinelonly** [comment]
where's the proguard config ,i'm facing the same problem , @saopayne

**Comment by pavan-techmorphosis** [comment]
Hi, I seem to be facing the same problem . have included the below lines in proguard-rules.pro (using Android Studio) but still get the same error - 
-keep class com.observatory.database.Master
-keepnames class com.observatory.database.Master {
    *;
}
-keepclassmembernames class com.observatory.database.Master {
    *;
}
-keep public class com.observatory.database.Master { *; }

Master is the class that extends SugarRecord

**Comment by pavan-techmorphosis** [comment]
@saopayne - would really appreciate what you've done

**Comment by pavan-techmorphosis** [comment]
This worked for me - 
-keep class my.package.DbModel { *; }

Where DbModel is the class extending SugarRecord

**Comment by Gilshallem** [comment]
I had the same problem, Solved it by changing the field names - had a field called "from" witch does not fit with sql queries

**Comment by isdzulqor** [comment]
I have problem, guys... I'd like to get a value from a table. If the column does not contain any value, then I am going to insert one. So I need getCount in my case.
My question is how to use getCount in this library, could you give me sample code, please? And where I can get the .db file to see my record table

**Comment by iaubain** [comment]
isdzulqor
I know I am late but I hope this can help someone
long count= MyEntity.count(MyEntity.class, "fieldToCheck= ?", new String[]{"Value"}); 
/* That's  how to count using a condition*/

for that of not creating table

make sure that 
<meta-data android:name="DOMAIN_PACKAGE_NAME" android:value="package_where_entity_bean_reside"/>

please uninstall the app first and recompile it.. make sure instant run is disabled

**Comment by deivitaka** [comment]
@iaubain I would have never thought of instant run ... disabling it worked for me! :D

**Comment by iaubain** [comment]
@deivitaka It is true. By the way, by default I disabled the instant run in my android studio
