### ISSUE TITLE
Resource entry ic_launcher already defined error

### ISSUE THREAD

**Issue by osrl** [satyan/sugar#125]
[This](http://stackoverflow.com/questions/24140030/resource-entry-ic-launcher-already-defined) is the same issue. Changing the resource names is not the best way I think

**Comment by idemax** [comment]
Hey on version 1.3 still the problem...

**Comment by satyan** [comment]
please try 1.3.1 version. This issue is fixed there.

**Comment by idemax** [comment]
Worked, thanks!
