### ISSUE TITLE
Instructions on configuring the project with Android Studio

### ISSUE THREAD

**Issue by fhur** [satyan/sugar#131]
Hi I would like to submit a couple of patches but I have been unable to configure the project with Android Studio, could you help me set it up? are there instructions anywhere?

**Comment by jivimberg** [comment]
So after messing for a while with gradle I manage to import the project into Android Studio from the base folder (_'sugar'_) and have the 2 sub modules (_'example'_ and _'library'_) built each with it's own build.gradle file. I also added graddle wrapper.
You can take a look at: 06c6c2a6918c85b22010040ea72014bfde90c2ab

**Comment by carloscavalcanti** [comment]
I'm having some problems to import the project into Android Studio.
The commit mentioned by @jivimberg will be available in master branch?

**Comment by jivimberg** [comment]
I didn't create a pull request for this changes because I wasn't sure if using the gradle wrapper is what Sugar maintainers want. 
Did my solution worked for you?

**Comment by carloscavalcanti** [comment]
@jivimberg, 
I did a test importing the project with your changes and I just had a problem with Roboeletric and jUnit libraries, apparently the libraries doesn't recognized. But, this is easy to fix. 
The most important is the project was imported with ease.

**Comment by whoshuu** [comment]
The latest master branch should be fully compatible with the latest standard Android Studio configurations.
