### ISSUE TITLE
Saving byte array

### ISSUE THREAD

**Issue by ryanjohn1** [satyan/sugar#139]
I'm trying to save an image (.jpg) to the database. I have the image as a byte array and have the database entity including:

  private byte[] image;

  public byte[] getImage() {
        return image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }

Looking at the database that has been created the image column is a Blob which is as expected but when I retrieve the byte array back it is a few bytes long instead of the large size of the byte saved.
Is there an issue or should I be doing something different?

**Comment by alvarojoao** [comment]
Hey I'm with the same problem, can anyone report the status of this?

**Comment by andresteves** [comment]
@alvarojoao look up this pull comments please

https://github.com/satyan/sugar/pull/175

**Comment by whoshuu** [comment]
Implemented in https://github.com/satyan/sugar/commit/9fabcc1e1f3318fe6a082e984008f3d03a42c858.
