### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'com.orm.Database com.orm.SugarApp.getDatabase()' on a null object reference

### ISSUE THREAD

**Issue by Leandros** [satyan/sugar#140]
I'am constantly getting this error. The `SugarApp` class never calls `onCreate` therefore, any operation fails.

`java.lang.NullPointerException: Attempt to invoke virtual method 'com.orm.Database com.orm.SugarApp.getDatabase()' on a null object reference`

**Comment by hoshomoh** [comment]
What if there another android:name attr before, what do I do

**Comment by Leandros** [comment]
Is it your own `Application` subclass? Than you can just take a look at what the `SugarApp` class does [here](https://github.com/satyan/sugar/blob/master/library/src/main/java/com/orm/SugarApp.java) and do it in your class.

**Comment by hoshomoh** [comment]
Yes its my own Application sub-class. This should work. Thanks

**Comment by chiragpatel3131** [comment]
FireApp extends SugarApp

**Comment by chiragpatel3131** [comment]
even if u are using Multidex 

in concrete or onattachbasecontex 

MultiDex.install(this);

**Comment by qstpnv** [comment]
@hoshomoh or you can just extend your class from SugarApp 
(public class YourApplication extends SugarApp)
