### ISSUE TITLE
Crash while trying to save an entity

### ISSUE THREAD

**Issue by a-manumohan** [satyan/sugar#144]
Integrated Sugar using gradle. 
Created  a simple entity class called FavouriteStore

public class FavouriteStore extends SugarRecord<FavouriteStore>{*
    String name;

  public String getName() {
        return name;
    }

```
public void setName(String name) {
    this.name = name;
}
```

}

Added all meta tags according to the http://satyan.github.io/sugar/getting-started.html

Created a new entity object and set a name.(In onViewCreated method )
upon calling save() getting a null pointer exception and thus app crashes.

java.lang.NullPointerException
            at com.orm.SugarRecord.save(SugarRecord.java:45)

**Comment by rhpereda** [comment]
Hi satyan, i´m using SugarORM 1.3, and i extend the SugarApp for doing required work for my application. SugarDB does not crush but when i try to save and instance of my domain class come the crush. Did you have any idea?
