### ISSUE TITLE
Entity constructor signature

### ISSUE THREAD

**Issue by rajatpandit** [satyan/sugar#145]
http://satyan.github.io/sugar/getting-started.html
suggests that the Book constructor doesn't take context as a argument but then further down in the page, it does. Also when implementing in my example, super() doesn't take the context object as an argument is it just the documentation gone out of date or am i missing something here?

**Comment by whoshuu** [comment]
The project is in much better shape now. If you take a look at the example project, there's a bunch of different models we're using, and the tests show how to use those models with the library. Marking this issue for closing unless you have any other comments.
