### ISSUE TITLE
Auto-generate database migrations

### ISSUE THREAD

**Issue by ArthurPBressan** [satyan/sugar#151]
I'm coming from a python background, and there I used [sqlalchemy ORM](http://www.sqlalchemy.org/) with the [alembic](http://alembic.readthedocs.org/en/latest/) migration tool.

What I liked about Sugar was how nice it is to write queries and set up models. It reminds me of SQLAlchemy, and that is a very good thing. 

However, while you guys do provide migrations via the sql files in the migrations folders, I feel that since it doesn't auto-generate migrations, the usability of Sugar is dimished somewhat, especially sice we are talking about SQLite, which is full of little details that make writing certain migrations (`ALTER TABLE`s come to mind) a pain.

I also want to say that I am aware that this is a really tall order. Alembic is a *huge* project, is probably just as complex, and at the end of the day I still have to validate the scripts that it generates. Even so, I feel that it is important to Sugar to consider having this kind of tool.

Thanks!

**Comment by sibeliusseraphini** [comment]
fixed with #328
