### ISSUE TITLE
Exception on calling save() inside background thread (Async task)

### ISSUE THREAD

**Issue by praveendath92** [satyan/sugar#153]
This issue is probably affecting only a few users as I can see many people are able to use it without facing this issue.

This is kind of similar to http://stackoverflow.com/questions/11584290/why-asynctask-behaves-differently-if-declared-as-inner-class-of-an-activity-or-o except for the inner class thing there. The log can be found below

```
08-28 02:36:26.395: E/AndroidRuntime(23125): Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
08-28 02:36:26.395: E/AndroidRuntime(23125): 	at android.os.Handler.<init>(Handler.java:200)
08-28 02:36:26.395: E/AndroidRuntime(23125): 	at android.os.Handler.<init>(Handler.java:114)
08-28 02:36:26.395: E/AndroidRuntime(23125): 	at android.support.v4.content.ModernAsyncTask$InternalHandler.<init>(ModernAsyncTask.java:466)
08-28 02:36:26.395: E/AndroidRuntime(23125): 	at android.support.v4.content.ModernAsyncTask$InternalHandler.<init>(ModernAsyncTask.java:466)
08-28 02:36:26.395: E/AndroidRuntime(23125): 	at android.support.v4.content.ModernAsyncTask.<clinit>(ModernAsyncTask.java:75)
```

**Comment by nosferatoo** [comment]
For me, setting DOMAIN_PACKAGE_NAME does not help.
If tables need to be created for the first time in AsyncTask, it fails with "Can't create handler inside thread that has not called Looper.prepare()", regardless of DOMAIN_PACKAGE_NAME.
My workaround at the moment is calling table.gettablename before starting AsyncTask.
This way, tables get created and no further exceptions are thrown.
