### ISSUE TITLE
Cursor for CursorAdapter?

### ISSUE THREAD

**Issue by mparodi** [satyan/sugar#155]
Is there a way to get a cursor from queries such as the following ones?

```java
Select
    .from(TestRecord.class)
    .where(Condition.prop("test").eq("satya"), Condition.prop("prop").eq(2))
    .list()
```

```java
Book.listAll(Book.class)
```

I don't want to get a list of all matching items since I expect to have quite a lot of them. I want a cursor instead to use in a CursorAdapter to fill a ListView.

What's the way to go here?

**Comment by martintama** [comment]
Are there any updates on this?

**Comment by whoshuu** [comment]
This has been requested a few times. I'll get it into 1.4.0! If someone can put up a pull request I'd be happy to merge it in

**Comment by benohalloran** [comment]
@whoshuu see PR 312
