### ISSUE TITLE
Primary Key

### ISSUE THREAD

**Issue by adorgoalp** [satyan/sugar#157]
Hi,
I am using sugar. It is very nice. But I don't understand how to declare primary key?

**Comment by whoshuu** [comment]
The point of a primary key is that there's usually only one. See this [SO answer](http://stackoverflow.com/a/12946196/2297365) for why. If you need a secondary key to act as another filter, you can use one of the more advanced find queries that take in specific `"where"` clauses.

If you have another other comments, feel free to make them. Marking this to be closed in a few days.
