### ISSUE TITLE
Singleton problem

### ISSUE THREAD

**Issue by MarcinMoskala** [satyan/sugar#162]
I wanted to do singleton, but when I make function 

public static UserPreferences getInstance(){
        List<UserPreferences> list = Select.from(UserPreferences.class).list();
        if(list.size() == 0) {
            new UserPreferences().save();
            return getInstance();
        }
        return list.get(0);
    }

it have id=null and it is making new object each time I type getInstance(). When I set Id as follow:

public static UserPreferences getInstance(){
        List<UserPreferences> list = Select.from(UserPreferences.class).list();
        if(list.size() == 0) {
            UserPreferences up = new UserPreferences();
            up.setId(Long.valueOf(0));
            up.save();
            return getInstance();
        }
        return list.get(0);
    }

There is infinitive loop, and of course error

I am using sugar 1.3

Regards,
MM

**Comment by whoshuu** [comment]
Proguard mangles the class names which makes it difficult to persist your models. I'm going to mark this for closing unless @MarcinMoskala has any other comments.
