### ISSUE TITLE
Why does SugarORM contain the default ic_launcher.png icons? They are merged with my own ic_launcher.png and I don't want that

### ISSUE THREAD

**Issue by ColorWP** [satyan/sugar#169]
Some background:

Using SugarORM in my app and currently I have designed a single app launcher icon that I have named "ic_launcher.png" and put in my app's /drawable folder. I'd like to use that icon globally throughout my app for all device resolutions so I removed ic_launcher.png from the other drawable folders.

However, SugarORM also includes the default ic_launcher.png in all of  it's drawable folders and since I am using SugarORM in the `<application>` tag, those are merged with my designed icon and device resolutions for which I have not provided ic_launcher use the one coming from the SugarORM folder.

One way to overcome this is to rename my custom designed icon something different than ic_launcher and put the new name in android:icon but I think most people that use SugarORM will just go for the default configuration and not even notice the merged ic_launcher drawable.

I think that in the future we should either remove this launcher icon from the SugarORM library or rename or just leave it in the default /drawable folder (no drawable-hdpi, etc).

**Comment by mosteo** [comment]
I found this too after nearly going crazy about my icon being ignored. Lucky you that were warned by Android Studio, for me it was silently failing.

In my case, renaming my icon to another name and using the 'tools:replace' tip did the trick while the fix arrives.

Error:(11, 9) Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@icon value=(@drawable/icon_fatofacts) from AndroidManifest.xml:11:9
  	is also present at com.github.satyan:sugar:1.3:13:9 value=(@drawable/ic_launcher)
  	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:10:5 to override

**Comment by wmora** [comment]
I confirm that it's solved in version 1.3.1; this issue should be closed. Maybe it was a build error @satyan @whoshuu? Also, it would be nice to have a tag available for version 1.3.1 :)

Generated AndroidManifest for version 1.3:
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.orm"
    android:versionCode="1"
    android:versionName="1.0" >

    <uses-sdk
        android:minSdkVersion="9"
        android:targetSdkVersion="19" />

    <application
        android:allowBackup="true"
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name" >
    </application>

</manifest>
```

Generated AndroidManifest for version 1.3.1:
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.orm"
    android:versionCode="1"
    android:versionName="1.0" >

    <uses-sdk
        android:minSdkVersion="9"
        android:targetSdkVersion="19" />

    <application>
    </application>

</manifest>
```

**Comment by mouhsinelonly** [comment]
same thing here

**Comment by MGaetan89** [comment]
Yes, it's fixed in 1.3.1.

**Comment by mopsalarm** [comment]
Are you guys sure? I got it on 1.3.1 and downloaded the *.aar from maven central. Unpacking it shows, that the file is still in there:

```
unzip remotecontent\?filepath=com\%2Fgithub\%2Fsatyan\%2Fsugar\%2F1.3.1\%2Fsugar-1.3.1.aar 
Archive:  remotecontent?filepath=com%2Fgithub%2Fsatyan%2Fsugar%2F1.3.1%2Fsugar-1.3.1.aar
  inflating: AndroidManifest.xml     
  inflating: classes.jar             
  inflating: R.txt                   
   creating: res/
   creating: res/drawable-hdpi-v4/
  inflating: res/drawable-hdpi-v4/ic_launcher.png  
   creating: res/drawable-mdpi-v4/
  inflating: res/drawable-mdpi-v4/ic_launcher.png  
   creating: res/drawable-xhdpi-v4/
  inflating: res/drawable-xhdpi-v4/ic_launcher.png  
   creating: res/drawable-xxhdpi-v4/
  inflating: res/drawable-xxhdpi-v4/ic_launcher.png  
   creating: res/values/
  inflating: res/values/values.xml   
   creating: assets/
   creating: aidl/

```

**Comment by vinceng** [comment]
I'm getting this too. There must be some auto-generated ic_launcher.png because it's giving me an ic_launcher.png duplicate file error despite it not being in my project. Removing sugarORM clears the error.

**Comment by cypressious** [comment]
You should release a new version so that jcenter and mavenCentral pickup the changes.

**Comment by MichaelObi** [comment]
I wanted to use this for a new project but i cant because of this issue

**Comment by mopsalarm** [comment]
@MichaelObi Like described in the first post, you could just rename your own ic_launcher

**Comment by MichaelObi** [comment]
That's a very hacky fix.

**Comment by MichaelObi** [comment]
I was using 1.3 just updated to 1.3.1 and I'm not getting the error anymore.

**Comment by satyan** [comment]
This issue should be resolved with the new version 1.3.1.

**Comment by cypressious** [comment]
@satyan Please check the following link from jCenter: https://bintray.com/artifact/download/bintray/jcenter/com/github/satyan/sugar/1.3.1/sugar-1.3.1.aar You can see that it still contains the resources.

**Comment by twig** [comment]
Still getting this issue on 1.3.1 with Android Studio.

**Comment by quivalen** [comment]
@twig Double check your gradle file for SugarORM dependency
It should be    
compile 'com.github.satyan:sugar:1.3.1'

The official doc on the site suggest version 1.3 but that's bugged ( http://satyan.github.io/sugar/ ) can i suggest an update to the docs @satyan ? Thank you in advance

**Comment by cypressious** [comment]
1.4 seems to have fixed it.

**Comment by twig** [comment]
@quivalen I was already using 1.3.1. Still getting the same error with 1.3.1, but I just renamed the icon file to avoid the issue. Haven't tried 1.4 yet though

**Comment by Zapnologica** [comment]
I also had this problem. I was using 1.3 though. Im glad I found this forum. I was totally confused as to why my apps Icon suddenly changed.

**Comment by pedrofsn** [comment]
Unfortunately, I moved my "ic_launcher" from "mimap" to "drawable". It's not a good solution, but it worked. 

I'm using version 1.3.

**Comment by masoomyf** [comment]
Just use         tools:replace="android:icon" in manifest.xml
``` 
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="............">

    <application
        tools:replace="android:icon" 
```

Its works for me, no need to move ic_launcher.

**Comment by limbertx** [comment]
thanks  @masoomyf  work for me.

**Comment by sadegh-q** [comment]
thanks @masoomyf work for me.
