### ISSUE TITLE
Sugar ORM is not saving data into the database

### ISSUE THREAD

**Issue by mehrad-rafigh** [satyan/sugar#171]
am currently using Sugar ORM and Android Async Http Client for my Android application.

I read through the documentation of Sugar ORM and did exactly what is written there. My HttpClient is using the singleton pattern and provides methods for calling some APIs.

Now comes the bad part about it. I am not able to save the data persistently into my database which is created by Sugar ORM. Here is the method, that is calling an API:

```
  public void getAvailableMarkets(final Context context, final MarketAdapter adapter) {
    String url = BASE_URL.concat("/markets.json");
    client.addHeader("Content-Type", "application/json");
    client.addHeader("Accept", "application/json");

    client.get(context, url, null, new JsonHttpResponseHandler() {

        @Override
        public void onSuccess(int statusCode, Header[] headers, JSONArray response) {

            Log.i(TAG, "Fetched available markets from server: " + response.toString());


            Result<Markets> productResult = new Result<Markets>();
            productResult.setResults(new Gson().<ArrayList<Markets>>fromJson(response.toString(),
                    new TypeToken<ArrayList<Markets>>() {
                    }.getType()));
            ArrayList<Markets> marketsArrayList = productResult.getResults();

            // This lines tells me that there are no entries in the database
            List<Markets> marketsInDb = Markets.listAll(Markets.class);

            if(marketsInDb.size() < marketsArrayList.size() ||
                    marketsInDb.size() > marketsArrayList.size()) {

                Markets.deleteAll(Markets.class);

                for(Markets m : marketsArrayList) {
                    Markets market = new Markets(m.getId(), m.getName(), m.getChainId(), m.getLat(),
                            m.getLng(), m.getBusinessHourId(), m.getCountry(), m.getZip(), m.getCity(),
                            m.getStreet(), m.getPhoto(), m.getIcon(), m.getUrl());

                    market.save();

                    adapter.add(market);
                }

                adapter.notifyDataSetChanged();

            } 

            List<Markets> market = Markets.listAll(Markets.class);
            // This lines proves that Sugar ORM is not saving the entries   
            Log.i(TAG, "The market database list has the size of:" + market.size());
        }
    });
}
```

his is what Logcat is printing:

D/Sugar: Fetching properties
I/Sugar: Markets saved : 3
I/Sugar: Markets saved : 5
I/RestClient: The market database list has the size of:0

Also I took a look at the Sugar ORM tag at stackoverflow, but no answers or questions could give me a hint on how to solve that problem. I am a newbie to the android ecosystem and would love any help of you guys to solve this problem. Thanks in advance

**Comment by dakshhmehta** [comment]
The better approach to fix this is to have boolean exists field in class that is internally used by ORM to detect whatever it exists or not!

**Comment by rezanahardani** [comment]
here  is resolved...
https://stackoverflow.com/a/44619474/7577642

**Comment by shylendramadda** [comment]
What is the difference between save() and update() here?

Can you answer this here in [stack over flow ](https://stackoverflow.com/q/41954881/2462531)

What is the difference between save() and update() in sugar ORM?

By referring to this https://stackoverflow.com/q/26835785/2462531

save and update are giving same result?

I want to update the existing record if exist how to do that?

For example here I want to do something like:

        long count = Lead.count(Lead.class);
                                if (count > 0) {
                                    List<Lead> leads = Lead.find(Lead.class, "lead_id = ?", leadItem.leadId);
    
                                    if (leads == null) { // save leadItem
                                        Lead.save(lead);
                                        logFile.writeLog("Home Activity: Lead saved in local DB. Lead Id is: " + leadItem.leadId + " leadItem Name: " + leadItem.name);
                                        Log.d("Lead saved: ", leadItem.toString());
                                    } else { // update leadItem
                                        Lead.update(lead);
                                        logFile.writeLog("Home Activity: Lead updated in local DB. Lead Id is: " + leadItem.leadId + " leadItem Name: " + leadItem.name);
                                        Log.d("Lead updated: ", leadItem.toString());
                                    }
                                }

Here when I call update it is also updating the another record which I saved with different ID and adding as new record rather update.

**Comment by karuhanga** [comment]
Updating a saved object is pretty straightforward.

Retrieve the object;
`Object object= Object.findById(Object.class, ID);`

Set the attributes you need to;
`object.setAttr("new value");`

Then finally call save;
`object.save();`

update() which works slightly differently and would ideally be used when changing several attributes;

First create the object and set the necessary attributes;
`Object object= new Object();`
`object.setAttr("some data");`

Then set an ID for the Object that **ideally already exists** in the database in order to target that item for replacement;
`object.setID(ID);`

And finally;
`object.update();`

**Comment by shylendramadda** [comment]
@Karuhanga As I mentioned the same answer you posted in above link, but i wanna know that why update method not acts like to update the existing one rather add it as new? save is working like update if same id already exists, My qn is why both are behaving like same?

**Comment by karuhanga** [comment]
@shylendramadda I've added a comment. Please check it out.
