### ISSUE TITLE
Please remove allowBackup="true" in the Android Manifest because manifest merging will fail on manifest that contains the allowBackup="true" attribute

### ISSUE THREAD

**Issue by domenicop** [satyan/sugar#174]

**Comment by tkeil69575** [comment]
I getting this when try to compile

C:\dev\workspace\ContactLoggerApp\app\src\main\AndroidManifest.xml:25:9-36 Error:
	Attribute application@allowBackup value=(false) from AndroidManifest.xml:25:9-36
	is also present at [com.github.satyan:sugar:1.3] AndroidManifest.xml:12:9-35 value=(true)
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:23:5-106:19 to override
C:\dev\workspace\ContactLoggerApp\app\src\main\AndroidManifest.xml:26:9-43 Error:
	Attribute application@icon value=(@mipmap/ic_launcher) from AndroidManifest.xml:26:9-43
	is also present at [com.github.satyan:sugar:1.3] AndroidManifest.xml:13:9-45 value=(@drawable/ic_launcher)
	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:23:5-106:19 to override
