### ISSUE TITLE
Missing artifact com.github.satyan:sugar:jar:1.3

### ISSUE THREAD

**Issue by elioth010** [satyan/sugar#179]
error in pom maven 
<dependency>
	<groupId>com.github.satyan</groupId>
	<artifactId>sugar</artifactId>
	<version>1.3</version>
</dependency>

**Comment by elioth010** [comment]
@satyan the aar format is not supported yet by m2-eclipse, another alternative?
and thanks for the tracking

**Comment by whoshuu** [comment]
Hey @elioth010, you can check out the master branch and run:

    ./gradlew libraryJar

This should build a `sugar-1.3.1.jar` in `library/build/libs`. You can then include that locally in your Eclipse project.

Keep in mind that most Android development nowadays uses Android Studio and gradle. I suggest you try to spin up an Android Studio development environment, you'll have a much easier time with libraries and dependencies.

I'm going to mark this for closing. If you have any other issues, leave a comment and I'll take a look.
