### ISSUE TITLE
Example code doesn't have  Update operation  like com.orm.SugarRecord.save;

### ISSUE THREAD

**Issue by LOG-TAG** [satyan/sugar#185]
I'm just looking for how to implement  update operation like this (Updating Entity) in new 1.4 version comparing to old version.
```java
//old version
Book book = Book.findById(Book.class, 1);
book.title = "updated title here"; // modify the values
book.edition = "3rd edition";
book.save(); 

findById(type, id)// is there  but how to get the id of the retrieved data??
```
//newversion

```java
 save(new Note(10 + (int) (10 * Math.random()), titleBox.getText().toString(), descBox.getText().toString(), tag));
```

like  in AddNoteActivity of the example!!

**Comment by jivimberg** [comment]
+1

**Comment by jivimberg** [comment]
The way I found to do this is by using the `unique` attribute. Then you can recover the entity you want to update and during save it will overwrite the previous value.
