### ISSUE TITLE
Function call with Java Reflection

### ISSUE THREAD

**Issue by pocha** [satyan/sugar#190]
I have some common fields needed across multiple models, so I created a base class SyncSugarRecord extending SugarRecord & all my models are now extending SyncSugarRecord. 

I need to perform a common operation on `save()` for which I am using java Reflection. The function is defined in parent class SyncSugarRecord which receives the name of the model class & id as parameters. I need to execute `findById()` using the class to get the object of the class. 

    public void doSync(String className, Long id) {
       Class<?> objectClass = Class.forName(className);
       objectClass.getMethod("findById",  __ dont know what to do here __, Long.TYPE).invoke(obj,objectClass,id);
     }

Can someone help ?

**Comment by sibeliusseraphini** [comment]
@pocha could you provide more information for this question?

**Comment by pocha** [comment]
Sorry, its been quite sometime I did any Android coding.
