### ISSUE TITLE
Can't find bulk insertion 

### ISSUE THREAD

**Issue by mohd-bh** [satyan/sugar#193]
does this library supports bulk insertion? if yes, how? it's not mentioned in the documentation

**Comment by whoshuu** [comment]
It's not mentioned in the documentation but it does exist. [Here's](https://github.com/satyan/sugar/blob/6bea27ce694cd548462440b48e5e64fb989b10ed/library/src/main/java/com/orm/SugarRecord.java#L49) where it's defined.
