### ISSUE TITLE
NoSuchFieldException with latest build in each save()

### ISSUE THREAD

**Issue by Pascal66** [satyan/sugar#201]
11-25 21:49:09.869: W/System.err(11348): java.lang.NoSuchFieldException: id
11-25 21:49:09.879: W/System.err(11348): 	at java.lang.Class.getField(Class.java:724)
11-25 21:49:09.879: W/System.err(11348): 	at com.orm.util.ReflectionUtil.setFieldValueForId(ReflectionUtil.java:182)
11-25 21:49:09.879: W/System.err(11348): 	at com.orm.SugarRecord.save(SugarRecord.java:193)
11-25 21:49:09.879: W/System.err(11348): 	at com.orm.SugarRecord.save(SugarRecord.java:179)

**Comment by nicolabeghin** [comment]
I've the same error. Here's the model class for reference. 

    @JsonIgnoreProperties(ignoreUnknown = true)
    @com.orm.dsl.Table(name = "articles")
    public class Article  extends SugarRecord {
        private int company_id;
        private int group_id;
        private String codice;
        private String ean;
        private String descrizione;
        private String gamma;
        private int imballo;
    
        public Article() {
        }
    
        public int getCompany_id() {
            return company_id;
        }
    
        public void setCompany_id(int company_id) {
            this.company_id = company_id;
        }
    
        public int getGroup_id() {
            return group_id;
        }
    
        public void setGroup_id(int group_id) {
            this.group_id = group_id;
        }
    
        public String getCodice() {
            return codice;
        }
    
        public void setCodice(String codice) {
            this.codice = codice;
        }
    
        public String getEan() {
            return ean;
        }
    
        public void setEan(String ean) {
            this.ean = ean;
        }
    
        public String getDescrizione() {
            return descrizione;
        }
    
        public void setDescrizione(String descrizione) {
            this.descrizione = descrizione;
        }
    
        public String getGamma() {
            return gamma;
        }
    
        public void setGamma(String gamma) {
            this.gamma = gamma;
        }
    
        public int getImballo() {
            return imballo;
        }
    
        public void setImballo(int imballo) {
            this.imballo = imballo;
        }
    }

**Comment by Pascal66** [comment]
I think ther's a problem with Table declaration. Try without it.
@com.orm.dsl.Table(name = "articles")

**Comment by nicolabeghin** [comment]
yeah but I need the @Table annotation.. If you have any hint on where to look for the issue I could try to fix it myself then submit a patch

**Comment by Pascal66** [comment]
I've commented one ligne in SugarRecord.java to make it work:

if (SugarRecord.class.isAssignableFrom(object.getClass())) {
            //ReflectionUtil.setFieldValueForId(object, id);
        }
        Log.i("Sugar", object.getClass().getSimpleName() + " saved : " + id);

**Comment by anti43** [comment]
Reflection is imo not the way to go, especially not on Android..

    if (SugarRecord.class.isAssignableFrom(object.getClass())) {
            ((SugarRecord)object).setId(id);
        }

**Comment by nicolabeghin** [comment]
thanks a lot @jivimberg

**Comment by abscondment** [comment]
+1 for the fix from @jivimberg - can we get this merged?
