### ISSUE TITLE
Listen to CRUD events before and after they are carried out

### ISSUE THREAD

**Issue by oderayi** [satyan/sugar#207]
If a have a model class called Book and I create an instance
Book book = new Book(); 
and set all the properties.
I need to call book.save() to persist, book.delete() to delete and so on.
Is there anything like before_save or on_save, after_save, on_delete, after_delete etc that I can listen to and run some codes on the object before the action takes place?

**Comment by loose11** [comment]
Override e.g save() function in your book class and call super.save() at last.

**Comment by oderayi** [comment]
Thank you so much loose11 for that tip.
