### ISSUE TITLE
Multiple Application tag names

### ISSUE THREAD

**Issue by vivekkartha** [satyan/sugar#211]
Since com.orm.SugarApp needs to be specified in the application tag, this causes a problem when other libraries also have to be mentioned there. Is there anyway Sugar can work without extending Application? Or is there any other work around to the multiple application name issue?

**Comment by jivimberg** [comment]
On master extending SugarApp is no longer needed. If you want to give it a try take a look at: bcb9bad

**Comment by idemax** [comment]
Works for me:

Application.java

    public class Application extends SugarApp

Manifest.xml

    <application
        android:name=".Application"

**Comment by abshih** [comment]
@jivimberg 

Does that mean you don't need to put android:name attribute anymore?

**Comment by jivimberg** [comment]
Hi @abshih, 
You still want to have a class extending `android.app.Application` for initializing and terminating `com.orm.SugarContext`. 
Take a look at the example app: https://github.com/satyan/sugar/blob/master/example/src/com/example/ClientApp.java
