### ISSUE TITLE
There is the underline the problem about the field name 

### ISSUE THREAD

**Issue by Alexantaotao** [satyan/sugar#213]
When the field name underscore, query in the Select or find () will prompt field does not exist.
Such as:
     public class AppDepartment extends SugarRecord<AppDepartment>{

	public int Department_ID;
	public String Department_Name;
	public int Department_ParentID;
	
	public AppDepartment(){}	
}

List<AppDepartment> depts = Select.from(AppDepartment.class)
					.where(Condition.prop("Department_ParentID").eq(departId))
					.list();
or
List<AppDepartment> depts = depts = AppDepartment.find(AppDepartment.class, "Department_Name = ?", "办公室");

The above methods are an exception is thrown, prompt "Department_Name", "Department_ParentID" does not exist.

But: if the "Department_Name" instead of "and" DepartmentName ", is normal, but "Department_ParentID" changed to "" DepartmentParentID" but can't.

This is to pay attention to what?Please give reply, thank you very much!

**Comment by sibeliusseraphini** [comment]
This is related to how SugarOrm transform column names to have the same pattern
