### ISSUE TITLE
Error after publishing to play store

### ISSUE THREAD

**Issue by MohammadAdelGabr** [satyan/sugar#217]
I use SugarORM and while i am testing the application it works fine on the emulator and my mobile phone.

But after I published it to the play store and tested it from mobile after I install it from the play. it gives me the following error

android.database.sqlite.SQLiteException: no such column: Category: , while compiling: SELECT \* FROM F WHERE Category = ?

it is generated from the following line

CustomUnit.find(CustomUnit.class, "Category = ?", Category);

and here is the definition of the class 
public class CustomUnit extends SugarRecord<CustomUnit>
{
    public long ID;
    public String Name;
    public float Value;
    public String BaseUOM;
    public String Category;
}

**Comment by mouhsinelonly** [comment]
i'm facing the same problem when using progurad can any one help ?

**Comment by MohammadGabr** [comment]
Check my answer : 
put the following line in the proguard , it worked with me
-keep public class FullClassName { *; }

**Comment by pavan-techmorphosis** [comment]
Hi @MohammadGabr , yep, that worked for me.. Thanks
