### ISSUE TITLE
Question: why is there no entity.findById(id) ?

### ISSUE THREAD

**Issue by anti43** [satyan/sugar#224]
When I look up an Object, why do I need to pass the class?

Book book = Book.findById(Book.class, 1);

could be wrapped in 

Book book = Book.findById(1);

automatically? When calling on Book, Book knows its a Book? :)

See https://developer.jboss.org/wiki/GenericDataAccessObjects?_sscc=t

how they get the persistenceClass within the Constructor, which later can be used as T in findById

Best,

Andreas

**Comment by satyan** [comment]
(findById is a static method defined and implemented in SugarRecord class).. In a static method, we always get the class as the one where it's present. So, we never get Book's class, infact we get the SugarRecord class. That's the reason, we're having to pass the Book.class as a parameter.

I'd love to remove the class parameter, but haven't found a more viable solution yet.

**Comment by anti43** [comment]
Hello!

The solution is in https://developer.jboss.org/wiki/GenericDataAccessObjects?_sscc=t 

You can detect the Type t upon instance creation via 

public SugarRecord(){
   this.pclass = (Class<T>) ((ParameterizedType) getClass()  
                                .getGenericSuperclass()).getActualTypeArguments()[0];  //thsi gives Book Type in "Book"
}


then:

public T findById(long id) {  
        T entity = (T) findById(this.pclass, id);  
       
        return entity;  // a Book!
    }

**Comment by anti43** [comment]
Ah, just realized that its of course a static call..

**Comment by jonathan-hepp** [comment]
You can always overload the method in your entity passing the class statically, like this:
```java
public class Book extends SugarRecord<Book> {
 public static <T> T findById(Long id) {
    findById(Book.class, id);
}
```
Improves readability with no significant downside.

**Comment by whoshuu** [comment]
@anti43, is there anything else? I'd like to close this to clean up the issues list.
