### ISSUE TITLE
Remove requirement for SugarApp 

### ISSUE THREAD

**Issue by anti43** [satyan/sugar#230]
I must use android.support.multidex.MultiDexApplication as Application class, hence I cannot use SugarOrm anymore, which is pretty sad.

The whole SugarApp class in master branch does nothing but static initializing stuff now, which one can just do in any other application class I assume. However the version from master branch is not yet released, do you know when It will be available?

**Comment by greatergoodguy** [comment]
I second this motion, as I have the exact same issue with the MultiDexApplication. It would be cool to make the SugarContext class public so the user has the option of creating their custom Application class other than inheriting from SugarApp.

**Comment by jivimberg** [comment]
Just so you know on master extending SugarApp is no longer needed. You may want to take a look at: bcb9bad

**Comment by eGorets** [comment]
you can try init MultiDex as

  @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }

**Comment by sibeliusseraphini** [comment]
You don't need to extend SugarApp anymore, just call **SugarContext.init(this)** on onCreate of your Application
```
public class SugarApp extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        SugarContext.init(this);
    }

    @Override
    public void onTerminate() {
        super.onTerminate();
        SugarContext.terminate();
    }

}
```
