### ISSUE TITLE
DSL annotations Table/Column not available in maven repo

### ISSUE THREAD

**Issue by kingsleyadio** [satyan/sugar#240]
I recently migrated to Android Studio, so I switched from the git project setup in Eclipse to using the maven dependency with gradle.
It seems the version on maven is quite out of date as it doesn't yet contain the newer annotation classes such as Table and Column, and these I use extensively in my app.
I would like to know how soon this would be available on maven central.
Currently, I'm using a version I pushed to my maven local.

Quick response would be appreciated. Thanks.

**Comment by MWalid** [comment]
Have same issue

**Comment by whoshuu** [comment]
I'm currently in the process of restructuring the project to make it more amenable to a gradle/maven workflow. In the next few days you'll be able to publish to a local maven repo and pull that into your project. That'll make the transition much easier when the official 1.4.0 is released to maven central.

**Comment by black-snow** [comment]
+1

**Comment by sibeliusseraphini** [comment]
Table/Column DSL is available on 1.4 and on master
