### ISSUE TITLE
ID in sugar record 

### ISSUE THREAD

**Issue by nosrak113** [satyan/sugar#251]
Can you change protected Long id = null; to private Long id = null; in SugarRecord.java?
this will  avoid collisions with gson serialization.

**Comment by ishan1604** [comment]
+1 for this.

**Comment by bytehala** [comment]
+1

**Comment by heatherSnepenger** [comment]
agreed. I'm using version 1.4 of the code for other reasons, but when I switch the type from protected to private, this resolved a lot of issues.

**Comment by whoshuu** [comment]
Looking to get in #258 soon. This should fix your issues.

**Comment by sibeliusseraphini** [comment]
fixed
