### ISSUE TITLE
Exposing Cursor interface for SugarRecord

### ISSUE THREAD

**Issue by solganik** [satyan/sugar#256]
Hi, I`m using Sugar for developing my app, and it is an awesome  lightweight android oriented framework.
However when it comes to display data it is not that easy, due to the fact that android heavily utilizes adapter strategy for its UI, and Sugar does not easily exposes its queries as adapters.
I have a proposal, what do you think about providing the findWithQueryAsCursor method that will return a cursor and exposing the inflate method so that SugarRecord could be inflated from cursor, this will ease the use of Sugar with android basic Adapter building block without a need to go through ArrayAdapter which does not work for large collections.
I will implement it, just wanted the opinion before i do.
Thanks, 
regards Sasha,

**Comment by thepes** [comment]
totally need ! :)

**Comment by benohalloran** [comment]
PR #312

**Comment by benohalloran** [comment]
PR #312

**Comment by sibeliusseraphini** [comment]
merged on master
