### ISSUE TITLE
Cursor finalized without prior close()

### ISSUE THREAD

**Issue by gterrono** [satyan/sugar#262]
I'm seeing a lot of warnings like 
```
02-09 11:27:45.935  20050-20059/com.gumroad.android W/CursorWrapperInner﹕ Cursor finalized without prior close()
```
after saving an object. Am I doing something wrong?

**Comment by whoshuu** [comment]
Can you post the offending code that you're calling the sugar library with? It's hard to know what's going on with a single log message.
