### ISSUE TITLE
Add ability to use the 'OFFSET' parameter with a Select object

### ISSUE THREAD

**Issue by drojf** [satyan/sugar#264]
I couldn't figure out any way to add the 'OFFSET' parameter to a sqlite query besides using custom sqlite queries. ie I want to be able to do Select.class(Car.class).limit(3).offset(15);

I see in your code (https://github.com/satyan/sugar/blob/master/library/src/com/orm/query/Select.java) that there is already a variable called 'offset', however there are no functions for the user to set the value?

**Comment by peterjkirby** [comment]
@drojf Did you ever figure this out?

**Comment by drojf** [comment]
Nope, unless you change the source code yourself or use a custom sql query

     public Select<T> offset(String prop) {
            this.offset = prop;
            return this;
        }

You could issue a pull request to add the above code into 'Select.java' as well if you have time, I haven't done it cause I don't know how to use git properly lol. That's all you'd need to change I think.

**Comment by scinfu** [comment]
added in grade version 1.5 
#400

**Comment by erobic** [comment]
It does not work with .list() function.
The offset param is completely ignored.
https://github.com/satyan/sugar/issues/682
