### ISSUE TITLE
namingHelper vs camelcase

### ISSUE THREAD

**Issue by rdheiliger** [satyan/sugar#265]
trying to use existing db, all tables, columns are in camelcase, cant change as other apps will use
any suggestions on how to eliminate namingHelper
thinking of changing namingHelper. toSQLNameDefault to this

public static String toSQLNameDefault(String camelCased) {

        return camelCased;
}

**Comment by sibeliusseraphini** [comment]
you can use @Column to use a specific columnName

```
class SimpleModel extends SugarRecord {
    @Column(name="camelCased")
    private String camelCased;
}
```
