### ISSUE TITLE
Control / defer table creation

### ISSUE THREAD

**Issue by praveendath92** [satyan/sugar#269]
I have many tables in my database model and I think, the initial table creation is delaying my app launch for the first time. The delay is perceivable. 

I'm wondering if it is possible to delay the initial table creation? Something like, a manual trigger so that I can get to present a loading message to the user before the creation event begins.

**Comment by praveendath92** [comment]
I suppose a call to 

```SugarContext.init(context)```

where required, would do the trick. 

Refer: https://github.com/satyan/sugar/blob/master/library/src/com/orm/SugarApp.java#L12

**Comment by jivimberg** [comment]
As far as I know the DB is only created when you use it. So by looking at the code the `com.orm.SugarDb#onCreate` will only be called the first time you do an operation over your records

**Comment by praveendath92** [comment]
@jivimberg Yes. That's true. It's a one time action which happens on the first application startup. My application uses many tables and since creation takes place on the UI thread by default, I can see a significant delay (of about 2secs+) even on high end devices.

**Comment by praveendath92** [comment]
SugarContext is not visible with jar dependency. @jivimberg  Any thoughts?

**Comment by jivimberg** [comment]
Which version are you using? seems to be public on master...

**Comment by macleo** [comment]
```javascript
SugarContext.init(context)
```
 file :  SuguarContext, 
It isn't  included in the major releases of current version.

**Comment by jivimberg** [comment]
That's right. I was talking about master, sorry.

**Comment by whoshuu** [comment]
@praveendath92, can you give us an update on the status of your issue when possible? Thanks.

**Comment by praveendath92** [comment]
@whoshuu,

The issue still persists. Mostly because SugarContext is not included (or at least not visible) in the jar release, as of 1.3.

**Comment by whoshuu** [comment]
Is it too onerous to grab the master branch or a jar and stick it into your project? I understand wanting to keep the dependencies system as clean as possible using maven, but right now the reality is that I can't update the maven repo myself. What I can do is provide a jar on github that you can download and include in your project. Is that something you'd like to see?

**Comment by akoul889** [comment]
@whoshuu If You can provide a jar That might be helpful.

**Comment by furedal** [comment]
I got exactly the same problem. I actually need to get some data from a server then cache them into sugar before initiating my main views. I would like to be able to put a splash-screen fragment while doing this load, but sugar blocks the ui thread before i even can change fragments.

I am compiling Sugar through gradle  'com.github.satyan:sugar:1.3'

**Comment by teymoori** [comment]
I also have this problem .
is there any solution? maybe , init databases in differentt thread ?

**Comment by CaptMustache** [comment]
Using another lib (ActiveAndroid) was my solution. :/
Am 27.09.2015 13:58 schrieb "teymoori" <notifications@github.com>:

**Comment by kadymuhammad** [comment]
Me too have the same problem with any version even the latest 1.4

**Comment by sibeliusseraphini** [comment]
Try to execute the first db operation in background using AsyncTask for instance, until we figure out how to improve it

**Comment by isdzulqor** [comment]
I have problem, guys... I'd like to get a value from a table. If the column does not contain any value, then I am going to insert one. So I need getCount in my case.
My question is how to use getCount in this library, could you give me sample code, please? And where I can get the .db file to see my record table
