### ISSUE TITLE
error: type SugarRecord does not take parameters

### ISSUE THREAD

**Issue by kayvannj** [satyan/sugar#271]
I'm getting this error in compile time after I cloned the repo and imported the library folder as a module in my AndroidStudio project (I need to make some changes to the library so I have to clone it)

```
public class UserBean extends SugarRecord<UserBean> implements Bean, Serializable {
...
}
```

when I take a look at my SugarRecord I don't see any generic parameter neither

```
public class SugarRecord {

    protected Long id = null;
    ...
}
```

can anyone help?

**Comment by anti43** [comment]
Remove '<UserBean>' - its not required anymore
Am 24.02.2015 19:40 schrieb "Kayvan" <notifications@github.com>:

**Comment by kayvannj** [comment]
Thanks @anti43
