### ISSUE TITLE
No results returned from Long Select condition.

### ISSUE THREAD

**Issue by ScottMellors** [satyan/sugar#275]
Currently pulling my beard hair out about this issue, cant seem to see what I am doing wrong, I am querying the database against two parameters, a String and Long, and cannot seem to get any results back from the Select:

Select where = Select.from(DataPoint.class).where(Condition.prop("time").eq((Long) timeVal), Condition.prop("scene").eq(sUrl)).limit("1");

Tried doing the same call with a inline select ("time = ? and scene = ?) and get the same results. Any ideas where I am going wrong?

**Comment by anti43** [comment]
Time is probably a date field ..
Am 05.03.2015 18:39 schrieb "ScottMellors" <notifications@github.com>:

**Comment by ScottMellors** [comment]
Should have mentioned my Class has this set as a long, unless another field is created automatically called time which would be unfortunate and is getting confused,
