### ISSUE TITLE
Android Manifest Issues

### ISSUE THREAD

**Issue by abshih** [satyan/sugar#276]
I am writing an Android Library that uses Sugar Orm to store stuff into the SQLite database. The AndroidManifest.xml of my Android Library. I am using 1.3.1

The error I get are:

Error:(13, 9) Attribute application@name value=(com.example.app.App) from AndroidManifest.xml:13:9
Error:(20, 13) Attribute meta-data#DATABASE@value value=(test_car.db) from AndroidManifest.xml:20:13
Error:(23, 13) Attribute meta-data#VERSION@value value=(4) from AndroidManifest.xml:23:13
Error:(29, 13) Attribute meta-data#DOMAIN_PACKAGE_NAME@value value=(com.example.app) from AndroidManifest.xml:29:13
It says " Suggestion: add 'tools:replace="android:value"' to element at AndroidManifest.xml:21:9 to override"

How would I solve this?

I want my Library to work with applications that use or do not use Sugar.

The Main App uses:

    <application
        android:name=".App"
        android:allowBackup="true"
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme">
        <meta-data
            android:name="DATABASE"
            android:value="example_scans.db" />
        <meta-data
            android:name="VERSION"
            android:value="4" />
        <meta-data
            android:name="QUERY_LOG"
            android:value="true" />
        <meta-data
            android:name="DOMAIN_PACKAGE_NAME"
            android:value="com.example.usps" />
My Library Uses:

       <application
        android:allowBackup="true"
        android:label="@string/app_name"
        android:name="com.orm.SugarApp">

        <meta-data android:name="DATABASE" android:value="example_logs.db" />
        <meta-data android:name="VERSION" android:value="3" />
        <meta-data android:name="QUERY_LOG" android:value="true" />
        <meta-data android:name="DOMAIN_PACKAGE_NAME" android:value="com.example.usps" />

**Comment by carloscavalcanti** [comment]
@abshih , 
Your App class declared in your manifest inherits from who?
It's necessary to extend the SugarApp. I think can be this problem.

**Comment by benohalloran** [comment]
There's a work around for this, but it should be changed in the future so this is not longer an issue. It took me a while to figure it out.
add xmlns:tools="http://schemas.android.com/tools" to the manifest tag
add  tools:replace="android:icon" to the application tag

**Comment by alfco333** [comment]
Hello everyone, I have a question, is there a way to stop showing the logs in the log cat for every query?, I have set the QUERY_LOG in the manifest to false but nothing happens, any help would be appreciated.

**Comment by emdete** [comment]
i have a similar problem. the library contains resources out of no reason. this overwrites my launcher icon. i consider the build broken - why would a minimallistc orm need icons? furthermore i found no way to not use these icons, so it breaks my app.

**Comment by ArtworkAD** [comment]
@emdete follow this to override the icon http://stackoverflow.com/a/27360988/401025
