### ISSUE TITLE
DB upgrades can result in race condition

### ISSUE THREAD

**Issue by hoda0013** [satyan/sugar#279]
In the SugarApp class the onCreate() method looks like this:

    @Override
    public void onCreate() {
        super.onCreate();
        SugarContext.init(this);
    }

Since super.onCreate() is being called first, it means that the launcher activity starts, then SugarContext.init(this) is called. This is creating problems in my app because my Activity is able to hit its onCreate() and onStart() methods before the upgrade is even started. This has been crashing my app and I wonder if this has occurred for anyone else and if you have a solution that you can suggest.

Would calling SugarContext.init(this) before super.onCreate() guarantee that upgrades would occur before Activity code is run?

**Comment by carloscavalcanti** [comment]
@hoda0013, 
you can create a class extending SugarApp and override onCreate method as you wish.
Don't forget to declare this class in your Android Manifest.

**Comment by hoda0013** [comment]
I currently am extending SugarApp with a class called MyApplication. 
One thought I had was to call SugarContext.init(this) in the onCreate() method of MyApplication and then call super.onCreate(). It looks like that would take care of the upgrade before any of my Activities start.

However, I'm having trouble getting a reference to SugarContext from MyApplication. Which is weird because it looks like SugarContext is a public class and I can get a reference to several of the other public classes in the com.orm package.

**Comment by hoda0013** [comment]
Disregard my last comment. I cloned the most recent branch instead of v1.3. v1.3 looks to be a bit different (SugarContext isn't even a class).

**Comment by whoshuu** [comment]
Is this still an issue for you or does the beta jar resolve this? Moving forward, what's in the beta jar will what 1.4.0 has.

**Comment by hoda0013** [comment]
I wasn't able to get database migrations to work for me using v1.3. It seemed that when the app would startup that the onCreate() of the application class would kick off the migration, but that it would happen 'in parallel' with the activity and fragment life cycles. What I was seeing was that the migration wouldn't have started until after one of my activities had completed a networking operation and would be trying to persist data and eventually result in a crash with the message 'table not found'.
This may just be user error, but I was not able to figure out how to do a migration because of this.

**Comment by sibeliusseraphini** [comment]
@hoda0013 try to use the master version
