### ISSUE TITLE
Add 2 lib on application tag (android:name)

### ISSUE THREAD

**Issue by zigic88** [satyan/sugar#282]
First of all, sorry for my bad english.
I'm using 2 lib on my application. That's volley lib and sugar orm lib.
My question how to add 2 lib on AndroidManifest.xml inside application tag (android:name)
For example  only use volley lib :
<application
        android:name="myapp.app.AppController"
..............................
>

how to add sugar orm android:name inside?
possible to add android:name="com.orm.SugarApp" below  android:name="myapp.app.AppController" ? please help me...

**Comment by zeeshansaiyed** [comment]
Same as above but little bit furnished question.

There where 2 methods in com.orm.SugarApp

 SugarContext.init(this);
 SugarContext.terminate();

which i included in my application class, but was unable to find source of SugarContext, so i copied that class too. but at the end the exception was 

java.lang.NullPointerException: Attempt to invoke virtual method 'com.orm.Database com.orm.SugarApp.getDatabase()' on a null object reference

i added these too to my manifest file.
<meta-data android:name="DATABASE" android:value="example.db" />
        <meta-data android:name="VERSION" android:value="1" />
        <meta-data android:name="QUERY_LOG" android:value="true" />
        <meta-data android:name="DOMAIN_PACKAGE_NAME" android:value="com.example" />

but failed !

can you please tell me how to resolve these issues ?

**Comment by zeeshansaiyed** [comment]
Same as above but little bit furnished question.

There where 2 methods in com.orm.SugarApp

 `SugarContext.init(this);
 SugarContext.terminate();`

which i included in my application class, but was unable to find source of SugarContext, so i copied that class too. but at the end the exception was 

java.lang.NullPointerException: Attempt to invoke virtual method 'com.orm.Database com.orm.SugarApp.getDatabase()' on a null object reference

i added these too to my manifest file.
`<meta-data android:name="DATABASE" android:value="example.db" />
        <meta-data android:name="VERSION" android:value="1" />
        <meta-data android:name="QUERY_LOG" android:value="true" />
        <meta-data android:name="DOMAIN_PACKAGE_NAME" android:value="com.example" />`

but failed !

can you please tell me how to resolve these issues ?

**Comment by XerWandeRer** [comment]
@zeeshansaiyed You can take a look at this [issue](https://github.com/satyan/sugar/issues/161).

**Comment by whoshuu** [comment]
@zigic88 and @zeeshansaiyed, did @XerWandeRer's suggestion help?

**Comment by OmarMahdoui** [comment]
i have the same problem and i didn't find help .. :/

**Comment by lupsyn** [comment]
Have you found a solution ?

**Comment by izaaz** [comment]
Make your AppController extend SugarApp instead of Application.

http://stackoverflow.com/questions/19001644/how-to-handle-multiple-application-classes-in-android

**Comment by sibeliusseraphini** [comment]
in the master version you don't need to extend SugarApp anymore, but you need to call SugarContext.init(this) inside onCreate of your Application

**Comment by RodryVazquez** [comment]
Sugar extends of Application and Volley extends Application as well, easy in your Volley singleton extends of com.orm.SugarApp and in your manifest set the name of the application tag, like this: <application name="Name volley singleton"/>
