### ISSUE TITLE
Use ids from api instead of Sugar's?

### ISSUE THREAD

**Issue by marwfair** [satyan/sugar#283]
All of the objects coming from my api have their own id. This id is also used to manage relationships between objects. Currently, I am creating a new id field for my object, ex. personId. Then when I want to update that object, I have to query if that object already exists in the db. If id does, I assign the "Sugar id" from the existing record to the current record to avoid duplication.

It would be really nice if I could use my own id to avoid these checks/assignments, and only have to deal with one id field. Is anybody else having this problem or found a better way around it?

**Comment by whoshuu** [comment]
If your application structure allows it, could you extend `SugarRecord` instead of using annotations? Doing this will make your classes inherit `id` from `SugarRecord`, and that `id` will always reflect how it is persisted within the database.

**Comment by marwfair** [comment]
Thanks. I was able to fix it by updating to the newest version of Sugar and setting Sugar's id to what I need it to be.
