### ISSUE TITLE
why example source from github can't not run with sugar-1.3.jar?

### ISSUE THREAD

**Issue by macleo** [satyan/sugar#284]
sugar-1.3.jar and library sugar from here
 It looks very different.

**Comment by XerWandeRer** [comment]
https://github.com/satyan/sugar/issues/161

**Comment by macleo** [comment]
thank you, Application extends com.orm.SugarApp,can solved this problem.

but, source code really is different.

**Comment by whoshuu** [comment]
I'm in the processing of cleaning up the library and project structure. Hopefully all this pain from having two different ways of interacting with the library goes away. We'll have to put in some effort to redo a lot of the github-pages stuff as well to keep everything up to date.

**Comment by whoshuu** [comment]
@macleo, can I close this issue?
