### ISSUE TITLE
NullPointerException using Select.from

### ISSUE THREAD

**Issue by black-snow** [satyan/sugar#287]
I just received a NullPointerException while building the Query via `Select.from`:

    Select.from(MyModel.class).where(Condition.prop("myprop").notEq(null)).orderBy("ID").list();

Did I get the usage wrong from the (poor) docs? What's the correct equivalent to `WHERE prop <> null`?

**Comment by whoshuu** [comment]
Null isn't supported in queries yet. There's a pending pull request that'll go into 1.4.0, #227. I'll close this issue when #227 gets into master.
