### ISSUE TITLE
Pulling from master, I get "SugarRecord does not take parameters"

### ISSUE THREAD

**Issue by cdesch** [satyan/sugar#288]
I switched from the gradle package `compile 'com.github.satyan:sugar:1.3'` and pulled the library from the master branch into my project `compile project(':libraries:sugar:library')`. The project was working before the change, but now I get this error when declaring a class as a `SugarRecord`

error:

     error: type SugarRecord does not take parameters public class UpTimeEvent extends SugarRecord <UpTimeEvent> {

code: 

    public class UpTimeEvent extends SugarRecord <UpTimeEvent> {
                                            

It seems to highlight that as an error anywhere I pass the type to `SugarRecord`

Another Error:

        error: type argument UpTimeEvent is not within bounds of type-variable E
        List<UpTimeEvent> eventsList = UpTimeEvent.listAll(UpTimeEvent.class);

How do I fix this error such that I can use the library? I was hoping to contribute a few lines of code to the library.

**Comment by cdesch** [comment]
I see, `public class SugarRecord {` changed from `public class SugarRecord<T>{` but because the directory changed I couldn't see the file history. 


I seem to be getting a new error when I have a `SugarRecord` save itself with `this.save()`

                03-27 11:27:27.636    1923-1923/com.kickinespresso.apps.myuptime W/System.err﹕ java.lang.NoSuchFieldException: id
		03-27 11:27:27.636    1923-1923/com.kickinespresso.apps.myuptime W/System.err﹕ at java.lang.Class.getField(Class.java:1048)
		03-27 11:27:27.636    1923-1923/com.kickinespresso.apps.myuptime W/System.err﹕ at com.orm.util.ReflectionUtil.setFieldValueForId(ReflectionUtil.java:182)
		03-27 11:27:27.636    1923-1923/com.kickinespresso.apps.myuptime W/System.err﹕ at com.orm.SugarRecord.save(SugarRecord.java:193)
		03-27 11:27:27.636    1923-1923/com.kickinespresso.apps.myuptime W/System.err﹕ at com.orm.SugarRecord.save(SugarRecord.java:224)
		03-27 11:27:27.636    1923-1923/com.kickinespresso.apps.myuptime W/System.err﹕ at com.kickinespresso.apps.myuptime.UpTimeEvent.updateLastKnownUpTime(UpTimeEvent.java:52)
		03-27 11:27:27.636    1923-1923/com.kickinespresso.apps.myuptime W/System.err﹕ at com.kickinespresso.apps.myuptime.MainService.updateStatus(MainService.java:84)
		03-27 11:27:27.636    1923-1923/com.kickinespresso.apps.myuptime W/System.err﹕ at com.kickinespresso.apps.myuptime.MainService$1.run(MainService.java:93)
		03-27 11:27:27.636    1923-1923/com.kickinespresso.apps.myuptime W/System.err﹕ at android.os.Handler.handleCallback(Handler.java:739)
		03-27 11:27:27.636    1923-1923/com.kickinespresso.apps.myuptime W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:95)
		03-27 11:27:27.636    1923-1923/com.kickinespresso.apps.myuptime W/System.err﹕ at android.os.Looper.loop(Looper.java:135)
		03-27 11:27:27.636    1923-1923/com.kickinespresso.apps.myuptime W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5221)
		03-27 11:27:27.636    1923-1923/com.kickinespresso.apps.myuptime W/System.err﹕ at java.lang.reflect.Method.invoke(Native Method)
		03-27 11:27:27.636    1923-1923/com.kickinespresso.apps.myuptime W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:372)
		03-27 11:27:27.636    1923-1923/com.kickinespresso.apps.myuptime W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
		03-27 11:27:27.637    1923-1923/com.kickinespresso.apps.myuptime W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
		03-27 11:27:27.637    1923-1923/com.kickinespresso.apps.myuptime I/Sugar﹕ UpTimeEvent saved : 6


line 52: 

     com.kickinespresso.apps.myuptime.UpTimeEvent.updateLastKnownUpTime(UpTimeEvent.java:52)

calls `this.save()`

**Comment by cdesch** [comment]
It seems to be here `Field field = object.getClass().getField("id");`


    public static void setFieldValueForId(Object object, Long value) {

        try {
            Field field = object.getClass().getField("id");

            field.setAccessible(true);
            field.set(object, value);
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        }
    }

**Comment by whoshuu** [comment]
You're correct, in the latest master branch, we removed the need to parameterize `SugarRecord` when extending it. All you need to do now is simply extend it, or you can use Java annotations instead if extending `SugarRecord` is inappropriate for your class structure.

**Comment by cdesch** [comment]
Cool. Thanks. 

I think the issue with the `object.getClass().getField("id");` is that is it is null when a new `SugarRecord` is created. 

Sorry, I'm just getting back into java. Bare with me. :-)

**Comment by whoshuu** [comment]
`object.getClass().getField("id");` isn't a number, it's a field. It not being present tells me you didn't extend the class. Can you provide me with a minimal snippet of how you're using `SugarRecord` in the class you're trying to persist?

**Comment by cdesch** [comment]
Here is my current code. Please excuse my horrible class.... still developing :-p

https://gist.github.com/cdesch/07f73ae5d172bef2cf9a

**Comment by whoshuu** [comment]
Hey, I looked into your issue a big more, and you're actually encountering a bug that was present in the master branch. I've since fixed that. The relevant issues are: #201, #216, and #236. Let me know if the latest master branch still doesn't fix your issue. If it does, we can close this one up.

**Comment by cdesch** [comment]
Yes. This fixed the issue. Thank you. Which pull request fixed it?

**Comment by whoshuu** [comment]
#216 and #236 both independently fixed the issue, though #236 obsoleted some parts of #216.
