### ISSUE TITLE
How do I run the roboelectric tests?

### ISSUE THREAD

**Issue by cdesch** [satyan/sugar#289]
I've add some [helper methods](https://github.com/kickinespresso/sugar/commit/172196666150d86371c2a247b10574985bb934ce) to master branch and [also created some tests cases](https://github.com/kickinespresso/sugar/commit/fdc9f72bab0fe9d628f1a7c97d2e39d0c9e832bc) for them. I want to run the test suite before making the pull request into the master branch. How do I do that in android studio or Is there a simple way to do this from the command line?

Please excuse my n00bishness to Roboelectric.

**Comment by whoshuu** [comment]
Hey @cdesch, really great work you've done there. Running the tests are very easy! Simply do this from the root directory:

    gradle build test

Let me know if this doesn't work for you.

**Comment by cdesch** [comment]
@whoshuu You're awesome! I can't express my gratitude enough. 

I had to install gradle `brew install gradle` but I get a missing SDK error. I haven't made any modifications to any of the gradle, manifest or .iml files in my fork. I'm trying to keep it as clean as possible for the pull request.  I set the `ANDROID_HOME` environment variable and it started running although I ran into an error with `Execution failed for task ':example:compileDebugUnitTestJava'.`   Here is my [stack trace](https://gist.github.com/cdesch/e79faeba20042ba7d033) 

It does seem to be running my test cases, which I'll work on fixing and making sure they execute properly before submitting a pull request. 

      /Users/cj/AndroidStudioProjects/sugar/example/src/test/java/com/example/sugartest/HelperRecordTests.java:23: error: reference to assertEquals is ambiguous, both method assertEquals(double,double) in Assert and method assertEquals(Object,Object) in Assert match
		        assertEquals(model.getFloat(), 0.25F);
		        ^
		/Users/cj/AndroidStudioProjects/sugar/example/src/test/java/com/example/sugartest/HelperRecordTests.java:30: error: no suitable method found for findById(Class<FloatFieldExtendedModel>)
		        FloatFieldExtendedModel model = SugarRecord.findById(FloatFieldExtendedModel.class);
		                                                   ^
		    method SugarRecord.<T#1>findById(Class<T#1>,Integer) is not applicable
		      (cannot instantiate from arguments because actual and formal argument lists differ in length)
		    method SugarRecord.<T#2>findById(Class<T#2>,Long) is not applicable
		      (cannot instantiate from arguments because actual and formal argument lists differ in length)
		  where T#1,T#2 are type-variables:
		    T#1 extends Object declared in method <T#1>findById(Class<T#1>,Integer)
		    T#2 extends Object declared in method <T#2>findById(Class<T#2>,Long)
		/Users/cj/AndroidStudioProjects/sugar/example/src/test/java/com/example/sugartest/HelperRecordTests.java:31: error: reference to assertEquals is ambiguous, both method assertEquals(double,double) in Assert and method assertEquals(Object,Object) in Assert match
		        assertEquals(model.getFloat(), 0.5F);
		        ^
		Note: /Users/cj/AndroidStudioProjects/sugar/example/src/test/java/com/example/sugartest/HelperRecordTests.java uses or overrides a deprecated API.
		Note: Recompile with -Xlint:deprecation for details.
		3 errors
		:example:compileDebugUnitTestJava FAILED

**Comment by whoshuu** [comment]
Now we're getting somewhere!

The problem is that you're returning an object with `model.getFloat()` (a `Float` object, to be specific), but you're trying to compare that to a primitive. This causes a method ambiguation which you can resolve by creating a new object inside the method call, like so:

    assertEquals(model.getFloat(), new Float(0.5F));

**Comment by whoshuu** [comment]
Additionally, `findById` takes in a class _and_ an id, either a `long` or an `int`. Be sure to provide one when calling that method.

**Comment by cdesch** [comment]
Yeah, I was able to find out what was wrong with those tests. They look to be running fine now although  the test runner seems to be failing all the tests with a `java.lang.NoClassDefFoundError` error. I think it is most likely a configuration error with the way I'm running the gradle tests since it seems to happen with our without my tests being included in the test suite. [Here is my stacktrace](https://gist.github.com/cdesch/d7c3b622d99807eeae2f)

	    @Test
	    public void firstHelperTest() {
	        save(new FloatFieldExtendedModel(0.25F));
	        save(new FloatFieldExtendedModel(0.5F));
	        FloatFieldExtendedModel model = SugarRecord.first(FloatFieldExtendedModel.class);
	        assertEquals(0.25F, model.getFloat(), 0.0000000001F);
	        assertFalse(0.5F == model.getFloat());
	    }

	    @Test
	    public void lastHelperTest() {
	        save(new FloatFieldExtendedModel(0.25F));
	        save(new FloatFieldExtendedModel(0.5F));
	        FloatFieldExtendedModel model = SugarRecord.last(FloatFieldExtendedModel.class);
	        assertEquals(0.5F, model.getFloat(), 0.0000000001F);
	        assertFalse(0.25F == model.getFloat());
	    }

	    @Test
	    public void nullFirstHelperTest() {
	        FloatFieldExtendedModel model = SugarRecord.first(FloatFieldExtendedModel.class);
	        assertNull(model);
	    }

	    @Test
	    public void nullLastHelperTest() {
	        FloatFieldExtendedModel model = SugarRecord.last(FloatFieldExtendedModel.class);
	        assertNull(model);
	    }

	    @Test
	    public void oneItemHelperTest() {
	        save(new FloatFieldExtendedModel(0.25F));
	        FloatFieldExtendedModel firstModel = SugarRecord.first(FloatFieldExtendedModel.class);
	        FloatFieldExtendedModel lastModel = SugarRecord.last(FloatFieldExtendedModel.class);
	        assertEquals(firstModel.getFloat(), lastModel.getFloat(),0.0000000001F );
	    }

**Comment by whoshuu** [comment]
Interesting, what if you try running the tests with the included gradle wrapper:

    chmod +x gradlew
    ./gradlew clean build test

The chmod is necessary because I haven't updated the executable bits yet.

**Comment by cdesch** [comment]
Got it. All tests are passing. Thank you so much for you're help. The number of records starting at 1 threw me a little. It isn't quite clear in the documentation, so I made  pull request number #291 to help make that a bit more clear. 

Thank you @whoshuu for all your help. I hope you'll consider my pull request #290 to add some smaller helper methods.
