### ISSUE TITLE
Latest compiled jar

### ISSUE THREAD

**Issue by shakmak** [satyan/sugar#296]
Where can i find nightly compiled jar file. I was facing some issues during deletion. 
I am doing deletion from background threads. 

I copied whole library code in my project but that is leading to 64K methods limit being crossed.

**Comment by whoshuu** [comment]
You can try to compile the jar yourself using the gradle command:

    ./gradlew libraryJar

This will put a `sugar-1.3.1.jar` into `library/build/libs`. Let me know if there are any other issues.

**Comment by whoshuu** [comment]
References #175.
