### ISSUE TITLE
Allow option to autodetect new properties in existing models and add those columns in the database.

### ISSUE THREAD

**Issue by jedld** [satyan/sugar#299]
Allow option to autodetect new properties in existing models and add those columns in the database.

There are times when you need to add a new property to a model and the corresponding column in the database. It would be nice if sugar would detect new columns during a version upgrade.

Though it is achievable now by manually adding the new columns in a migration sql file, there is problem when it is a new installation.... the new columns get created by the schema generator, unfortunately the migration files are also run which causes a duplicate column error.

**Comment by whoshuu** [comment]
References #151.

**Comment by sibeliusseraphini** [comment]
fixed with #328
