### ISSUE TITLE
Enum storage does not work with overridden toString in enum class

### ISSUE THREAD

**Issue by nednil** [satyan/sugar#300]
Enum values are serialized with toString and deserialized using valueOf. ValueOf is generated by the compiler and will only except the name of the enum. This leads to problems when a custom toString for the enum is used since it is not possible to override the valueOf method to handle the matching case.

It would be better to serialize using the enum name method, then deserialize using valueOf. These two methods cannot be overriden so it will prevent any problems with adding custom toString methods to an enum.

**Comment by whoshuu** [comment]
References #292.
