### ISSUE TITLE
Ignore field update if null value?

### ISSUE THREAD

**Issue by marwfair** [satyan/sugar#305]
Some of my models have fields that are populated on the device side, and are not part of the API models. When I hit the API to update my objects, the fields that were populated by the device are getting overwritten. For now, when I update my objects, I am doing a db query to see if the object already exists, then assign the existing object's fields to my new "updated" object before saving to the db. Is there a way to tell Sugar to not update certain fields if the newer value is null?

**Comment by whoshuu** [comment]
Currently there's no way to selectively update fields for instances of a model. The way your API is interacting with your models seems peculiar, is it too much to have the API selectively update the model with only fields that are present instead of setting them to null? When I use API's to update objects, they rarely behave in the way you're describing.

**Comment by marwfair** [comment]
I can't change the API. Here is an example of what is happening: A list of Video objects come down from the API with the fields "Title" and "URL". In my Video Sugar model, I have added the field "hasWatched". When a user watches the video, that is set to true. When I refresh my video list and it updates my Video objects, the "hasWatched" values gets set back to false.

Maybe I will have to create a new table that keeps track of which videos have been watched.

**Comment by whoshuu** [comment]
You don't have to change your API. I think it's possible to change how you're using the API to update your models. You say "it updates my Video objects, the "hasWatched" values gets set back to false.", and I don't believe this *has* to be the case. Why don't you leave fields as they are if the API doesn't set them explicitly?

**Comment by marwfair** [comment]
I am using Jackson to parse the json data, then saving the objects to the db as soon as the parsing is complete, so I am not manually setting the fields. I'm using Jackson's JsonIgnore annotation to make sure that it isn't setting fields that it shouldn't be.

**Comment by sibeliusseraphini** [comment]
#436
