### ISSUE TITLE
Is there any method like findOne ?

### ISSUE THREAD

**Issue by scarletsky** [satyan/sugar#307]
Hi, I am new to android development, and I am a web developer before.
I am using mongodb in server side, and it use `_id` for primary key.

When using Sugar ORM, it seems that it can only use `Model.findById` to get **ONE** record in database. 
In other case, if I want to get one record by other fields (not the id field) in database, I can only doing this:

```java
List<User> users = User.find(User.class, "_id = ?", "_id field in mongodb");
User user = users.get(0);
Log.d(TAG, user._id);
```

So, my question is : is there any mehod like findOne can help me to do this:
```java
User user = User.findOne(User.class, "_id = ?", "_id field in mongodb");
Log.d(TAG, user._id);
```
thanks!

**Comment by satyan** [comment]
There's no findOne currently. You could use the "limit" parameter in find to restrict your result to one record.

**Comment by scarletsky** [comment]
@satyan Ok, I see.
