### ISSUE TITLE
Insert queries in Migrations

### ISSUE THREAD

**Issue by dhvanish** [satyan/sugar#309]
Hi,

By default when a model is created an id field is automatically associated with it.
When we save a new object for that model we don't pass the id as it automatically increments it.

But when I added an insert query in the sql file for migration, It got picked for migration but gave and error that 
table has 10 columns but 9 values were supplied.

I save an object using only 9 values as id is not required. Same values i pass in insert sql.

Is it possible to get the next id while inserting ?
Could you please help ?

Thanks.

**Comment by whoshuu** [comment]
If you have a table with columns "id", "data", "more_data", then you can insert only the required values with:

    INSERT INTO table_name (data, more_data) VALUES ("hello", "world");

Notice that I omit "id" in the first parenthetical block, and this lets me avoid having to declare one in the second block. Let me know if this helps.

**Comment by dhvanish** [comment]
It worked!!
Thanks...
