### ISSUE TITLE
Initial inserts

### ISSUE THREAD

**Issue by dhvanish** [satyan/sugar#318]
Hi,

Is there any way in which inserts can be done on app installation?
Like we specify the inserts.sql in sugar_ugrades under assets folder.
I tried with version 1 and 1.sql didnot work.

Thanks.

**Comment by shinhithi** [comment]
Hello,

I have the same problem.

Thx

**Comment by nicconicco** [comment]
same problem...

**Comment by edu1910** [comment]
Hi guys.

I made a workaround to solve that.

1- Create a 0.sql file in sugar_upgrades with your initials inserts;
2- Add this code in your main activity:
```
if (AppPreferences.getInstance().isFirstExecution()) {
    SchemaGenerator generator = new SchemaGenerator(this);
    generator.doUpgrade(new SugarDb(this).getDB(), -1, 0);
    AppPreferences.getInstance().setFirstExecution(false);
}
```
*AppPreferences is a controller to manipulate my SharedPreferences that has a boolean property indicating if the app is running for the first time.

I hope it will help somebody else :)

**Comment by JonatanSalas** [comment]
Hello guys! This trouble has been solved by PR 577 which adds a method called afterTableCreated which reads a folder in assets that is called sugar_inserts, so you can put a custom .sql script to populate your db with fresh data. 
It only executes when schemaGenerator is called. 

If you want to probe this new feature you should use SugarORM from master branch.

We are waiting for a patch release version of sugar.

**Comment by JonatanSalas** [comment]
Hello guys! This trouble has been solved by PR 577 which adds a method called afterTableCreated which reads a folder in assets that is called sugar_inserts, so you can put a custom .sql script to populate your db with fresh data. 
It only executes when schemaGenerator is called. 

If you want to probe this new feature you should use SugarORM from master branch.

We are waiting for a patch release version of sugar.

**Comment by JonatanSalas** [comment]
Hello guys! This trouble has been solved by PR 577 which adds a method called afterTableCreated which reads a folder in assets that is called sugar_inserts, so you can put a custom .sql script to populate your db with fresh data. 
It only executes when schemaGenerator is called. 

If you want to probe this new feature you should use SugarORM from master branch.

We are waiting for a patch release version of sugar.
