### ISSUE TITLE
ic_laucher.png duplicated

### ISSUE THREAD

**Issue by NexsDev** [satyan/sugar#319]
Hi!

I think that im not the only who has this problem, but grade was throwing an error in my project about one file duplicated, the ic_laucher. One file came from my project, the other one from here.

If there is no problem, could you remove ic_laucher from sugar?

**Comment by satyan** [comment]
Can you try version 1.3.1 in your dependency. This has been fixed in that release. thanks.

**Comment by patxu** [comment]
Worked for me

**Comment by NexsDev** [comment]
Thank you @satyan it worked for me too
