### ISSUE TITLE
Model not saving parameters passed to constructor with overrides

### ISSUE THREAD

**Issue by ashstampede** [satyan/sugar#321]
I was implementing a test in android studio (junit 3) trying to learn Sugar.  I first create a parent model in a loop then save. Then in a nested loop I try to create child models by calling... \<snip>

Basically after a lot of hours looking in the wrong places, this doesn't work in SugarORM.
```
public Model(long wid, String str, ){
        this.wid = wid;
        this.str = str;
    }
    public Model(long wid, String str, String str1...) {
        new Model(wid, str);
        this.str1 = str1;
    }
```
what was returned in my 'saved' model was a lot of null string and default values of 0,s on ints or 0.0f on floats. But a new Model object with an ID from the db.
Now should it work/why doesn't it work? Should it be a feature request, how are you suppose to do it in your Models? or will I have to call the full list parameter constructor that sets all values itself( which I have amend my model to work like this now).

**Comment by VLEIX** [comment]
Hello!
You need to generate a constructor without parameters.
like...
public Model(){
}

**Comment by ashstampede** [comment]
I have the empty default constructor as per the documentation, however I was not able to perform constructor overloading.... but thinking about it now it's probably the new keyword in the second constructor.
