### ISSUE TITLE
`@icon value=@drawable`  Conflict

### ISSUE THREAD

**Issue by solome** [satyan/sugar#322]
with `compile 'com.github.satyan:sugar:1.3'`

`@icon value=@drawable`  conflict!

error log:
```
Error:(54, 9) Attribute application@icon value=(@drawable/mt_logo) from AndroidManifest.xml:54:9
is also present at com.github.satyan:sugar:1.3:13:9 value=(@drawable/ic_launcher)
```

**Comment by cjimenezpacho** [comment]
Same here!

**Comment by satyan** [comment]
Try 1.3.1 https://github.com/satyan/sugar/issues/319#issuecomment-94562179

**Comment by cjimenezpacho** [comment]
Everything Ok! Thanks! @satyan :+1:

**Comment by Goutte** [comment]
I confirm that 1.3.1 solves that issue. Thanks !.

**Comment by solome** [comment]
same =>  #319
