### ISSUE TITLE
Don't put too much stuff into 1.4

### ISSUE THREAD

**Issue by black-snow** [satyan/sugar#324]
Hi there,

please don't put too many features into the 1.4 build. Instead I'd love to see some kind of a "release often"-strategy. 1.4 beta is already packed w/ important stuff.

Background: I would really like to have some features and fixes from 1.4 beta. As I fetch all my third-party-stuff via maven I don't want to make an exception for sugar and check back every now and then if 1.4 was released or not. Currently my code is packed w/ TODOs and workarounds stating "remove when 1.4 is available" or "change to XY when 1.4 ...".

Also this would make migrations from one version to another smaller and easier. I'd claim that developers rather like to do some little changes every now and then than to cope with a huge rewrite once.

**Comment by satyan** [comment]
Thanks for the suggestion. Makes total sense. Will start releasing stuff to maven more often.

**Comment by black-snow** [comment]
Awesome!

**Comment by black-snow** [comment]
Closing this one - looking forward to the next release

**Comment by black-snow** [comment]
@satyan is this project still being maintained? Is there gonna be a 1.4?

**Comment by satyan** [comment]
@black-snow There is a 1.4 version on maven central. I'm yet to update the documentation though. You're free to use it.

**Comment by satyan** [comment]
@sibeliusseraphini has been helping out with the issues lately.. Looking for some help on updating the documentation as per releases.

**Comment by black-snow** [comment]
@satyan great, are there any release notes / changelogs for 1.4? I'd help if I knew how to.

**Comment by sibeliusseraphini** [comment]
we should move the changelog from README.md to a CHANGELOG.md, and try to follow this: http://keepachangelog.com/

we can check the commits and closed issues from 1.3 to 1.4 add this to changelog

**Comment by black-snow** [comment]
+1 for this

**Comment by sibeliusseraphini** [comment]
@satyan where is the commit or the release for the v1.4 ?

**Comment by sibeliusseraphini** [comment]
I've moved changelog to CHANGELOG.md and update some info about it

**Comment by satyan** [comment]
@sibeliusseraphini This was the commit for 1.4 before maven publish.. https://github.com/satyan/sugar/commit/01504511c5d657563b2da0817904cfa184f3fbe2

**Comment by sibeliusseraphini** [comment]
@black-snow I've created the release for v1.4

I'll try to add the changelog, and see what to work for v1.5

**Comment by black-snow** [comment]
@sibeliusseraphini thanks
