### ISSUE TITLE
Sugar ORM create tables but do not save data

### ISSUE THREAD

**Issue by witalobenicio** [satyan/sugar#332]
Sugar ORM is creating my model tables, and when the .save() method is called it shows in log that object was saved.

The problem is that when i try to get the objects (over listAll, findAll and findwithQuery) i did not receive any object. So, its not being saved.

Im using sugar orm with wasp lib, and GSON lib.

**Comment by yuluyi** [comment]
Same issue here. But the data did save. I used sqlitestudio to inspect the data. It's there. But usding listAll, findAll can't get the results. Always return empty list.

**Comment by DoM4** [comment]
Same yuluyi issue.I can see the table populated but when I try to retrieve data by listAll/findAll,find I always get empty list

**Comment by galaxyfeeder** [comment]
Are you setting your own id?

It's what happened to me, on logcat appears as saved but then listAll() size is 0.

Issue #171 talks about this.

**Comment by franzejr** [comment]
@witalobenicio, it was happening the same thing with me. I was not matching all the fields in my POJO with sugarORM table I was created. As @galaxyfeeder  mentioned about ids... sugarORM creates an ID and I was also getting an ID from my JSON (btw, I am also using GSON) and It was kinda overriding my ID itself. I've created another field called idBackEnd or something like this.

1)Look your entire model class and check if all the fields you are receiving from your json matches
2)Change the ".db" in your AndroidManifest, just to test.

Hope you can get it working.

**Comment by DoM4** [comment]
I set my own ids and the table get populated.The problem is that some fields are lists of objects and they cannot be retrieve because I found it sugarORM doesn't support List<T>.
What I don't understand is what happen wheb lists get received, are they converted in array or in String like this :[1,2,3,4,5,6]?

**Comment by mobile1-vaibhav** [comment]
i have built an app .. Sugar creates every table for which i extend sugarrecord except one class . I dont know whats the issue .. uninstalled it many times . There's an empty constructor in it also .

**Comment by voghDev** [comment]
Confirmed. Sugar 1.3.1, 1.3 and 1.2 do not insert new entries on an empty table when save() is called after setId(). Only with id = null, entries are inserted.

**Comment by mobile1-vaibhav** [comment]
the issue was empty constructor needs to be public !! That was my mistake

**Comment by eironeia** [comment]
Love you 029vaibhav
