### ISSUE TITLE
No such column exception

### ISSUE THREAD

**Issue by fifielshafie** [satyan/sugar#335]
i work on android studio and use  Sugar 1.3 .... ..i have agreat problem with selection .. cause no such column  exception
i didnot know why ..Help me please 

this is my class  

package motdev.com.mybooks;

import com.orm.SugarRecord;

/**
 * Created by Administrator on 27/05/2015.
 */
public class data_details extends SugarRecord<data_details> {

   public String row_id ;
    public String row_title ;
   public String row_details ;

    public data_details(String row_id, String row_title, String row_details) {
        this.row_id = row_id;
        this.row_title = row_title;
        this.row_details = row_details;
    }
    public data_details() {

    }

    public String getRow_id() {
        return row_id;
        
    }

    public void setRow_id(String row_id) {
        this.row_id = row_id;
        
    }

    public String getRow_title() {
        return row_title;
        
    }

    public void setRow_title(String row_title) {
        this.row_title = row_title;
        
    }

    public String getRow_details() {
        return row_details;
        
    }

    public void setRow_details(String row_details) {
        this.row_details = row_details;
        
    }
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
This is Selection code

  Select select=Select.from(data_details.class).where(Condition.prop("row_id").eq("12"));
            List<data_details>data_list=select.list();

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////           
finally this is manifeast file

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="motdev.com.mybooks"
    android:versionCode="1"
    android:versionName="1.0"
    >

    <uses-permission android:name="com.google.android.providers.gsf.permission.READ_GSERVICES" />
<uses-permission android:name="android.permission.INTERNET"></uses-permission>
    <uses-permission android:name="motdev.com.permission.C2D_MESSAGE" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.VIBRATE" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:name="com.orm.SugarApp"
        android:label="@string/app_name"
        android:theme="@style/CustomActionBarTheme"

        >
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name=".menuActivity"
            android:parentActivityName="motdev.com.mybooks.MainActivity"
            ></activity>

        <activity android:name=".ViewPagerFragmentActivity"
            android:parentActivityName="motdev.com.mybooks.M_Main"
            ></activity>
        <activity android:name=".Fav_Activity"
                  android:parentActivityName="motdev.com.mybooks.M_Main"

            ></activity>

        <activity android:name=".M_Main"
            android:parentActivityName="motdev.com.mybooks.menuActivity"
            ></activity>
        <activity android:name=".ScreenSlideActivity"></activity>
        <activity android:name=".products_Activity"

            android:parentActivityName="motdev.com.mybooks.menuActivity"
            ></activity>
        <activity android:name=".adsActivity"
            android:parentActivityName="motdev.com.mybooks.M_Main"
            >

        </activity>
        <activity android:name=".Sencond_Main"
            android:screenOrientation="portrait"
            ></activity>
        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />

        <activity android:name="com.google.android.gms.ads.AdActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
            android:theme="@android:style/Theme.Translucent" />

        <meta-data android:name="DATBASEUNIGRP" android:value="example.db" />
        <meta-data android:name="VERSION" android:value="1" />
        <meta-data android:name="QUERY_LOG" android:value="true" />
        <meta-data android:name="DOMAIN_PACKAGE_NAME" android:value="motdev.com.mybooks" />

    </application>

</manifest>

**Comment by kifki** [comment]
Change `Select select=Select.from(data_details.class).where(Condition.prop("row_id").eq("12"));` to 
`Select select=Select.from(data_details.class).where(Condition.prop("rowid").eq("12"));`

See the last paragraph here http://satyan.github.io/sugar/query.html

**Comment by sibeliusseraphini** [comment]
we need to improve how Sugar convert property to column names on database, closing for now

**Comment by fifielshafie** [comment]
@kifki Thanks i will try it :)
