### ISSUE TITLE
How to use existing database?

### ISSUE THREAD

**Issue by alirezaaa** [satyan/sugar#337]
I created my database using DB Browser for SQLite and I want to import that database file to my project which uses Sugar ORM. How can I use my existing database?

**Comment by emdete** [comment]
this seems to be a wrong aproach for either android and even an orm. anyway you could use a dump restore cycle of the sqlite3 caommand line tool. the tool understands commands like .dump and .restore (use .help to see what commands and parameters are supported).

**Comment by alaaghribi** [comment]
Any news about this feature ?
