### ISSUE TITLE
Sugar doesn't save Timestamp

### ISSUE THREAD

**Issue by HectorFGarcia** [satyan/sugar#339]
When I do this:

sugar.setTS(new Timestamp(System.currentTimeMillis()));
sugar.save();

I can check using debugger that the TS is correct, it's the current date. But when I recover the TS by ID like this:

Sugar sugar = Sugar.findById(Lugar.class, 1);
Timestpam tS = sugar.getTS();

Then tS changed into a new Timestamp from 1970 (Epoch time) with a few seconds. Why.

**Comment by ellina0919** [comment]
Having exactly the same issue. How did you solve this?

**Comment by HectorFGarcia** [comment]
Saving the tS in a String. I still don't know how to fix it.

**Comment by HectorFGarcia** [comment]
I think project is abandoned so I close this.
