### ISSUE TITLE
Which gradle version has to be used to build sugar?

### ISSUE THREAD

**Issue by suyambu** [satyan/sugar#350]
I tried with gradle 2.4 but I am not able to import. I would like to improve Sugar lot. Help me with correct gradle version.

**Comment by JonatanSalas** [comment]
@suyambu actually sugar uses gradle plugin version 2.0.0 so the gradle version should be >= 2.10. There is a lot of to do. If you fork the project from the master know you will see that there are a lot of changes. Hope you can help us with some PR!
