### ISSUE TITLE
Reduce method count

### ISSUE THREAD

**Issue by JeroenMols** [satyan/sugar#354]
Due to the dependency on Guave, the method count of SugarORM has increased dramatically

* SugarORM 1.4 -> **14575** methods
* SugarORM 1.3 ->  184 methods

Suggestion to remove dependency on Guava as this has too big of an impact on the method footprint of sugar DB.

## My app with SugarORM 1.4
***********************************************************************************
DEX COUNTS                                                                      *
***********************************************************************************
44314                 (there are still 16222 references to burn...)             *
***********************************************************************************

## My app with SugarORM 1.3
***********************************************************************************
DEX COUNTS                                                                      *
***********************************************************************************
29923                 (there are still 30613 references to burn...)             *
***********************************************************************************

## My app without SugarORM
***********************************************************************************
DEX COUNTS                                                                      *
***********************************************************************************
29739                 (there are still 30797 references to burn...)             *
***********************************************************************************

**Comment by satyan** [comment]
I agree. I never liked Guava for that one reason. :) Will try to remove the dependency.

**Comment by dnalves** [comment]
Any news on this matter? :) 
Can anyone explain why MapMaker is being used? Because of the weak references?

**Comment by sibeliusseraphini** [comment]
@satyan I think this could help - https://github.com/mttkay/ignition/issues/23

**Comment by sibeliusseraphini** [comment]
@dnalves MapMaker is used for Cache, but it is kind of deprecated

**Comment by sibeliusseraphini** [comment]
fixed using #437

**Comment by isdzulqor** [comment]
I have problem, guys... I'd like to get a value from a table. If the column does not contain any value, then I am going to insert one. So I need getCount in my case.
My question is how to use getCount in this library, could you give me sample code, please? And where I can get the .db file to see my record table

**Comment by sibeliusseraphini** [comment]
@isdzulqor you can use method **count** of SugarRecord
