### ISSUE TITLE
I want to call a method after fetching an object

### ISSUE THREAD

**Issue by MIH1406** [satyan/sugar#355]
// Creation of an object from database.
    Book myBook = Book.findById(Book.class, 1l);

After `myBook` has bean fetched, I want to call a private method to perform some logic.
I want this method to be called automatically. Such as in the constructor.
I do not want to call this method after each time I fetch object from database.

### Example 1 (private):

    public class Book extends SugarRecord<Book> {
        public Book() {
            if(id != null && id > 0) {
                // However, this block will never be execuated because "id" is null, but I fetched Book with "id = 1"
                this.privateLogicMethod();
            }
        }

        private void privateLogicMethod() {
                ...
        }
    }

Somewhere in my code:

    Book myBook = Book.findById(Book.class, 1l);
    // But the "if" block is never execuated.

### Example 2 (public):

    public class Book extends SugarRecord<Book> {
        public Book() {
        }
        public void publicLogicMethod() {
                ...
        }
    }

Somewhere in my code:

    Book myBook = Book.findById(Book.class, 1l);
    if(myBook.getId() != null && myBook.getId() > 0) {
        this.privateLogicMethod();
    }
    // The "if" block IS execuated.

**Comment by satyan** [comment]
This is because when the object is instantiated, the value of "id" is null. After construction, the ORM sets the "id" value into the object.

I'd suggest to follow the approach you mentioned at the end, and not load up too many things during construction.

Hope it works for you.. thanks.

**Comment by MIH1406** [comment]
It would be good if there is a method called "onCreate" to allow user do anything after construction of an object.
