### ISSUE TITLE
Error in AndroidStudio after addubg Sugar to gradle file

### ISSUE THREAD

**Issue by maartenaalbers** [satyan/sugar#357]
After just adding the first step of the 'Getting started' to my build.gradle, I got an error after syncing:

Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '...../Android/sdk/build-tools/22.0.1/aapt'' finished with non-zero exit value 1

If I open my main activity I also see that the import for the R file is red...

**Comment by tkhduracell** [comment]
I get this to. Any ideas?

**Comment by tkhduracell** [comment]
You can fix it temporarily by using the JAR release instead of maven. 
```gradle
compile files('libs/sugar-1.4_beta.jar')
```
