### ISSUE TITLE
default Id auto increments

### ISSUE THREAD

**Issue by sathishsr** [satyan/sugar#364]
Hi Satyan, I am locked with sugar orm in a particular issue. The issue is,
Even after giving the deleteAll method for a table, the default id continues incrementing instead of starting from the first. Please help me in this issue. 

Am I missing something? Please, looking for your response.

**Comment by agoransson** [comment]
This is standard SQL behaviour I think, the autoincrementing id is just an atomic counter, it will continue to increment.

I think if you execute a raw query (see: http://satyan.github.io/sugar/query.html and http://stackoverflow.com/questions/9759502/resetting-autoincrement-in-android-sqlite) for resetting the autoincrement counter you'll be set.

**Comment by sathishsr** [comment]
Yes, thaks agoransson. I got the solution. 

Cheers,
Sathish Kumar S.R

**Comment by kartiraman** [comment]
Hi I am doing application in android, i am facing the same issue autoincrement,
I used the raw query as given below,
"Places.executeQuery("DELETE FROM SQLITE_SEQUENCE WHERE NAME = 'PLACES'"); 
but not working, help me to solve this issue.
