### ISSUE TITLE
failed to do file read got 0 amt 4096 last errno 0

### ISSUE THREAD

**Issue by makunomark** [satyan/sugar#366]
Hi Satyan, I get this error when running an application using sugar as a way to store data. It doesn't crash the application. Rather data is not saved. Here's the full excerpt:

07-27 16:42:36.730: I/Sugar(25949): create table
07-27 16:42:36.730: D/Sugar(25949): Fetching properties
07-27 16:42:36.731: I/Sugar(25949): creating table TABLE_NAME
07-27 16:42:36.732: E/SQLiteLog(25949): (10) Failed to do file read, got: 0, amt: 4096, last Errno: 0

The error occurs in some devices while in others it doesn't. What could be the cause of this?

**Comment by sibeliusseraphini** [comment]
@makunomark did you change any of your fields types?

this happen when you change the fields and didn't upgrade your database version
