### ISSUE TITLE
Exceeding number of file descriptors sqlite errror

### ISSUE THREAD

**Issue by makunomark** [satyan/sugar#367]
Hi all, I am developing an application using Sugar. Plus I am stuck and I believe you may help me. My issue is that at times when running my application, data is not saved. This is an excerpt of my logs of what I think might be causing data not to be saved. 

Iv googled around and the problem seems to be that  "system exceeded the total number of open fd(file discriptors) due to that its facing this problem". Since I'm using sugar to abstract my SQLite db procedures, Id like to know how best to fix this.

I/Sugar(20256): Credits saved : 31
D/dalvikvm(20256): threadid=89: exiting
D/dalvikvm(20256): threadid=89: bye!
E/SQLiteLog(20256): (257) Open fd: 57, file: /data/data/com.toe.gwap/databases/gwap_db.db-journal
E/SQLiteLog(20256): (257) Close fd: 57
E/SQLiteLog(20256): (257) Open fd: 57, file: /data/data/com.toe.gwap/databases/gwap_db.db-journal
E/SQLiteLog(20256): (257) Close fd: 57
E/SQLiteLog(20256): (257) Open fd: 57, file: /data/data/com.toe.gwap/databases/gwap_db.db-journal
E/SQLiteLog(20256): (257) Close fd: 57
E/SQLiteLog(20256): (257) Open fd: 57, file: /data/data/com.toe.gwap/databases/gwap_db.db-journal
I/Sugar(20256): Debits saved : 40

**Comment by RayHuo** [comment]
Have you fixed this? Get the same problem...

**Comment by makunomark** [comment]
@RayHuo Hi, Yes I did fix it.
I was running code in Threads in a loop. Noob stuff.
Have you managed to solve this issue?
