### ISSUE TITLE
List return all values null, except Id

### ISSUE THREAD

**Issue by tsuharesu** [satyan/sugar#37]
Hi. I have two classes that behave different. One return all values, all right when I use ListAll (or whatever other method). The other class return objects only with Id set, all other values null. I'm trying to figure out what is happening but I don't know.

Im using:
- Sugar as a library project (is it better to use Jar?)
- Android Annotations (but I don't think this is the problem, as the other class work)
- Android Studio

Here is the problematic class. The subject object relationed to it is coming with everything set too. I don't know what can be wrong :sweat: 

``` java
public class Am extends SugarRecord<Am> {
    private Float grade;
    private Integer half;
    private Subject subject;

    public Am(Context context) {
        super(context);
    }

    // getters and setters
}
```

**Comment by behi198** [comment]
I'm having this problem using version 1.5!
