### ISSUE TITLE
Dropping Tables

### ISSUE THREAD

**Issue by JA-VON** [satyan/sugar#374]
I thought upgrading the version of the database would empty the contents of the tables but it doesn't seem to do so, how do I accomplish this? 

I'm using version sugar version 1.4

**Comment by JA-VON** [comment]
Resolved it by deleting the table elements int the <VERSION_NUMBER>.sql file in the assets folder per the documentation.

**Comment by sibeliusseraphini** [comment]
@JA-VON did you use DROP TABLE?

**Comment by JA-VON** [comment]
Yes I did, in the sql file.
