### ISSUE TITLE
How to turn off Sugar logging

### ISSUE THREAD

**Issue by maarek** [satyan/sugar#375]
Even though I have commented out the following, I still see model saved in the log. I tried with setting it to false but that still didn't work.

**Comment by Siddounet** [comment]
Hi,
`QUERY_LOG 	Logs the generated Select queries.` 
So, when you save, logs are activated, I didn't see any attribute to disable it, & I prefer it disable too. 
`QUERY_LOG` is only for SELECT... :(

**Comment by jfabrix101** [comment]
Inside the save method there is log command

>> Log.i("Sugar", object.getClass().getSimpleName() + " saved : " + id);

so the log info are always shown (at INFO level).

Should be possible to add some "LogLevel" suport, i.e. through configuration choose if show or not this (and other) kind of log ?

**Comment by maarek** [comment]
Yes, I have created a fork where I have commented out all logging for now. In the next couple of days I will wrap it all with the ability to adjust the log level and create a pull request. Seems like quite a few PRs are sitting there though.

**Comment by sushantkhanna** [comment]
Was this resolved?

**Comment by sibelius** [comment]
use `<meta-data android:name="QUERY_LOG" android:value="false" />` to disable logs

**Comment by heitorcolangelo** [comment]
Is not working, it is still logging.

**Comment by sibelius** [comment]
R u using master?

**Comment by heitorcolangelo** [comment]
What do you mean by using master?

**Comment by sibelius** [comment]
Which version of sugar r u using? Follow README to use master version (latest)

**Comment by heitorcolangelo** [comment]
No, I haven't notice this point.
I'll try and let you know if it works.
Thank you!
