### ISSUE TITLE
One to One Relationships not updating

### ISSUE THREAD

**Issue by andrespalma2** [satyan/sugar#392]
Hi! 
I have the following class 

public class Project extends SugarRecord<Project> implements Serializable{
    String projectName;
    Client client;
    String description;
    Category category;
}
 where both Client and Category extends SugarRecord.

If i want to update a Project, whats the right way to do so?
After I get a reference to the project I want to update and modifie all the fields, the only ones that are getting updated in the database are "description" and "project Name", whereas "client" and "category" remains unaltered.
Does Sugar ORM updates the references to other objects on the database?

Thanks!!

Almost Forgot! Im using sugar 1.3.1

**Comment by sureshjoshi** [comment]
@andrespalma2 Did you ever solve this?
