### ISSUE TITLE
Data not persisting between activities?

### ISSUE THREAD

**Issue by MisterSpicy** [satyan/sugar#396]
This issue happens at different times for different clients, so I'm not quite sure whats happening.

Description : I have a basic messaging app that shows on one screen, a list of messages, the last time a message was sent/received, and the last message text.  In the next activity, I have the list of messages.  Standard stuff.  I'm encountering a problem where the message text and time are not being updated properly, but it happens in different ways on different devices.  When I navigate back to the list of chat threads, it re-builds the activity, which does a fresh query to the DB with a Conversations.findAll(...)

The issue is that when I send a message (receiving messages seems to work), the last_message is not being saved.  I find it strange since the send and receive messages follows the same code path, and within the activity, the data shows up correctly.  When I navigate out, and re-query the DB, the changes do not persist.

Even more confusing, is that this presents in different ways on different devices.  One device will update completely normally, except in the case where I'm talking to myself.

One device only updates on received messages, but not sent.

This leads me to think that maybe it has something to do with the sqlite version or Android version, but I believe its' the same root issue.

All messages run through the same code:
```
  public static void addMessage(Message msg){

        Log.i(TAG, "Inserting Message (SUGAR) " + msg.toString());
        SugarDb.Conversation bc = getConversation(msg.friend_id);

        switch(msg.getType()){
            case Constants.TYPE_IMAGE_MESSAGE:
                Log.i(TAG, "Type_Image_Message");
                if(msg.getLeft()){
                    bc.setLastMessageText(msg.getUsername() + " sent you an photo.");
                } else {
                    bc.setLastMessageText("You sent a photo.");
                }
                bc.setLastMessageTime(msg.getTimestamp());

                break;
            case Constants.TYPE_BANNER_MESSAGE:
                Log.i(TAG, "Type_Banner_Message");
                //Don't update last message for a banner update
                break;
            case Constants.TYPE_STICKER_MESSAGE:
                Log.i(TAG, "Type_Sticker_Message");
                if(msg.getLeft()){
                    bc.setLastMessageText(msg.getUsername() + " sent you a sticker.");
                } else {
                    bc.setLastMessageText("You sent a sticker.");
                }

                bc.setLastMessageTime(msg.getTimestamp());
                break;
            default:
                Log.i(TAG, "Setting Last Message To Text + " + msg.getText());
                bc.setLastMessageText(msg.getText());
                bc.setLastMessageTime(msg.getTimestamp());
                Log.i(TAG, "Last Message after set : " + bc.getLastMessageText());
                break;
        }

        bc.setUnreadCount(bc.getUnreadCount()+1);
        bc.save();

        SugarDb.Message bm = new SugarDb.BuzzMessage(
                bc,
                msg.getLeft(),
                0,
                msg.getText(),
                msg.getTimestamp(),
                msg.getType(),
                msg.getUnread());

        bm.save();

        Log.i(TAG, "ADDMESSAGE: set last message text to : " + bc.getLastMessageText());
        Log.i(TAG, "ADDMESSAGE: MESSAGE bc.tostring " + bc.toString());

    }
```

I guess my main question is if my getConversation, then save() is doing what it's supposed to be doing.  I have read some of the other issues that I can get conflicting Insert and Update states if I'm not careful.

the code for getConversation:
```
public static SugarDb.Conversation getConversation(String friend_id){

        Log.i(TAG, "Sugar: getConversation: " + friend_id);
        List<SugarDb.BuzzConversation> bc = SugarDb.Conversation.find(SugarDb.Conversation.class, "friend_id = ?", friend_id);
        if(bc.isEmpty()){
            Log.i(TAG, "No Conversation Found");
            return null;
        } else {
            Log.i(TAG, "Sugar: Found Conversation with friend id : " + bc.get(0).getFriendId());
            return bc.get(0);
        }
    }
```

Thanks!

**Comment by sibeliusseraphini** [comment]
@MisterSpicy could you post your SugarRecords?
