### ISSUE TITLE
Getid returns null

### ISSUE THREAD

**Issue by hoshomoh** [satyan/sugar#398]
I am implementing sugarorm with a listadapter. When the user clicks on an item,  I want to get the Id of that item in the database.  Other fields are being returned but getid returns null.

**Comment by NirHUJI** [comment]
same problem here. 
i found out that the id field is being initialized only after you save the object. so a simple work-around would be:
Book book = new Book(ctx, "Title here", "2nd edition")
book.save();
book.getId();

**Comment by hoshomoh** [comment]
Okay. Thanks @NirHUJI . I later got this to work. Isssue was with serialization.
