### ISSUE TITLE
add Mockito for Unit tests

### ISSUE THREAD

**Issue by RoyMontoya** [satyan/sugar#404]
Hi, everyone i would like to add tests to the sugar library and i think it would be useful to have Mockito framework. Mockito is an open source project that allows you to easily create mocks and stubs for unit testing.

I think that sugar right now needs more testing, and mockito can help us with this. I leave the link.

http://mockito.org/

Any feedback or opinions are appreciated.

**Comment by sibeliusseraphini** [comment]
Great, try to improve the coverage if this tests
