### ISSUE TITLE
Attribute application@allowBackup is also present at [com.github.satyan:sugar:1.3] 

### ISSUE THREAD

**Issue by tkeil69575** [satyan/sugar#406]
I getting this when try to compile

C:\dev\workspace\ContactLoggerApp\app\src\main\AndroidManifest.xml:25:9-36 Error:
Attribute application@allowBackup value=(false) from AndroidManifest.xml:25:9-36
is also present at [com.github.satyan:sugar:1.3] AndroidManifest.xml:12:9-35 value=(true)
Suggestion: add 'tools:replace="android:allowBackup"' to element at AndroidManifest.xml:23:5-106:19 to override
C:\dev\workspace\ContactLoggerApp\app\src\main\AndroidManifest.xml:26:9-43 Error:
Attribute application@icon value=(@mipmap/ic_launcher) from AndroidManifest.xml:26:9-43
is also present at [com.github.satyan:sugar:1.3] AndroidManifest.xml:13:9-45 value=(@drawable/ic_launcher)
Suggestion: add 'tools:replace="android:icon"' to element at AndroidManifest.xml:23:5-106:19 to override

**Comment by tkeil69575** [comment]
Okay, updating to 1.3.1 solved the issue :)

**Comment by omashano** [comment]
**Suggestion: add 'tools:replace="android:XXXX"' to element at AndroidManifest.xml to override**
just replace XXXX with the attribute you are having problems with and add to the <application> element in your Manifest. This way you will override any value set by the library for those attributes.

For example:
```
<application
    tools:replace="android:icon"
    android:icon="@drawable/my_launcher"
    android:theme="@style/AppTheme"
    android:label="@string/app_name">

        <!-- your stuff here -->

</application>
```
