### ISSUE TITLE
UnsatisfiedLinkError error

### ISSUE THREAD

**Issue by siddhpuraamitr** [satyan/sugar#418]
Whenever I execute following code

List<BusinessFacilityInformation> tempFillForms = BusinessFacilityInformation.find(BusinessFacilityInformation.class, "MARKER_ID=?", String.valueOf(markerId));

I was getting below error

	java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.chorstreamforms-1/base.apk"],nativeLibraryDirectories=[/data/app/com.chorstreamforms-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libRSSupport.so"
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at java.lang.Runtime.loadLibrary(Runtime.java:366)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at java.lang.System.loadLibrary(System.java:988)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at com.esri.core.analysis.LineOfSight.<clinit>(SourceFile:48)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at java.lang.Class.classForName(Native Method)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at java.lang.Class.forName(Class.java:309)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at com.orm.util.ReflectionUtil.getDomainClass(ReflectionUtil.java:270)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at com.orm.util.ReflectionUtil.getDomainClasses(ReflectionUtil.java:254)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at com.orm.SchemaGenerator.createDatabase(SchemaGenerator.java:37)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at com.orm.SugarDb.onCreate(SugarDb.java:26)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at com.orm.SugarDb.getDB(SugarDb.java:36)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at com.orm.SugarRecord.find(SugarRecord.java:189)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at com.orm.SugarRecord.find(SugarRecord.java:158)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at com.chorstreamforms.FillFormActivity.onCreate(FillFormActivity.java:57)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5990)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:151)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5254)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	11-05 18:26:05.187 31771-31771/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by siddhpuraamitr** [comment]
Finally I have resolved the issue by putting one line of IF condition in your code

In your **ReflectionUtil.java** file

There is function 

    private static Class getDomainClass(String className, Context context) {


I have put below condition 

        if(!className.contains("com.esri.core.analysis") && !className.contains("jcifs") && !className.contains("org.codehaus"))
            discoveredClass = Class.forName(className, true, context.getClass().getClassLoader());



I have to skip calling my library's class name, 

        if(!className.contains("com.esri.core.analysis") && !className.contains("jcifs") && !className.contains("org.codehaus"))


I don't know why you need to call whole project's class name


Anyway try to resolve this issue in next update


But thank you so much for making this awesome library, we are very thankful to you and it saves our lots of time in developing 

Thanks a lot

**Comment by sibeliusseraphini** [comment]
closing now because a multidex support PR was merged on master
