### ISSUE TITLE
SQLiteException : duplicate column name in alter table in upgrade script

### ISSUE THREAD

**Issue by vahidaghakhany** [satyan/sugar#419]
i have force close in many of users, its about upgrade script.
i think sugar run upgrade script twice.

android.database.sqlite.SQLiteException
      :  duplicate column name
      :  HEAVY_NEG (code 1)
      :  , while compiling
      :  alter table FINE_TITLE add column HEAVY_NEG;

**Comment by dangalg** [comment]
could it be you forgot to add the column in your last release to the migration file, and then tried adding it in a later version?
that's what happened to me and I have no idea how to fix it...

**Comment by vahidaghakhany** [comment]
@dangalg i find how it created.
in new installation sugar create tables from model class then run migration files. i think sugar should be run migration file just for upgrade version and not for new version.

**Comment by rinkudas** [comment]
@dangalg you are correct. I am facing the same problem. Upgrade script is running twice. I am not able to Alter my existing table if I need to add one more extra column. Any idea how to handle this?

**Comment by hairiecs** [comment]
@dangalg, @rinkudas you are right. I'm facing the same problem as well. Not able to add a new column right now. Any workaround on this?

**Comment by sibeliusseraphini** [comment]
In master version, Sugar will automatically generate new columns added to models - fixed with #328

**Comment by RaphaelRoyerRivard** [comment]
I still have this problem on 1.5

**Comment by arahik** [comment]
@vahidaghakhany were you able to solve your problem

**Comment by arahik** [comment]
@RaphaelRoyerRivard Did you manage to solve the issue.I also have 1.5 and I am having the same problem

**Comment by RaphaelRoyerRivard** [comment]
No, I believe it will need some change in the Sugar base code...

**Comment by NehaSevlani** [comment]
Hi,
Did anyone solved this issue. I am having the same problem in my applications and i need to get this resolved asap.

**Comment by mutaherraza** [comment]
Hi,
Just upgrade app version. You don't need to write migration. New columns are added automatically.
