### ISSUE TITLE
Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:45:9-36   	is also present at [com.github.satyan:sugar:1.3] AndroidManifest.xml:12:9-35 value=(true)

### ISSUE THREAD

**Issue by farmazon3000** [satyan/sugar#420]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:45:9-36
  	is also present at [com.github.satyan:sugar:1.3] AndroidManifest.xml:12:9-35 value=(true)
  	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:9:5-28:19 to override

**Comment by Ewg777** [comment]
https://github.com/satyan/sugar/issues/406
