### ISSUE TITLE
Adding sugar to app dependencies causes Gradle finished with non-zero exit value 1 (ic_launcher.png: error: Duplicate file)

### ISSUE THREAD

**Issue by farmazon3000** [satyan/sugar#421]
Like described here http://stackoverflow.com/questions/29965398/gradle-finished-with-non-zero-exit-value-1-ic-launcher-png-error-duplicate-fi

**Comment by farmazon3000** [comment]
All because there are icons (what for???) in:
```
sugar/1.3/res/drawable-hdpi-v4/ic_launcher.png
sugar/1.3/res/drawable-mdpi-v4/ic_launcher.png
sugar/1.3/res/drawable-xhdpi-v4/ic_launcher.png
sugar/1.3/res/drawable-xxhdpi-v4/ic_launcher.png
```

**Comment by omashano** [comment]
I had the same problem until this morning.
I renamed my icon and added `tools:replace="android:icon"` to my <application> tag in the manifest since it complained about a problem while merging the manifest files.
