### ISSUE TITLE
Sugar 1.4 Examples

### ISSUE THREAD

**Issue by MikeRzDev** [satyan/sugar#427]
Hi, it seems like sugar 1.4 implements a lot of new features and deprecates also a lot of things, the example of "getting started" is not working with 1.4, could you please update the getting started page for 1.4, thank you!.

**Comment by sibeliusseraphini** [comment]
I'm trying to merge some pull requests, improve the changelog, and improve the docs.

In fact 1.4 should be 2.0 because it breaks if your upgrading from 1.3

@MikeRzDev - Feel free to dig into the code, and do some pull requests to improve README.md and docs in general

**Comment by sibeliusseraphini** [comment]
docs updated
