### ISSUE TITLE
Can't use Find or SearchWithQuery with multiples args

### ISSUE THREAD

**Issue by daybson** [satyan/sugar#428]
I'm just doing:
Note.find(Person.class, "name = ? and title = ?", "satya", "title1"); 
or 
Note.findWithQuery(Person.class, "Select * from PERSON where name = ? and title = ?", "satya", "title1");

.. and surprise?! Always return a list size 0, but If I do Person.listAll(Person.class) I cant get the elements. I already checked the parameters values, and they are correct.

I don't know what else to do to perform a simple select.... My experience with sugarORM is just getting worse every day... (see Issue #422)

Here is the exactly query that WORKS on Sqlite Expert:
SELECT * FROM TABLEX WHERE fielda = 1 AND fieldb >= 1 AND fieldb <= 1000 --or
SELECT * FROM TABLEX WHERE fielda = 1 AND fieldb BWETWEEN 1 AND  1000

**Comment by sibeliusseraphini** [comment]
@daybson why are you using Note.find(Person.class) instead of Person.find(Person.class) ?

can you provide your Note and Person class definition?

are you using proguard?
