### ISSUE TITLE
Renaming column names

### ISSUE THREAD

**Issue by shreenivas-ch** [satyan/sugar#429]
when I define column as tablename_somecolumnname in java class, sugar ORM internally creates column  as tablenamesomecolumnname, because of this I am facing so much issues, and there is no proper documentation of why it does like this and what are all conditions where it changes column name. So I am shifting to normal android database implementation of creating DB.

**Comment by nseidm1** [comment]
It's not entirely a major issue. Camel case SugarRecords are also renamed to ex:

PushMmsMessage ---> PUSH_MMS_MESSAGE

I has trouble updating my databases to add columns, had no idea what the database name was :-P Had to dump the Sqlite databases from an emulator and view it on my comp.

**Comment by VLEIX** [comment]
Read the last lines from http://satyan.github.io/sugar/query.html :)

**Comment by sibeliusseraphini** [comment]
@shreenivas-ch @nseidm1 you guys can use NamingHelper.toSQLName(Model.class) to get the name of the TABLE

you can also use @Column(name="columnName") to define a custom column name for a property

**Comment by marufsharia** [comment]
how to use a custom column name for the existing database ??
