### ISSUE TITLE
Tutorial for 1.4 version?

### ISSUE THREAD

**Issue by marinovskiy** [satyan/sugar#431]
There are any tutorial for new 1.4 version? Cause last example was pushed 7-8 months ago.

**Comment by adist** [comment]
Yes, i also looking for this tutorial on this version...

I'm upgrading from 1.3 to 1.3.1 just work fine with same tutorial. But when i migrate to 1.4, my source doesn't affect to my DB. Especially @NotNull annotation.

Is there any different way to use this?

I'm waiting for this tutorial. Thanks ^_^

**Comment by colabug** [comment]
Yeah, it's confusing to get started. +1 for a 1.4 tutorial

**Comment by sibeliusseraphini** [comment]
I've put some examples using 1.4 and master repo on [README.md](https://github.com/satyan/sugar/blob/master/README.md)
