### ISSUE TITLE
Using your own application class

### ISSUE THREAD

**Issue by QuickBrownFoxy** [satyan/sugar#44]
SugarApp requires it to be set as application class but I am using my own class with more methods. Is there any way getting over this requirement?

**Comment by PGMacDesign** [comment]
My apologies for revisiting this, but after your changes were made, what do I need to implement within my MyApplication class for this to run? As with the user above, I am currently running a MyApplication extends  Application setup for Singleton context purposes. Do I implement something after the extends? Or is there an entirely different solution?
Thanks!
-Sil
