### ISSUE TITLE
Table Creation Order

### ISSUE THREAD

**Issue by adiyatmubarak** [satyan/sugar#442]
Hii I create an application with SugarORM by following quick start in http://satyan.github.io/sugar/getting-started.html

I have 2 Activities & 2 models.
Activities:
    - `HomeActivity`
    - `LoginActivity`
Models:
    - `AuthToken`
    - `Promo`

and the first activity is `HomeActivity` and there is Promo query at this activity, the problem is sugar ORM create my entities when I opening my `LoginActivity` instead of my first launched `HomeActivity`.

is sugar ORM use alphabet order for table creation?

Here is my Manifest config:
```
<application
    android:fullBackupContent="false"
    android:name="com.orm.SugarApp"
    android:allowBackup="true"
    android:icon="@mipmap/ic_kargo"
    android:label="@string/app_name"
    android:supportsRtl="true"
    tools:replace="android:icon">

    <meta-data android:name="DATABASE" android:value="kargo.db"/>
    <meta-data android:name="VERSION" android:value="1"/>
    <meta-data android:name="QUERY_LOG" android:value="true"/>
    <meta-data android:name="DOMAIN_PACKAGE_NAME" android:value="id.co.kargo.kargoapp.entities"/>

    ....

</application>
```

**Comment by nurolopher** [comment]
Sugar ORM will create the database when you first launch your app. It doesn't create the tables until the first query to the database.
