### ISSUE TITLE
Support for null relationship

### ISSUE THREAD

**Issue by skarllot** [satyan/sugar#445]
Sugar ORM currently does not support null relationship.

E.g.
``` java
class Table1 extends SugarRecord {
    private Table2 field1
    ...
}

class Table2 extends SugarRecord {
    private String field1
    ...
}
```

If I try to save a Table1 instance with null relationship, then a NullPointerException is thrown.
``` java
...
Table1 record = new Table1();
SugarRecord.save(record);    // <-- NullPointerException on field1
```

**Comment by sibeliusseraphini** [comment]
@skarllot, the master version does not have this problem, it will put a 0 instead of null on the field1 of Table1

I think it should put null instead, I will investigate more on this issue
