### ISSUE TITLE
Saving an Image using Sugar ORM 

### ISSUE THREAD

**Issue by smholsen** [satyan/sugar#446]
Hello!

So, I am trying to save an Image using sugarORM. 
I first turn it into a ByteArray, and save the byteArray, and then when loading, I turn that byteArray back into a BitMap. 

Now, All the other values I am saving works fine, and I have also tried to display the image by first making it into a byte array and then turning it back into a Bitmap and then deisplaying it. This works fine. The problem arises when I to load. 

After loading, the byteArray gets a value, but after turning it back into a bitMap and diplaying it, it just shows a white image, and the BitMap has the value null. So something goes wrong during the conversion from byteArray to Bitmap I guess? Since the bytearray has SOME VALUE after loading, I do not know 100% certain that this is the same value as I saved, but I cant see any reason why it would change :S

This is the code I use for saving and loading :

    public void saveImage(){
        imageToSave = Utilities.getBytes(backGround);
    }

    public void updateImage(){
        backGround = Utilities.getImage(imageToSave);
    }

This is the Utilities class:

    public class Utilities {

    public static byte[] getBytes(Bitmap bitmap) {
        ByteArrayOutputStream stream=new ByteArrayOutputStream();
        bitmap.compress(Bitmap.CompressFormat.PNG,100, stream);
        return stream.toByteArray();
    }

    public static Bitmap getImage(byte[] image)
    {
        return BitmapFactory.decodeByteArray(image, 0, image.length);
    }

    }

imageToSave is a variable inside the TrackedEvent class. 
The TrackedEventObject is saved from the MainActivityClass on line 439, doing this:
    newEvent.saveImage();
    newEvent.save();

where newEvent is an Object of the type TrackedEvent. 

The rest of the code is available here: https://github.com/smholsen/BigDayCountdown/tree/master/app/src/main/java/com/simonm/bigdaycountdown

Any idea on what I am doing wrong?

**Comment by sibeliusseraphini** [comment]
are you calling **.save()** in TrackedEvent after **saveImage()** ?

The TrackedEvent will only store the image on the database when you call the save method on SugarRecord

**Comment by smholsen** [comment]
Yes, in the MainActivity they are called in this order: 

                newEvent.saveImage();

                newEvent.save();

Where newEvent is an object of the type TrackedEvent.

**Comment by sibeliusseraphini** [comment]
What is the result of these logs? Log newEvent.imageToSave after newEvent.save() as well, try to use the Android Studio debug to check the behavior of SugarRecord save method

```
Log.i("imageToSaveBEFORESAVE", String.valueOf(Utilities.getBytes(newEvent.backGround)));
newEvent.saveImage();
Log.i("imageToSaveAFTERSAVE", String.valueOf(newEvent.imageToSave));
```

**Comment by smholsen** [comment]
Hey mate I just found out I was using this: 
compile 'com.github.satyan:sugar:1.3'
instead of this:
compile 'com.github.satyan:sugar:1.4'

After changing this it now works! =)

**Comment by sibeliusseraphini** [comment]
I think you should use the debug to find the reason for this error

**Comment by smholsen** [comment]
I will try to do this, but I unfortunately have no experience on how to use the debug mode in android studio, and while running the app on my device. So I kinda have little knowledge on how to do it :p But I am still supposed to reference the saved data the same way, right? 

Like for example

    TrackedEvent.listAll(TrackedEvent.class) 

?

Sorry for stupid questions and stuff, but I am kinda new to this... I really appreciate your help mate :)

**Comment by sibeliusseraphini** [comment]
http://developer.android.com/tools/debugging/debugging-studio.html

**Comment by smholsen** [comment]
Is Context a required argument in v1.4? =)

**Comment by smholsen** [comment]
Ok, so I ran the debugger, both on the save() method and on the 

    TrackedEvent.findById(TrackedEvent.class, Long.valueOf(1)) . 

On the save() method it looked to me as everything ran through smoothly, but when testing the 
    
    TrackedEvent.findById(TrackedEvent.class, Long.valueOf(1)) 

I ran into some trouble. 
I believe it ran OK all the way untill it was supposed to pick out the first element of the db. Thats when it gave me this:

    12-01 22:32:07.985 13258-13258/com.simonm.bigdaycountdown E/CursorWindow: Failed to read row 0, column 0 from a CursorWindow which has 0 rows, 5 columns.
    12-01 22:33:59.483 13258-13258/com.simonm.bigdaycountdown W/System.err: java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.

But I am unfortunately not skilled enough to be able to troubleshoot this any further. 

If you have any idea of what the problem might be then I would really appreciate it :)

If not; Thanks alot for the help anyways! :) 

Sugar ORM is really impressive, and the 1.3 version worked like a charm for me, except for the image :) 

Best regards :)

**Comment by sibeliusseraphini** [comment]
I think there is not a TrackedEvent with ID 1, that's the problem. Try to Log all TrackedEvents with theirs IDs

**Comment by smholsen** [comment]
Thanks for the tips! :) 
So, I tried to do this:

        for (TrackedEvent savedEvent : TrackedEvent.listAll(TrackedEvent.class)){
            Log.i("checkEvents", String.valueOf(savedEvent.getId()));
        }

But I get the same error:

    12-02 12:28:35.601 15545-15545/com.simonm.bigdaycountdown E/CursorWindow: Failed to read row 0, column 0 from a CursorWindow which has 0 rows, 5 columns.
    12-02 12:28:35.601 15545-15545/com.simonm.bigdaycountdown W/System.err: java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    12-02 12:28:35.602 15545-15545/com.simonm.bigdaycountdown W/System.err:     at android.database.CursorWindow.nativeGetLong(Native Method)
    12-02 12:28:35.602 15545-15545/com.simonm.bigdaycountdown W/System.err:     at android.database.CursorWindow.getLong(CursorWindow.java:511)
    12-02 12:28:35.602 15545-15545/com.simonm.bigdaycountdown W/System.err:     at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
    12-02 12:28:35.602 15545-15545/com.simonm.bigdaycountdown W/System.err:     at com.orm.SugarRecord.inflate(SugarRecord.java:296)
    12-02 12:28:35.602 15545-15545/com.simonm.bigdaycountdown W/System.err:     at com.orm.SugarRecord.find(SugarRecord.java:197)
    12-02 12:28:35.602 15545-15545/com.simonm.bigdaycountdown W/System.err:     at com.orm.SugarRecord.listAll(SugarRecord.java:94)
    12-02 12:28:35.602 15545-15545/com.simonm.bigdaycountdown W/System.err:     at com.simonm.bigdaycountdown.MainActivity.initVars(MainActivity.java:169)
    12-02 12:28:35.602 15545-15545/com.simonm.bigdaycountdown W/System.err:     at com.simonm.bigdaycountdown.MainActivity.onCreate(MainActivity.java:128)
    12-02 12:28:35.602 15545-15545/com.simonm.bigdaycountdown W/System.err:     at android.app.Activity.performCreate(Activity.java:5976)
    12-02 12:28:35.602 15545-15545/com.simonm.bigdaycountdown W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
    12-02 12:28:35.602 15545-15545/com.simonm.bigdaycountdown W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2297)
    12-02 12:28:35.602 15545-15545/com.simonm.bigdaycountdown W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404)
    12-02 12:28:35.602 15545-15545/com.simonm.bigdaycountdown W/System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:145)
    12-02 12:28:35.602 15545-15545/com.simonm.bigdaycountdown W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1323)
    12-02 12:28:35.602 15545-15545/com.simonm.bigdaycountdown W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
    12-02 12:28:35.602 15545-15545/com.simonm.bigdaycountdown W/System.err:     at android.os.Looper.loop(Looper.java:135)
    12-02 12:28:35.602 15545-15545/com.simonm.bigdaycountdown W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5319)
    12-02 12:28:35.602 15545-15545/com.simonm.bigdaycountdown W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
    12-02 12:28:35.602 15545-15545/com.simonm.bigdaycountdown W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
    12-02 12:28:35.602 15545-15545/com.simonm.bigdaycountdown W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
    12-02 12:28:35.602 15545-15545/com.simonm.bigdaycountdown W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
    12-02 12:28:35.603 15545-15545/com.simonm.bigdaycountdown D/SQL Log: SQLiteQuery: SELECT * FROM TRACKED_EVENT
    12-02 12:28:35.628 15545-15545/com.simonm.bigdaycountdown W/CursorWindow: Window is full: requested allocation 11433122 bytes, free space 2096669 bytes, window size 2097152 bytes
    12-02 12:28:35.705 15545-15545/com.simonm.bigdaycountdown W/CursorWindow: Window is full: requested allocation 11433122 bytes, free space 2096669 bytes, window size 2097152 bytes

So I dont think that is the problem... or?

**Comment by sibeliusseraphini** [comment]
@smholsen could you update to sugar 1.4 (or master), and try to debug the listAll method?

**Comment by smholsen** [comment]
I am using version 1.4.
So, the error I posted in my last comment was actually from version 1.4 and using the listAll method.. Is there anything specific I should look for while doing the debugging?

**Comment by sibeliusseraphini** [comment]
try to see in which method it crashes

**Comment by smholsen** [comment]
Ok, so I believe the crash happens here:
    
    private SQLiteDatabase(String path, int openFlags, CursorFactory cursorFactory,
            DatabaseErrorHandler errorHandler) {
        mCursorFactory = cursorFactory;
        mErrorHandler = errorHandler != null ? errorHandler : new DefaultDatabaseErrorHandler();
        mConfigurationLocked = new SQLiteDatabaseConfiguration(path, openFlags);
    }

Because after clicking "Step Into" on it, my variables updates to this: http://i.imgur.com/fcSJ1Mm.jpg

Does this tell you anything? 
Thanks for taking time to help me with this :)

**Comment by sibeliusseraphini** [comment]
maybe it is a problem in your manifest

we can talk tomorrow on [![Join the chat at https://gitter.im/satyan/sugar](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/satyan/sugar?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by smholsen** [comment]
That would be awesome! Thanks alot! :) 

What time will you be on there you think? What timezone? :)

**Comment by smholsen** [comment]
So, my problem was veyr similar to this: 

http://stackoverflow.com/questions/26783143/error-while-trying-save-and-retrieve-images-into-database-in-android/26797130#26797130

Where 2 different solutions are posted. 

I am basically just going to store the images locally and then just save the url to the images with sugar :)

Thanks alot for the help! :)
