### ISSUE TITLE
[Question] Errors when trying to retrieve saved data

### ISSUE THREAD

**Issue by smholsen** [satyan/sugar#448]
I earlier posted this thread: https://github.com/satyan/sugar/issues/446 (Thanks alot for the help btw! :)

But since I cant re-open threads I started a new Issue (Sorry if this was the wrong way to do it)  )

Well, I guess changing it helped, but I ran into another problem:
Now I think the saving works fine, I get this confirmation in the Log after saving, 

    12-01 19:28:27.959 14386-14386/com.simonm.bigdaycountdown D/Sugar: Fetching properties
    12-01 19:28:28.780 14386-14386/com.simonm.bigdaycountdown I/Sugar: TrackedEvent saved : 1

But when loading I get this error whenever I try to get   TrackedEvent.listAll(TrackedEvent.class)  : 

    12-01 19:30:20.123 17358-17358/com.simonm.bigdaycountdown E/CursorWindow: Failed to read row 0, column 0 from a CursorWindow which has 0 rows, 5 columns.
    12-01 19:30:20.123 17358-17358/com.simonm.bigdaycountdown W/System.err: java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    12-01 19:30:20.123 17358-17358/com.simonm.bigdaycountdown W/System.err:     at android.database.CursorWindow.nativeGetLong(Native Method)
    12-01 19:30:20.123 17358-17358/com.simonm.bigdaycountdown W/System.err:     at android.database.CursorWindow.getLong(CursorWindow.java:511)
    12-01 19:30:20.123 17358-17358/com.simonm.bigdaycountdown W/System.err:     at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
    12-01 19:30:20.123 17358-17358/com.simonm.bigdaycountdown W/System.err:     at com.orm.SugarRecord.inflate(SugarRecord.java:296)
    12-01 19:30:20.123 17358-17358/com.simonm.bigdaycountdown W/System.err:     at com.orm.SugarRecord.find(SugarRecord.java:197)
    12-01 19:30:20.123 17358-17358/com.simonm.bigdaycountdown W/System.err:     at com.orm.SugarRecord.listAll(SugarRecord.java:94)
    12-01 19:30:20.123 17358-17358/com.simonm.bigdaycountdown W/System.err:     at com.simonm.bigdaycountdown.MainActivity.initVars(MainActivity.java:165)
    12-01 19:30:20.123 17358-17358/com.simonm.bigdaycountdown W/System.err:     at com.simonm.bigdaycountdown.MainActivity.onCreate(MainActivity.java:124)
    12-01 19:30:20.123 17358-17358/com.simonm.bigdaycountdown W/System.err:     at android.app.Activity.performCreate(Activity.java:5976)
    12-01 19:30:20.123 17358-17358/com.simonm.bigdaycountdown W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
    12-01 19:30:20.123 17358-17358/com.simonm.bigdaycountdown W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2297)
    12-01 19:30:20.123 17358-17358/com.simonm.bigdaycountdown W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404)
    12-01 19:30:20.123 17358-17358/com.simonm.bigdaycountdown W/System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:145)
    12-01 19:30:20.123 17358-17358/com.simonm.bigdaycountdown W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1323)
    12-01 19:30:20.124 17358-17358/com.simonm.bigdaycountdown W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
    12-01 19:30:20.124 17358-17358/com.simonm.bigdaycountdown W/System.err:     at android.os.Looper.loop(Looper.java:135)
    12-01 19:30:20.124 17358-17358/com.simonm.bigdaycountdown W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5319)
    12-01 19:30:20.124 17358-17358/com.simonm.bigdaycountdown W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
    12-01 19:30:20.124 17358-17358/com.simonm.bigdaycountdown W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
    12-01 19:30:20.124 17358-17358/com.simonm.bigdaycountdown W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
    12-01 19:30:20.124 17358-17358/com.simonm.bigdaycountdown W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

  

Do you know why? It worked while using the 1.3 version :S 
Like I said it happens whenever I use 

    TrackedEvent.listAll(TrackedEvent.class) 

or 

    TrackedEvent.findById(TrackedEvent.class, Long.valueOf(1))

Is this no longer the correct way to retrieve saved items or?

Thanks alot for helping me out :)

**Comment by rezanahardani** [comment]
**_here is resolved...
https://stackoverflow.com/a/44619474/7577642_**
