### ISSUE TITLE
@Table annotation not working in 1.4

### ISSUE THREAD

**Issue by mesterj** [satyan/sugar#463]
Hello

I tried my entities with @Table (com.orm.dsl.Table) annotation, but when I use this I can't get SugarRecord methods when I call entity object. With extends SugarRecord everything is good.

Will you fix it, or when I use @Table I need use SugarORM in a different way, which is recommended in next version? 

Thank you, for fast response.

**Comment by sibeliusseraphini** [comment]
@mesterj if you use @Table annotation, your model will not have SugarRecord methods, you need to use the static methods of SugarRecord instead

```
@Table
class SimpleModel {
    private Long id;

    public SimpleModel() {}

    public Long getId() { return id; }
}

SimpleModel model = new SimpleModel();
SugarRecord.save(model);
SugarRecord.count(SimpleModel.class)
```

**Comment by mesterj** [comment]
Which of them recommended? Annotation or extending SugarRecord?

**Comment by sibeliusseraphini** [comment]
It does not matter, it is up to you

**Comment by mesterj** [comment]
Thank you. I think I will extending SugarRecord...
