### ISSUE TITLE
When SugarOrm db's created

### ISSUE THREAD

**Issue by mesterj** [satyan/sugar#465]
Hello

I want fill some of my database from rest service after application first start. I see in the log , I trying acces rest service before the sugarorm database created. How can I force database creating? 
I use 1.4.

**Comment by sibeliusseraphini** [comment]
the database will create in the first data insert

**Comment by mesterj** [comment]
Hmmm... I see the tables created after Activity onCreate finished.
Now I created a workaround . I am downloading rest data in a fragment onActivityCreated() method and looks like correct.

**Comment by mesterj** [comment]
Not just the two tables created what I want to fill , all tables created.
