### ISSUE TITLE
Many-to-One relation

### ISSUE THREAD

**Issue by MBehtemam** [satyan/sugar#466]
hi , how to implement many to one ? for example between book and author can i use something like this : 

     class Book {
     }

    class Author{
       .......
      List<Book> books;
    }

**Comment by LarryLGHao** [comment]
I have the same question~

**Comment by sibeliusseraphini** [comment]
You can add a Author to a Book class, and use a method to retrieve all the Books of an Author
```
class Book {
    Author author;
}

class Author {
    List<Book> getBooks() {
         return Book.find(Book.class, "author = ?", new String{author.getId()})
    }
}
```

We still do not support List<Book> books syntax, you can provide a PR to handle this if you want to

**Comment by LarryLGHao** [comment]
@sibeliusseraphini 
1 save Author and Book by ourself manual? save Book must before save Author?
2 I add Author in the Book as your doc,but look into the db file, the column author is null,why?
3 "author.getId()",how to get  Object "author"?use "this" replace?

**Comment by sibeliusseraphini** [comment]
@LarryLGHao , I've updated my comment above, it was wrong.

- First, save Author,
- Assign author to Book,
- Save book

Then you will have a Book with a foreign key to Author, however we still do not apply foreign constraint yet (https://www.sqlite.org/foreignkeys.html)

You can check your database structure using this steps:
- adb shell
- run-as com.example (your package)
- cat /data/database.db > /sdcard/database.db
- adb pull /sdcard/database.db .

then you can use a tool like [sqlitebrowser](https://github.com/sqlitebrowser/sqlitebrowser)

**Comment by LarryLGHao** [comment]
@sibeliusseraphini Thanks a lot~

**Comment by sibeliusseraphini** [comment]
You're welcome
