### ISSUE TITLE
getCount method to check existing column or record table

### ISSUE THREAD

**Issue by isdzulqor** [satyan/sugar#468]
I'd like to get a value from a table. If the column does not contain any value, then I am going to insert one. So I need getCount in my case. 
My question is how to use getCount in this library, could you give me sample code, please? And where I can get the .db file to see my record table

**Comment by sibeliusseraphini** [comment]
@isdzulqor you can use method **count** of SugarRecord

**Comment by sibeliusseraphini** [comment]
To get the database from your mobile phone you can something like this:

```
adb shell
run-as com.example
cat /databases/db.name > /sdcard/db.name
adb pull /sdcard/db.name .
```

**Comment by isdzulqor** [comment]
first, you dont write <SimpleModel> after extends SugarRecord.. Is it allowed?
secondly, I dont use linux I am using window... so 
adb shell
run-as com.example
cat /databases/db.name > /sdcard/db.name
adb pull /sdcard/db.name .

it's not working for me

**Comment by sibeliusseraphini** [comment]
"first, you dont write after extends SugarRecord.. Is it allowed?" - I didn't understand that, sorry.

about it is not working on windows, you should configure your system to allow access adb from your command line [maybe this help](https://www.google.com.br/search?q=configure+adb+window&oq=configure+adb+window&aqs=chrome..69i57.3630j0j7&sourceid=chrome&es_sm=91&ie=UTF-8)

**Comment by isdzulqor** [comment]
public class StatusLogin extends SugarRecord<StatusLogin> {
    String email_user;
    Boolean status;

    public StatusLogin(String email_user, Boolean status) {
        this.email_user = email_user;
        this.status = status;
    }

    // Default constructor is necessary for SugarRecord
    public StatusLogin() {
    }
}

I initialize my db like above. So I need <StatusLogin> in my class. and you wrote above without <SimlpleModel>.

**Comment by isdzulqor** [comment]
public class StatusLogin extends SugarRecord<StatusLogin> {
    String email_user;
    Boolean status;

    public StatusLogin(String email_user, Boolean status) {
        this.email_user = email_user;
        this.status = status;
    }

    // Default constructor is necessary for SugarRecord
    public StatusLogin() {
    }
}



I need <StatusLogin> in my class above. and you wrote without <SimpleModel> in your class.

**Comment by isdzulqor** [comment]
![capture](https://cloud.githubusercontent.com/assets/12388558/11767200/73106e5c-a1d8-11e5-99a3-f453629bdebf.PNG)
![capture2](https://cloud.githubusercontent.com/assets/12388558/11767201/79107d7e-a1d8-11e5-9fd2-8e77b5c698d2.PNG)
It's not working. It needs two or three parameters.

**Comment by sibeliusseraphini** [comment]
use version 1.4 or master version, this is fixed there

The readme has some examples of the latest version, until I updated the documentation
