### ISSUE TITLE
Some tables not generated

### ISSUE THREAD

**Issue by heroic** [satyan/sugar#469]
Weirdly, one of my app works fine, but in the other, out of 7 tables, only 5 are being generated. Also, if I am not wrong, tables should be generated at app launch, however, they seem to be created only after the onCreate of launcher activity.

The error I am getting is:

    android.database.sqlite.SQLiteException: no such table: DISH (code 1): , while compiling: SELECT * FROM DISH

I am currently on version 1.4. The other app is on version 1.3.

This is the model class:

```
public class Dish extends SugarRecord {
    public Integer quantity;
    public Item item;
    public Integer complete;
    public Integer assigned;
    public Long remoteId;
    public Order order;

    public Dish(){
    }

    public Dish(Long remoteId, Item item, Integer quantity, Integer assigned, Integer complete, Order order){
        this.remoteId = remoteId;
        this.item = item;
        this.quantity = quantity;
        this.assigned = assigned;
        this.complete = complete;
        this.order = order;
    }
}
```

**Comment by sibeliusseraphini** [comment]
@heroic could you please debug the method **getDomainClasses** in **ReflectionUtil** please, to check what is going on in your code.

**Comment by heroic** [comment]
So it turns out that since one of my relations is Order, and since Sqlite is refusing to create Order, this table wasn't formed. However, Sugar 1.4 didn't report an error for this. 1.3 did!

**Comment by sibeliusseraphini** [comment]
1.4 fixed your problem?

**Comment by heroic** [comment]
Nope. 1.4 didn't report the problem. 1.3 only reported the problem. I had to rename the table to get the issue to go away.

**Comment by sibeliusseraphini** [comment]
Why is Order table not being generated?

**Comment by heroic** [comment]
I am not sure! I am guessing that sqlite treats "order" as a keyword?

**Comment by sibeliusseraphini** [comment]
related #416

**Comment by kmbuthia** [comment]
I had the same problem where some tables were not being created. After updating sugar to 1.5 this solved it. I suspect the issue was with projects that have multidexing enabled because 1.5 changelog points out a fix for this.
