### ISSUE TITLE
no such  column

### ISSUE THREAD

**Issue by mesterj** [satyan/sugar#471]
I have a table

class Partner extends SugarRecord

@Unique
String partnerKod;

When I want to search for partnerKod like this query

String kod = "STGH";
Partner.find(Partner.class, "partnerKod = ?',kod)
I have got an error: SQLiteLog: no such column

It is 1.4

**Comment by sibeliusseraphini** [comment]
@mesterj try to use NamingHelper.toSQLName or NamingHelper.toSQLNameDefault in your Field, to check database name of the column

**Comment by maykonmeier** [comment]
Is not your column named "partner_kod" ?

I was having the same issue and when I changed to snake_case it works for me.
I hope to help you.

**Comment by JonatanSalas** [comment]
@mesterj  using what @sibeliusseraphini recommends to you solves your problem! I will close this issue. If you have another problem related to this, please open it again or post a new issue.

**Comment by mesterj** [comment]
Thank you. I solved.
