### ISSUE TITLE
Saving and retrieve image using Sugar. Need proper way. Please help ASAP

### ISSUE THREAD

**Issue by ADAnup** [satyan/sugar#474]
Can you please provide proper way to save and retrieve image using this library.
I'm using Blob object for image. First taking image from one URL as a bitmap and then converting it to Blob then storing it.
At the time of storing it is getting stored, but when I retrieve it I'm getting it null.

Please help ASAP.
1.Model for Event
![untitled](https://cloud.githubusercontent.com/assets/16332676/11864609/21679bfe-a4c4-11e5-8111-0ad3440ee58f.png)
2.Getting image from url, and then saving in db.
![untitled1](https://cloud.githubusercontent.com/assets/16332676/11864610/217a2922-a4c4-11e5-8642-ed3ef8f4f0e6.png)
3.While accessing it it is returnign null.
![untitled2](https://cloud.githubusercontent.com/assets/16332676/11864611/21811caa-a4c4-11e5-9f1f-8778b7236f10.png)

**Comment by sibeliusseraphini** [comment]
check it out #446 and http://stackoverflow.com/questions/26783143/error-while-trying-save-and-retrieve-images-into-database-in-android/26797130#26797130
