### ISSUE TITLE
SugarContext has not been initialized properly

### ISSUE THREAD

**Issue by LarryLGHao** [satyan/sugar#477]
Sometimes,it will be happened~

**Comment by sachinletsgo** [comment]
its show me the same error.
then i come to know that i have to set the application name "com.orm.SugarApp"?
why i cant use my application name in manifest file

**Comment by kifki** [comment]
I had the same problem, and I forgot to add `android:name="com.orm.SugarApp"` in the manifest application tag.
But it's clearly stated in the docs, so I don't think it's a bug.

**Comment by alemdg** [comment]
still not documented

**Comment by alemdg** [comment]
you can use you application name, just extend your Application class from SugarApp

public class ThisApplication extends SugarApp {

**Comment by Midhilaj** [comment]
i am sorry , sugar lib is not working for me
