### ISSUE TITLE
Not able to create Table

### ISSUE THREAD

**Issue by Fshamri** [satyan/sugar#478]
I have the following Observer to save feeds to database:
````
 public Observable<Boolean> saveFeeds(List<FeedEntity> feedEntity) {
        if (feedEntity != null) {
            return Observable.create(new Observable.OnSubscribe<Boolean>() {
                @Override
                public void call(Subscriber<? super Boolean> subscriber) {
                    try {
                    for (FeedEntity feeds : feedEntity){
                        feeds.save();
                    }
                    subscriber.onNext(true);
                    subscriber.onCompleted();
                }  catch (Exception exception) {
                    subscriber.onError(exception);
                }
                }
            });

            } else
        return Observable.empty();
    }
````
but i am getting the following error:

````android.database.sqlite.SQLiteException: no such table: FEED_ENTITY (code 1): , while compiling: INSERT OR REPLACE  INTO FEED_ENTITY(ID,CACHED,M_ITEMSTOTAL,M_LOGO_URL,M_FEED_ID,IS_SUBSCRIBED,M_FEED_TITLE) VALUES (?,?,?,?,?,?,?)````

**Comment by sibeliusseraphini** [comment]
Could you please check the tables created by Sugar, using this https://gist.github.com/sibeliusseraphini/b060c415604c52c2a94e and sqlitebrowser

**Comment by dnalves** [comment]
@Fshamri Is your app using multidex or something like that?

I had a similar problem where an app was using multidex, then I removed the multidex and I was getting a error because Sugar couldn't find the secondary dex file.

**Comment by XxPixX** [comment]
@dnalves 
So did you just reenable multidex and it worked fine?

**Comment by JonatanSalas** [comment]
Now in v1.5 of Sugar multidex is supported.
