### ISSUE TITLE
SUGAR reformats entity properties

### ISSUE THREAD

**Issue by QuickBrownFoxy** [satyan/sugar#48]
public class Book extends SugarRecord<Book> {
  String ISBN_ID;
  String title_string;
}
becomes below columns
ISBNID
TITLESTRING

it shouldn't touch property names should it?

**Comment by whoshuu** [comment]
The right approach is probably to beef up the query builder modules, with a specific interface for userland names that'll automatically do the name conversions under the hood.

**Comment by sibeliusseraphini** [comment]
now we have @Column annotation that enable us to use any name for a specific column
