### ISSUE TITLE
How can i prevent duplication of rows ??

### ISSUE THREAD

**Issue by iAviatorJose** [satyan/sugar#480]

**Comment by sibeliusseraphini** [comment]
Could you please give more info?

**Comment by iAviatorJose** [comment]
I Get an Array Of Objects from API. And i store them in Database using SugarDB.

PROBLEM:
Every time hit the get API then i get a JSON Array which has objects that are already in my DB and some are new. So when i save this new array fetched duplicate Rows are created.

Is there a built in functionality in SugarDB. that will prevent the duplication of Rows.

**Comment by sibeliusseraphini** [comment]
You can use a @Unique constraint in a column of your table

**Comment by iAviatorJose** [comment]
Ok @sibeliusseraphini  will try this and get back to you!!!

**Comment by jonisaa** [comment]
@iAviatorJose did you solve your problem?

**Comment by JonatanSalas** [comment]
@iAviatorJose I will close it because in fact the use of @Unique annotation solves your trouble. If you need something else please re open it. Or create a new issue!
