### ISSUE TITLE
Dependency Error with com.google.common.collect.MapMaker. 

### ISSUE THREAD

**Issue by hammoudeh** [satyan/sugar#483]
Hi, 

I'm trying to use the new version 1.4, but unfortunately it is dependent in  com.google.common.collect.MapMaker. 
In realty I'm using it in virtual device which is pure android OS. 

So what is the solution to not depends my work in com.google.common.collect.MapMaker. 

Below the error log.  
`
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/collect/MapMaker;
                                                                                  at com.orm.SugarContext.<init>(SugarContext.java:19)
                                                                                  at com.orm.SugarContext.init(SugarContext.java:30) 
`

**Comment by kmno** [comment]
i have same issue...

**Comment by sampohaavisto** [comment]
Likewise

**Comment by sibeliusseraphini** [comment]
the master version removed the MapMaker dependency, give it a try

**Comment by larick** [comment]
Hi, could you update the jar library 1.4 in the download section ? I cannot use the "graddle way" to use it in my developement.
Thanks in advance

**Comment by sibeliusseraphini** [comment]
@satyan will release 1.5 soon, maybe this week
