### ISSUE TITLE
Problem with column named 'class'

### ISSUE THREAD

**Issue by StevenWung** [satyan/sugar#489]
table structure is fixed, some of the columns were named with java keywords, is there any way to move forward without changing the column names?
Thanks

**Comment by sibeliusseraphini** [comment]
You can define these column names like _String and use the annotation @Column to define the name in the database

```
public class MyRecord extends SugarRecord {
    MyRecord() {}

    @Column("String")
    String _String;
}
```

But, I prefer to not use reserved words of Java neither of Sqlite

related to #416

**Comment by StevenWung** [comment]
@sibeliusseraphini thanks a lot
