### ISSUE TITLE
Domain objects using both Gson and SugarRecord, clashing over field name "id" in Retrofit call

### ISSUE THREAD

**Issue by rachellejane** [satyan/sugar#491]
Hey there,

I'm wondering if there's a workaround for this little issue I've encountered in a class called User, which I deserialize from a JSON object using Gson, annotating like so:
```
public class User extends SugarRecord{
    private Long id; //used by Sugar

    @SerializeName("id") //used by Gson -- I can't change this field name
    private String userId;
}
```

Even though the variables are called totally different things and are different types in the definition of User, this addition of the Long id field with Sugar is causing Retrofit to throw an error, which says "com.package.User declares multiple JSON fields named id".

Is there any possible workaround for this? Let me know if there's anything else you might need to see, and thanks so much for any help you can offer!

**Comment by rachellejane** [comment]
Ah, and I found a workaround. If you run into this, it's just a matter of adding something like this to your deserialize method: 
```
user.getAsJsonObject().getAsJsonPrimitive("id").toString().replace("\"id\"", "\"user_id\"");
```
And then changing the annotation accordingly in your domain class.

**Comment by MangeshKadam** [comment]
@rachellejane - could you please details about your solution? I am also facing exact the same problem. If you could help me with posting piece of code in detail that will be helpful.

**Comment by JonatanSalas** [comment]
What you have to do is not to extend from base class SugarRecord. Instead you should use the @Table annotation which gives to you the ability to declare by yourself a private Long id. 

When declaring the private Long id, you have to use the keyword transient like this: 

private transient Long id;

That mean that your id field won't be serialized NEVER! 

Hope this helps!

**Comment by MangeshKadam** [comment]
Thanks @JonatanSalas  - you saved  a day. Works perfectly.

**Comment by JonatanSalas** [comment]
@MangeshKadam great! :D

**Comment by rachellejane** [comment]
I actually fixed my issue not by using transient, because I did need to
keep the ID on my objects. What I did, in the deserialize method (in class
implementing JsonDeserializer<ObjectType>), was remove the "id" field on
the JsonObject so that Sugar could take it, but then re-added the data,
renamed as "item_id".

      JsonObject item =
responseArray.get(i).getAsJsonObject().getAsJsonObject("item");
            int itemId = item.get("id").getAsInt();
            item.remove("id");
            item.addProperty("item_id", itemId);

Sorry for dumping code in there without formatting, but it's a short
snippet.

**Comment by JonatanSalas** [comment]
@rachellejane another thing that can be done when you have your model class extend from SugarRecord it's to create an exclusion strategy for Gson.

```java 
public class SugarExclusionStrategy implements ExclusionStrategy {
    private Class<?> clazz;

    public SugarExclusionStrategy(Class<?> clazzToExclude) {
        this.clazz = clazzToExclude;
    }

    @Override
    public boolean shouldSkipClass(Class<?> clazz) {
        return false;
    }

    @Override
    public boolean shouldSkipField(FieldAttributes f) {
        return f.getDeclaringClass().equals(clazz) && f.getName().equals("id");
    }
}
```
And then add it when you create your Retrofit object like this:

```java
final SugarExclusionStrategy strategy = new SugarExclusionStrategy(SugarRecord.class);

final Gson gson = new GsonBuilder()
                .addDeserializationExclusionStrategy(strategy)
                .addSerializationExclusionStrategy(strategy)
                .create();

final Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(baseUrl)
                .addConverterFactory(GsonConverterFactory.create(gson))
                .client(buildClient())
                .build();

```

**Comment by flogvit** [comment]
I hit the same problem with the api returning id, and I wanted to use retrofit and Sugar. And Since I didn't find any working examples where I actually was able to also store it, I worked out a solution.

```java
Gson gson = new GsonBuilder()
                .setFieldNamingStrategy(new MySugarormIdRenamingStrategy())
                .create();

class MySugarormIdRenamingStrategy implements FieldNamingStrategy
    {
        public String translateName(Field field)
        {

            if (field.getName().equals("id") &&
                !field.getDeclaringClass().getName().equals("com.orm.SugarRecord"))
            {
                return "apiId";
            }
            return field.getName();
        }
    }
```

This way all my retrofit get calls return apiId as name instead of id. You can do the same the other way. And you can extend SugarRecord.
