### ISSUE TITLE
Orderby descending

### ISSUE THREAD

**Issue by CreaRo** [satyan/sugar#493]
Is there a way to order by descending?
```
SugarRecord latestRecord = Select.from(EmailMessage.class).orderBy(StringUtil.toSQLName("contentID")).first();
```
gives me the first record, but I want the last. What query should I use for that?

**Comment by sibeliusseraphini** [comment]
try to use

```
orderBy(StringUtil.toSQLName("contentID") + " DESC")
```

I will accept a PR to improve this hack solution

based on this [answer](http://stackoverflow.com/questions/8948435/how-do-i-order-my-sqlite-database-in-descending-order-for-an-android-app)

**Comment by CreaRo** [comment]
Alright.
