### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by fg607** [satyan/sugar#494]
Use the static method 'findById'  throws  the "java.lang.ExceptionInInitializerError"  and "java.lang.Class.classForName(Native Method)" exception ,when run in jelly bean.
But it's fine in lollipop.

hopes to resovle, Thanks!

**Comment by koolll** [comment]
any solution?

**Comment by karimi12** [comment]
my friend please see this links 
http://stackoverflow.com/questions/3375810/exception-in-initializer-error
i have this problem too


i use Singleton  pattern 

i change 

public class MedicineListSingleton {
    private static MedicineListSingleton  ourInstance = new MedicineListSingleton();

..........
} 

to


public class MedicineListSingleton {
    private static MedicineListSingleton ourInstance;

static {
    ourInstance = new MedicineListSingleton();
}
..........
}

**Comment by fg607** [comment]
@karimi12  Thanks!
