### ISSUE TITLE
slow performance with listAll()

### ISSUE THREAD

**Issue by matfur92** [satyan/sugar#496]
Hi,
I've noticed that listAll() method is too slow in my opinion.
My code :
```java
List<Domanda> arrDomande = Domanda.listAll(Domanda.class);
```
produce : 
```
SQLiteQuery: SELECT * FROM DOMANDA
```
and 318 (items in table DOMANDA) of : 
```
SQLiteQuery: SELECT * FROM DOMANDA WHERE id=? LIMIT 1
```

There is a method to improve performance and run only ```SELECT * FROM DOMANDA``` to have a list of all objects in ```DOMANDA```?

Thanks a lot in advance

**Comment by sibeliusseraphini** [comment]
I suggest to use a Iterator based method instead, this will make the list evaluation lazy

**Comment by matfur92** [comment]
Hi,
I used this code:
```java 
        Iterator<Domanda> cursor = SugarRecord.findAll(Domanda.class);
        while (cursor.hasNext()){
            Domanda domanda = cursor.next();
            obj+=domanda.count;
        }
```
but I have the same time to read 318 elements. It's too 670ms for me, did you have any other idea to resolve this?

**Comment by sibeliusseraphini** [comment]
http://stackoverflow.com/questions/18081581/how-to-make-sqlite-select-query-faster
http://stackoverflow.com/questions/3632827/is-there-any-efficient-way-to-make-android-database-query-faster
http://stackoverflow.com/questions/16125919/android-sqlite-get-all-data-from-cursor-fast

You can use an AsyncTask to not block the UI thread

You can also use an aggregation for your type of query

**Comment by mikemike396** [comment]
Using the AsyncTask works pretty good. Atleast takes the lag out of the UI if transition to new activity

    public class QueryDataBase extends AsyncTask<String, Void, Void> {
        private Exception exception;
        protected Void doInBackground(String... urls) {
            try {
                objectList = Object(Object.class, "is_read = ?", "1");
            } catch (Exception e) {
                this.exception = e;
                return null;
            }
            return null;
        }

        protected void onPostExecute(Void feed) {
            if (exception == null)
            {
               Home_adapter adapter = new Home_adapter(getActivity(), objectList);
               listView.setAdapter(adapter);
            }
        }
    }
