### ISSUE TITLE
Annotations lack the @Target annotation.

### ISSUE THREAD

**Issue by tevjef** [satyan/sugar#497]
The [Target](https://docs.oracle.com/javase/7/docs/api/java/lang/annotation/Target.html) annotation is used to compile-time checking. The Kotlin compiler specifically uses annotation to provide interoperability between it and Java.
```Kotlin
class AccountModel {
    @Unique
    var accountId: Long = 0
    var email: String
}
```
The Kotlin compiler does not bind the annotation to the field if the `Target` annotation is not declared.

**Comment by sibeliusseraphini** [comment]
fixed with #498
