### ISSUE TITLE
No such table error

### ISSUE THREAD

**Issue by amaurymuro** [satyan/sugar#50]
Hi, I am new with Sugar. I have a simple android project with a single record named "Abonado". I have followed the wiki' steps but when I ran the project and I had the error: "android.database.sqlite.SQLiteException: no such table: ABONADO (code 1): , while compiling: SELECT \* FROM ABONADO". Then I looked the db file created  and it’s true, the table ABONADO does not exit. 
Then I looked the master project SugarActivity and it  does not  make the tables either and I also had another similar error: "android.database.sqlite.SQLiteException: no such table: TEXT_NOTE (code 1): , while compiling: DELETE FROM TEXT_NOTE". 
Have you experienced this issue before?Could you please help me? Thanks in advanced. Respectfully.  
ohh I am using android 4.2

**Comment by nesasivan** [comment]
where we need to use the constructor

**Comment by Raguking** [comment]
where we need to use the constructor??

**Comment by mouhsinelonly** [comment]
this should really be fixed +1

**Comment by divyanshunegi** [comment]
Why is this library so buggy ? Satyan please write some more documentation in the website, in example you have created class without context and in another database creation method there you are passing context, please fix these little issues. BTW , it crashes in my device and also shows a white screen when app starts for 100- 200 ms.

**Comment by ksrpraneeth** [comment]
I was having the same issue i solved it by adding 
1. public constructor (Public constructor is must.)
2. Increasing the VERSION in manifest file to '20'(can be anything)

**Comment by HosseinKurd** [comment]
Is it possible to Add new table in new version released without removing older version ??

**Comment by 3ct0m0rph** [comment]
Solved by changing the database name:
<meta-data android:name="DATABASE" android:value="ae_qt_01.db" />
to:
<meta-data android:name="DATABASE" android:value="ae01.db" />

**Comment by HosseinKurd** [comment]
@3ct0m0rph  Change DB Name ? Lose Previous Tables And Rows

**Comment by 3ct0m0rph** [comment]
@HosseinKurd To get it working initially.

**Comment by HosseinKurd** [comment]
@3ct0m0rph So How to add new table to DB witout create  new DB file ?

**Comment by sarathvallathol** [comment]
I am using Gradle worked for firs time but next day tried its crashing saying"SQLiteException: no such table _sugar". then after reading all these changed my version from 3 to 5 worked. i don't know why. so i need to change y version daily ? please help

**Comment by sarathvallathol** [comment]
And also I cant down grade the version to below 3

**Comment by johnelevado** [comment]
Like the others, i fixed mine with an empty constructor.  Just create it in your SugarRecord sub class

**Comment by leohgz** [comment]
Mine works putting the: 
       <meta-data android:name="DATABASE" android:value="sugar.db" />
        <meta-data android:name="VERSION" android:value="2" />
        <meta-data android:name="QUERY_LOG" android:value="true" />
        <meta-data android:name="DOMAIN_PACKAGE_NAME" android:value="own.leo.libreria.sqlite" />
outside the <application>. Thats weird. The other thing that works for me. Leaving to ="2" the version of database, as the website suggests.

**Comment by mversteeg3** [comment]
Make sure all of your Sugarized classes are located within the same package.  I fixed my issue by moving them to a data.sugar package and changing the DOMAIN_PACKAGE_NAME tag in the manifest to be the fully qualified path of that package

**Comment by krazykira** [comment]
I am getting the *same exception* and none of the above solutions worked for me
```
10-09 11:30:21.511 4326-4831/com.example.app E/SQLiteLog: (10) Failed to do file read, got: 0, amt: 100, last Errno: 2
10-09 11:30:26.506 4326-4831/com.example.app E/SQLiteLog: (1) no such table: IMAGE
10-09 11:30:26.516 4326-4831/com.example.app E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
10-09 11:30:26.516 4326-4831/com.example.app E/AndroidRuntime: java.lang.RuntimeException: An error occured while executing doInBackground()
10-09 11:30:26.516 4326-4831/com.example.app E/AndroidRuntime:     at android.os.AsyncTask$3.done(AsyncTask.java:299)
10-09 11:30:26.516 4326-4831/com.example.app E/AndroidRuntime:     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
10-09 11:30:26.516 4326-4831/com.example.app E/AndroidRuntime:     at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
10-09 11:30:26.516 4326-4831/com.example.app E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:239)
10-09 11:30:26.516 4326-4831/com.example.app E/AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
10-09 11:30:26.516 4326-4831/com.example.app E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
10-09 11:30:26.516 4326-4831/com.example.app E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
10-09 11:30:26.516 4326-4831/com.example.app E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:838)
10-09 11:30:26.516 4326-4831/com.example.app E/AndroidRuntime:  Caused by: android.database.sqlite.SQLiteException: no such table: IMAGE (code 1): , while compiling: SELECT * FROM IMAGE
10-09 11:30:26.516 4326-4831/com.example.app E/AndroidRuntime:     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
10-09 11:30:26.516 4326-4831/com.example.app E/AndroidRuntime:     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:886)
10-09 11:30:26.516 4326-4831/com.example.app E/AndroidRuntime:     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:497)
10-09 11:30:26.516 4326-4831/com.example.app E/AndroidRuntime:     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
10-09 11:30:26.516 4326-4831/com.example.app E/AndroidRuntime:     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
10-09 11:30:26.516 4326-4831/com.example.app E/AndroidRuntime:     at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
10-09 11:30:26.516 4326-4831/com.example.app E/AndroidRuntime:     at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
10-09 11:30:26.516 4326-4831/com.example.app E/AndroidRuntime:     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
10-09 11:30:26.516 4326-4831/com.example.app E/AndroidRuntime:     at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1161)
10-09 11:30:26.516 4326-4831/com.example.app E/AndroidRuntime:     at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1032)
10-09 11:30:26.516 4326-4831/com.example.app E/AndroidRuntime:     at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1238)
```

This happens when i add [GPU image Android Library](https://github.com/CyberAgent/android-gpuimage). I am using Gradle and Android Studio. Also once i remove GPU image this issue is solved. So i don't know whats the conflict

**Comment by farmazon3000** [comment]
I have the same issue.

@satyan "But we still need the default constructor (i.e.) an empty constructor. In absence of which, the tables fail to get created.." why? Doesn't java create one by default?

**Comment by ontur00** [comment]
I have a problem when I delete the application file database. Then there is an error android.database.sqlite.SQLiteException: no such table Province, but when I push a database to emulator of all CRUD operations are performed.

Link how look manifest
http://wklej.org/hash/d6732855df6/

**Comment by sibeliusseraphini** [comment]
@ontur00 which version of sugar are you using? why are you deleting the database file?

**Comment by ontur00** [comment]
compile 'com.github.satyan:sugar:1.3'  
Beacuse i trying method which check if( database != exist )  then i want create .db file

**Comment by sibeliusseraphini** [comment]
try to use 1.4 or master version

**Comment by ontur00** [comment]
I need only change 1.3 to 1.4   and   extends SugarRecord    - without <T>

**Comment by ontur00** [comment]
I have problem manifest 
<application   
   android:allowBackup="true" 
   android:icon="@drawable/ic_launcher"
   android:theme="@style/AppTheme">

Error:(16, 23) No resource found that matches the given name (at 'icon' with value '@drawable/ic_launcher').

**Comment by sibeliusseraphini** [comment]
do you have a drawable ic_launcher?

**Comment by ontur00** [comment]
I try at new TestProject. 
I add 
    compile 'com.github.satyan:sugar:1.4'    - sync project   - to gradle
    new class at package where is my activity (com.example.user.testsugar1_4 )
    in my main activity     Book book = new Book("isbn123", "Title here", "2nd edition");
    Book.save();   and :

Exception :
Caused by: java.lang.NullPointerException: SugarContext has not been initialized properly. Call SugarContext.init(Context) in your Application.onCreate() method and SugarContext.terminate() in your Application.onTerminate() method.

I use this tutoriall - https://android-arsenal.com/details/1/337


http://pastebin.com/iB1J1KRj   - main activity
http://pastebin.com/dgdy7eiX   - manifest
http://pastebin.com/jESs2KjQ   - gradle

**Comment by sibeliusseraphini** [comment]
```
public class TestProjectApp extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        SugarContext.init(this);
    }

    @Override
    public void onTerminate() {
        super.onTerminate();
        SugarContext.terminate();
    }

}
```

**Comment by ontur00** [comment]
I fixed I use a 1.3, I had a mistake in the manifesto

<meta-data android: name = "DOMAIN_PACKAGE_NAME" android: value = "com.example.akilaptop.wrongPackage.Model" />

Advice to other check if you have a well-configured manifest

**Comment by RodryVazquez** [comment]
I just to have the same problem, I fixed by adding an empty contructor, and compile with  the 1.3 Sugar orm version and rainstalled the app, and before  new testing run cleanner in device and clear cache.
my ManifestFile looks like : 

 <meta-data android:name="DATABASE" android:value="MyDb.db" />
    <meta-data android:name="VERSION" android:value="1" />
    <meta-data android:name="QUERY_LOG" android:value="true" />
    <meta-data android:name="DOMAIN_PACKAGE_NAME" android:value="com.example.DemoApp.Models" />

**Comment by krazykira** [comment]
For me this error occured because i had `Multidex` enabled and i was using a lot of `libraries` around 20 of them and it was a very big project with a lot of classes. I debugged and went through the source code and i confirmed it there that the classes that `extended sugar record` were never found so in the end i `added my classes explicitly` into the source code in order to get my project to work.

I don't know if this would help other but it certainly something that the devs should look into. Try adding the project as library project and try debugging the source code and you will find the same issue.

**Comment by miladna7** [comment]
i did this thing:
change DOMAIN_PACKAGE_NAME = not working
change VERSION = not working
change DATABASE = working
so i think change the db name may help u in this case.

**Comment by Gujarats** [comment]
Yes I was having the same issue, @miladna7 Thanks man your suggestion works.
But I wonder why it can't use the same database?

**Comment by sibeliusseraphini** [comment]
it is fixed on master and on 1.5 version

**Comment by aubertdavy** [comment]
Hi, no changment, i've got the same error..

**Comment by Gujarats** [comment]
@aubertdavy try to change the name of your database or update to the version 1.5

**Comment by aubertdavy** [comment]
@Gujarats yes that's what i did !!
I upgrated to 1.5,  removed my app, changed my db name .. and no changment

**Comment by aubertdavy** [comment]
Ok i solved my problem extending SugarApp and passing application context (and not base context) on create overriding method

**Comment by cdaringe** [comment]
@aubertdavy, can you be more specific?

**Comment by aubertdavy** [comment]
@cdaringe 
Init SugarContext in a derived Application class,  passing application base context solved my problem.

**Comment by aubertdavy** [comment]
public class MySugarApp extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        SugarContext.init(getApplicationContext());
    }
}

**Comment by cdaringe** [comment]
i'm sorry to be a total rookie on this (i _rarely_ code java), but no where in my current app do I use `Application` explicitly (perhaps implicitly?).  Even if so, I'd like to write some unit tests--I'm unsure how'd I'd get the context otherwise if there'd be no `Context` in the test suite.

thanks for the tip.

**Comment by cdaringe** [comment]
nm, @aubertdavy, i did figure out how to do that. still gives the error, though, unforunately

>  Caused by: android.database.sqlite.SQLiteException: no such table: CUSTOMER (code 1): , while compiling: INSERT OR REPLACE  INTO CUSTOMER(EMAIL,ID,NAME) VALUES (?,?,?)

**Comment by RodryVazquez** [comment]
try, reinstall the app in the phone, in some cases its necesary, I never use application context to initialize sugar context in my apps

**Comment by Aiuspaktyn** [comment]
Same problem, fixed using gradle 1.5.0 (before was 2.0.0-beta7)

**Comment by truongvnse03130** [comment]
i have the same problem, but i fixed by:
1. Write a subclass extends Application like this:

public class SugarORMApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        SugarContext.init(this);
    }

    @Override
    public void onTerminate() {
        super.onTerminate();
        SugarContext.terminate();
    }
}
2. Add android:name="com.....SugarORMApplication" (to class above) and is fixed

**Comment by felipebonezi** [comment]
This is not working with GRADLE 2.0.0!!!!!!!

**Comment by firasalkafri** [comment]
@felipebonezi please check #564

**Comment by RodryVazquez** [comment]
yes, disable instant Run in android studio

**Comment by amrishodiq** [comment]
I tried to disable instant run on android studio 2.1.2 but still have no luck.
But actually succeed when using gradle 1.5.0.

classpath 'com.android.tools.build:gradle:1.5.0'

on project's build.gradle.

I hope the patch will be released soon.

**Comment by bishwash72** [comment]
This may help :
correct :         <meta-data android:name="DATABASE" android:value="cal.db" />
Error:         <meta-data android:name="DATABASE" android:value="cal_bi.db" />

**Comment by billgockeler** [comment]
updating build.gradle to 'com.github.satyan:sugar:1.5' fixed it for me

**Comment by cbedoy** [comment]
Not working with kotlin using 

 'com.github.satyan:sugar:1.5'

**Comment by Lim-Jerico11** [comment]
I have a problem  java.lang.NullPointerException: SugarContext has not been initialized properly. Call SugarContext.init(Context) in your Application.onCreate() method and SugarContext.terminate() in your Application.onTerminate() method.
