### ISSUE TITLE
Getting Data in reverse order. Why ???  

### ISSUE THREAD

**Issue by sachinletsgo** [satyan/sugar#503]
Lets suppose i save data  
1
2
3
4
5

But i am receiving the data in reverse order when i use  FindAll()
like 
5
4
3
2
1

Why so ??

how to tackle  it

**Comment by nurolopher** [comment]
Select.from(TestRecord.class).orderBy("id");

**Comment by jonisaa** [comment]
@sachinletsgo have you solved the trouble?
