### ISSUE TITLE
data not saved when app is in background

### ISSUE THREAD

**Issue by danndi** [satyan/sugar#504]
Hello,

I am using Sugar 1.4 and I have a problem that data are not saved in Sugar Object when the app is in background. 

My app is downloading a file. When the download completes, the DownloadCompleteReceiver is called where I want to save a STATE_COMPLETE for this object. The logCat says: DownloadFile saved : 14741. But when I go back to the app, the state is not saved and the DownloadFile has the previous state. It is working without any problem when the app is running in foreground. 

I was testing it on more than 5 devices with different Android versions and the issue is on all of them. Could you please help.

Thank you.

**Comment by sibeliusseraphini** [comment]
@danndi try to use the android studio debugger tools to help you identify in which exactly part does not work, and let me know the problem with the logs

**Comment by danndi** [comment]
Hi,

sorry for not answering earlier. From further research it seems that the problem was in the RecyclerView and its data. There was and old "copy" of the object and when resumed to app, this old copy replaced the record in that was saved by the receiver earlier. 

I think you can close this issue as it is not problem of Sugar ORM.

**Comment by sibeliusseraphini** [comment]
thanks
