### ISSUE TITLE
Cannot instantiate table on application startup

### ISSUE THREAD

**Issue by ErikRehnqvist** [satyan/sugar#506]
Hi,

I have a problem instantiating a table in the onCreate-method of the MainActivity. I am trying to initialize a table called Recipe but I get the following error:

Caused by: android.database.sqlite.SQLiteException: table RECIPE has no column named NAME (code 1): , while compiling: INSERT OR REPLACE  INTO RECIPE(ID,INGREDIENTS,NAME,HOW_TO) VALUES (?,?,?,?)

My call inside of the onCreate method looks like this:

    recipe = new Recipe("Filet mignon", "Beef, potatoes", "Peel the potatoes");
    recipe.save();

My Recipe class looks like this:

    public class Recipe extends SugarRecord {
        String name;
        String ingredients;
        String howTo;
        public Recipe() {
    }

    public Recipe(String name, String ingredients, String howTo) {
        this.name = name;
        this.ingredients = ingredients;
        this.howTo = howTo;

    }

    public String getIngredients() {
        return ingredients;
    }

    public void setIngredients(String ingredients) {
        this.ingredients = ingredients;
    }

    public String getHowTo() {
        return howTo;
    }

    public void setHowTo(String howTo) {
        this.howTo = howTo;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
   
    @Override
    public String toString() {
        return "Recipe{" +
                "name='" + name + '\'' +
                ", ingredients='" + ingredients + '\'' +
                ", howTo='" + howTo + '\'' +
                '}';
        }

    }

I don't know why this doesn't work, because I have an almost identical class and I add objects to it in the same way. The only difference between the two is that the other class' function calls take place in a class called AddInfo, and the one posted here take place in the onCreate method of the MainActivity.

/E

**Comment by sibeliusseraphini** [comment]
have you created the Recipe class after running your code at least once?

I think you should try to update your database version

which Sugar version are you using?

**Comment by ErikRehnqvist** [comment]
Hi,

I'm using Sugar version 1.4. Yeah, I constantly test the code so the Recipe class was created after I made the code work with another table, called Inventory.

By updating the database version, you mean simply changing the 1 in the android manifest to a 2?

**Comment by sibeliusseraphini** [comment]
yeah

**Comment by ErikRehnqvist** [comment]
I tried that, updated it to first 2, then 5 and now 200, but it still doesn't work. It still gives me:

Caused by: android.database.sqlite.SQLiteException: table RECIPE has no column named NAME (code 1): , while compiling: INSERT OR REPLACE  INTO RECIPE(ID,INGREDIENTS,HOW_TO,NAME) VALUES (?,?,?,?)

**Comment by sibeliusseraphini** [comment]
Could you try to get your db files from your android sdcard

You can use this script for that: https://gist.github.com/sibeliusseraphini/b060c415604c52c2a94e

and check whether there is something wrong with it

**Comment by ErikRehnqvist** [comment]
I have found a solution, sort of. If I change the database name, everything works. However, I suspect that this is not the intended way for it to work. But, as a quick fix, it does work.

However, how do I prevent duplication in the process of adding items? Now, I am trying to use the method for an ArrayList, like list.isEmpty(), but it returns true everytime (i.e. that list is empty). Why is that, and is there any other way of not adding duplicates?

**Comment by sibeliusseraphini** [comment]
You could use https://github.com/satyan/sugar#update-entity

It requires you to define the unique field that you want to preserve, so when you use update, it will update the save based on the unique field, instead of creating another item

**Comment by ErikRehnqvist** [comment]
That is not really what I meant. However, I do want to ask you if there is a good way to have a many-to-many relationship with SugarORM?

I have a lot of recipes that have a lot of ingredients, and one recipe have multiple ingredients. The same ingredient could be in multiple recipes, therefore the many-to-many relationship.

Also, if I have a table called "Inventory" and this table consists of Ingriedient objects, how do I extract the Ingredient object attributes? Now, I can have a list of inventory-objects, but I want to have the Ingredients that lie within the Inventory object.

**Comment by sibeliusseraphini** [comment]
In the SQL world you should have another table (RecipeIngredient) that has two foreign keys, one pointing to Recipe Table and another pointing to Ingredient Table, to have a many-to-many relationship

The example below, solve your both problems:

```java
public Inventory extends SugarRecord {
  Inventory() {}

  List<Ingredient> getIngredients() {
    return Ingredient.find(Ingredient.class, "inventory = ?", new String(getId()))
  }
}

public Ingredient extends SugarRecord {
  Inventory inventory;
  Ingredient() {}
}

public Recipe extends SugarRecord {
  Recipe() {}
}

public RecipeIngredient extends SugarRecord {
  Ingredient ingredient;
  Recipe recipe;

  RecipeIngredient() {}
}
```
