### ISSUE TITLE
Compile Binary not working.

### ISSUE THREAD

**Issue by ALJazeeraIDP** [satyan/sugar#509]
If I try to compile the binary using:
compile 'com.github.satyan:sugar:1.3' 

It is failing and giving me following error:
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

But when I download the library and use it as follows:

compile name: 'sugar-1.3' 
It works fine.

Now I want to use latest 1.4 using compile remote library and it is failing.

**Comment by sibeliusseraphini** [comment]
@ALJazeeraIDP are u sure that this is a problem with Sugar?

could you try to use the master version?

**Comment by jonisaa** [comment]
@ALJazeeraIDP Try to do a 
```gradle
gradle clean build 
```
after including sugarORM to your dependencies, then add it and synchronize. Hope this helps!

**Comment by JonatanSalas** [comment]
@ALJazeeraIDP could you solve this? I will close for now the issue. If you can't solve it, please re open it.
