### ISSUE TITLE
"No such Table Exception" with AndroidStudio Preview-Version

### ISSUE THREAD

**Issue by lumueller** [satyan/sugar#510]
Hi, 
I don't know if that's an issue with sugar or the gradle build-tools - but just to inform you:

I am using the Android-Studio-Preview-Version and since v2.0 Preview 6 (with build-tools 2.0.0-alpha5) I can't start my App as I am getting a "No Such Table Exception" at the first call to my database. I am now on Preview 8 with build-tools 2.0.0-alpha8 and it's still not working.

When I switch to Android Studio 1.5. everything works fine. With Preview-Versions prior to 6 also everything was working fine.

Best wishes,
Lukas

**Comment by jonisaa** [comment]
Do you made a refactor of your code?

**Comment by lumueller** [comment]
No. No refactoring, no code changes.
All I did was update android studio from preview 5 to 6 (including gradle). I tried on three different notebooks.

**Comment by jonisaa** [comment]
This is strange. I have worked with all preview versions (now I'm on preview 8), and I don't have any problem. Try to make a gradle clean build from the android studio terminal, if there's a trouble it will print some message to you.

**Comment by vyacheslavk** [comment]
I seems have problems with new feature Instant Run, because I don't had any issues with previous preview versions of android studio, but now i run 2.1 preview 4. To reproduce issue try to completely remove app and make fresh install.

**Comment by firasalkafri** [comment]
Instant Run now works #559
