### ISSUE TITLE
How to use Sugar with SQLCipher?

### ISSUE THREAD

**Issue by jonisaa** [satyan/sugar#512]
I want to encrypt my database using SQLCipher, and I don't know how to achieve this. Is this possible?

**Comment by sibeliusseraphini** [comment]
There is this lib: https://github.com/sqlcipher/android-database-sqlcipher

But I don't know what needs to be done to integrate with Sugar

**Comment by jonisaa** [comment]
In the sugar repository there is a branch called sugar-cipher or something like that. I follow some of the things that says in the README file but it doesn't work. 
To probe if this works I extract the database to SDcard and I attempt to read its content. I can do it with no problem. 
Could you take a look at that branch and help me?

**Comment by sibeliusseraphini** [comment]
There is only few commits in the cypher branch.

You should fork this repository, create a new branch, fetch sugar-cipher branch, merge with your new branch, and reference your repository in your main project , using readme instructions

Something like this:

- fork repo
- git clone jonissa/sugar
- git remote add upstream git@github.com:satyan/sugar.git
- git fetch upstream
- git checkout my-sugar-cipher
- git merge upstream/sugar-cipher

**Comment by jonisaa** [comment]
Okey! Thanks for your help! I will probe it!

**Comment by sibeliusseraphini** [comment]
let me know if you have any trouble
