### ISSUE TITLE
Mutli Dex Support - No Class Found Error

### ISSUE THREAD

**Issue by jd-alexander** [satyan/sugar#515]
I recently upgraded my app to multi dex and now I am getting no class found def errors on Android 4.4 . Is there any way I can fix this?

**Comment by jonisaa** [comment]
Could you show us the stacktrace of the error that you get?

**Comment by jd-alexander** [comment]
Oh it's a no such table found 
android.database.sqlite.SQLiteException: no such table: BEAT (code 1): , while compiling: SELECT * FROM BEAT WHERE (beat_id = ? ) LIMIT 1
1	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
2	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1121)
3	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:694)
4	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
5	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
6	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
7	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
8	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:143

**Comment by jd-alexander** [comment]
Only getting this on Android 4.4 though . And some tables are being created

**Comment by sibeliusseraphini** [comment]
@jd-alexander use this [script](https://gist.github.com/sibeliusseraphini/b060c415604c52c2a94e) and check it out the tables generated by Sugar

**Comment by jonisaa** [comment]
Did you have your model classes in separated packages? Would you like to show us your AndroidManifest.xml file?

**Comment by jd-alexander** [comment]
I fixed it. I didnt have anyh empty constructors on a few of my models. Thanks for the assistance.
