### ISSUE TITLE
Cursors missing from 1.4

### ISSUE THREAD

**Issue by caseyhelbling** [satyan/sugar#518]
Am I losing it or does the 1.4 release not contain the Cursor implementation from https://github.com/satyan/sugar/commit/ec0b465de3c8413977af6e18627885735d0e19db? 

My sugar-1.4.jar and source don't have it... What am I missing? 

Thanks!

**Comment by jonisaa** [comment]
How do you import the project?

**Comment by caseyhelbling** [comment]
Gradle 
`    compile 'com.github.satyan:sugar:1.4'`

**Comment by jonisaa** [comment]
It should contain that cursor implementation in fact. What are you trying to do? Explain a little more so I can help you to solve this!

**Comment by caseyhelbling** [comment]
I was trying to create a `CursorAdapter` for a ListView. Gradle installed sugar-1.4 (see screenshot.) But the class files don't actually have the implementation that I see on the commit https://github.com/satyan/sugar/commit/ec0b465de3c8413977af6e18627885735d0e19db

![2016-02-17 at 5 06 pm](https://cloud.githubusercontent.com/assets/12005/13128098/0ddd60f4-d599-11e5-9a5b-bda10850639e.png)

**Comment by jonisaa** [comment]
Yes, you got the reason, may be the modifications made by the commit you show me where deleted. Well, I think that your strategy to populate the listView was in the use of a CursorLoader? 

In this case, the possible work around you have it's to create your own loader implementation and your own adapter implementation or fork and clone this project and made the modifications you need.

**Comment by caseyhelbling** [comment]
Yah I mean ... I was trying to populate a CursorAdapter https://developer.android.com/reference/android/widget/CursorAdapter.html for my listview. I'll look into CursorLoader... For now I've just created an ArrayAdapter and query the db to pull in all the objects. Not optimal but works. 

Out of curiosity why where the Cursor commits pulled from the release?

**Comment by jonisaa** [comment]
I don't know really, I started to work as collaborator of this project 2 days ago.
Maybe this could help you, at work I have developed a little project and I have implemented own loaders and adapters: 
https://github.com/SAMSistemas/business-contacts 
Take a look and let me know if this helps you. 

I will close this issue, if you want you could send me emails to jonatansalas@live.com.ar!

**Comment by caseyhelbling** [comment]
:+1: Thank you! Cheers.
