### ISSUE TITLE
Documentation for using ProGuard with sugar

### ISSUE THREAD

**Issue by enyciaa** [satyan/sugar#520]
Hi,

I've run into a few issues with using ProGuard and sugar. The table name/column names end up becoming obfusacated letters (e.g. I, L, M). This makes it difficult to run SQL statements on the table at a later stage and causes a variety of other problems including crashes on Android 4.4. There's an easy fix to this by ensuring ProGuard keeps the domain classes un-obfuscated.

Adding this to ProGuard keeps domain classes un-obfuscated.
-keep class com.yourpackage.yourapp.domainclasspackage.** { *; }

However there's nothing that makes this obvious in the documentation. Please make this obvious to other developers using the library!

**Comment by sibeliusseraphini** [comment]
@enyciaa would you mind sending a PR for this?

Add this info to README and to docs, thanks

**Comment by enyciaa** [comment]
I've sent a pull request for the README

I'm not sure how to add it to the docs however?

**Comment by sibeliusseraphini** [comment]
thanks, you should use the [gh-pages](https://github.com/satyan/sugar/tree/gh-pages) branch

**Comment by sibeliusseraphini** [comment]
fixed with https://github.com/satyan/sugar/commit/fafe384bcf4cb47236fd561ba3a810e3c32a7327 by @enyciaa
