### ISSUE TITLE
Cannot specify the ID on insert (regression?)

### ISSUE THREAD

**Issue by scognito** [satyan/sugar#522]
Hi,
i want to create a record with a specific id:

Book manualBook = new Book(99L, "This book has its ID specified manually")
like explained here: [https://github.com/satyan/sugar/pull/78](https://github.com/satyan/sugar/pull/78)

Simplyfing, the class looks like this
```

 public class Book extends SugarRecord {
 
     public String name;
     //Long id; // from superclass SugarRecord
 
     public Book () {
     }
 
     public Book (Long id, String name) {
         this.id = id; // id has private access on com.orm.SugarRecord
         this.name = name;
     }
 }
```

The problem is that another commit ([https://github.com/satyan/sugar/pull/258](https://github.com/satyan/sugar/pull/258)) made the super class id private, and not accessible from the inner class.

Any way to fix this?

**Comment by jonisaa** [comment]
Yes, you can do this. You have two ways to generate your domain classes using Sugar. You can extend from SugarRecord (what actually you do) or use the annotation processing. With the annotation processing approach you have to generate an attribute id to make it work. Take a look at this page: http://satyan.github.io/sugar/creation.html

Let me know if this help you!

**Comment by scognito** [comment]
Thanks jonisaa for quick response.
I have several methods in my class that doesn't compile if I use the annotation:

```
public static List<Book> findOrderByName() {
        return Book.find(Book.class, null, null, null, "upper(name)", null);
    }
```
The error is "cannot resolve method find".
Same for executeQuery methods and such

I'm using sugar 1.4

**Comment by jonisaa** [comment]
Just do this! Replace all the methods that you have with Book. for SugarRecord.
I show you here how to do this, with the code you sent to me:

```
public static List<Book> findOrderByName() {
        return **SugarRecord.find(Book.class, null, null, null, "upper(name)", null);**
}
```

**Comment by scognito** [comment]
Worked, thank you very much!
