### ISSUE TITLE
Using cursors

### ISSUE THREAD

**Issue by MiguelFale** [satyan/sugar#527]
Hi! I'm currently using Sugar 1.3.1 (compile 'com.github.satyan:sugar:1.3.1')
I'm trying to figure out how to use cursors. The thread at https://github.com/satyan/sugar/issues/333 indicated I should use SugarRecord.getCursor(), but it doesn't exist in this version apparently.

Any help would be apreciated!

**Comment by jonisaa** [comment]
Why do you need the use of a cursor?

**Comment by MiguelFale** [comment]
@jonisaa I'm trying to create a CursorAdapter to use in  listview

**Comment by jonisaa** [comment]
Okey, I understand. I think another approach could be the use of a custom Adapter. You could create your own adapter that extends BaseAdapter class and pass by constructor a List<T> where T is the type of your model class. 
This is an example of a BaseAdapter class that I use to create my custom Adapters. Hope this helps!

```java
/**
 * @author jonatan.salas
 */
public class BaseListAdapter extends BaseAdapter {

    @NonNull
    protected Context mContext;

    @Nullable
    protected List mItems;

    /**
     * BaseListAdapter constructor with params
     *
     * @param context the context used to inflate the view that represent an Item in the ListView
     * @param items the list of items to populate
     */
    public BaseListAdapter(@NonNull Context context, @Nullable List items) {
        this.mContext = context;
        this.mItems = items;
    }

    @Override
    public int getCount() {
        return (null != mItems) ? mItems.size() : 0;
    }

    @Override
    public Object getItem(int position) {
        return (null != mItems) ? mItems.get(position) : null;
    }

    @Override
    public long getItemId(int position) {
        return (null != mItems) ? position : 0;
    }

    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        return null;
    }

    /**
     * ViewHolder abstract class
     *
     * @author jonatan.salas
     * @param <T> the object to bind with the view
     */
    public abstract static class ViewHolder<T> {

        /**
         * Abstract method whose purpose is to bind the view with the model
         *
         * @param object the object containing the data to be presented in a ListView item
         */
        public abstract void bindViews(T object);
    }
}
```

**Comment by jonisaa** [comment]
@MiguelFale could you solve the trouble?

**Comment by MiguelFale** [comment]
@jonisaa Sorry for taking so long. Yes, it worked! Thank you!

**Comment by jonisaa** [comment]
@MiguelFale you are welcome! Good luck =D

**Comment by bpappin** [comment]
Actually this doesn't solve it for me, because I use the LoaderManager. ListAdapters are for small amounts of data that you can hold in memory, they are not suitable to larger (more complex) datasets.

Additionally, you can't query them easily, to filter the list.

**Comment by JonatanSalas** [comment]
What you can do it's to create your own loader class extending from AsyncTaskLoader that returns a List of your objects. In your custom loader you perform all filter related operations. 

The problem is not the large amount of data. The problem is when you use a ListView without ViewHolder pattern. An adaptar can hold all the items you want, the problem is the itemView generation.  Maybe the most performant solution is to use a RecyclerView.

**Comment by bpappin** [comment]
I really don't want to do that, I am ripping out all the poorly written AsyncTask class I inherited as we speak (they are a maintenance nightmare), which is why I'm moving this code to cursor loaders in the first place.

My solution will be to create a ContentProvider that can work with SugarORM. It might be possible to make it adaptable (which could then be made into a pull request), but for now it will fit my application.

**Comment by luna-vulpo** [comment]
@bpappin  did you create a ContentProvider using SugarORM easly?

**Comment by bpappin** [comment]
I ended up having to fork the library, as the changes where too extensive to easily merge back in.
Once I decided to fork, I did not try to maintain backward compatibility.

I did make the fork public, in case you want to play with it, but you should consider it working but unstable.
See: https://bitbucket.org/sixgreen/sixgreen-cube

At some point in the future, I'll donate it back to this project and/or make it a more stable library.
