### ISSUE TITLE
How to change the id field

### ISSUE THREAD

**Issue by sagits** [satyan/sugar#529]
Hi, i'm trying to use sugar along with json data i get from my server. The problem is that both relies on the id field, is there a way to change the id property to not be auto-increment (my id already comes from server). Thanks in advance.

**Comment by jonisaa** [comment]
Yes, there is a way, you can use annotation processing approach. For example: 

```java
import com.orm.dsl.NotNull;
import com.orm.dsl.Table;
import com.orm.dsl.Unique;

/**
 * @author jonisaa
 */
@Table
public class Book {
    
    @Unique @NotNull
    private Long id;
    
    @Unique @NotNull
    private String title;
    
    @Unique @NotNull
    private String edition;

    /**
     * Empty constructor is needed 
     */
    public Book() { }

    public Long getId() {
        return id;
    }

    public Book setId(Long id) {
        this.id = id;
        return this;
    }

    public String getTitle() {
        return title;
    }

    public Book setTitle(String title) {
        this.title = title;
        return this;
    }

    public String getEdition() {
        return edition;
    }

    public Book setEdition(String edition) {
        this.edition = edition;
        return this;
    }
}
```

**Comment by sagits** [comment]
Thank you @jonisaa . May i ask you one more question? I use a model named MyModel which contains an Long id field as my super() for all my other models:
```
@Table
public class MyModel {
    @Unique @NotNull
    protected Long id;
}
```

```
public class Book extends MyModel {
    private String title;
    private String edition;
}
```

In this use case i would need to add the annotations in every class (@table and @unique)?

**Comment by jonisaa** [comment]
May I ask you some question, why would you create a class with only one field? The way you show me won't work, I will explain you why. 

When you annotate a class with @Table it needs an explicit declaration of a 
```java 
    private Long id;
```
Otherwise it won't work. So, any model class you have, will need three things in order for Sugar to work as expected: 
 - The @Table annotation 
 -  A private Long id field
 -  A public empty constructor

**Comment by jonisaa** [comment]
@sagits Let me know if this solves your trouble. I will close this issue for now.

**Comment by sagits** [comment]
Thank you. The truth is that theres a lot more on MyModel class. But essentialy, using the id on a super() was usefull for me to take care of adapter, network requests and common methods.
 
I'm originally using SharedPreferences to save my json and converting it to a List or object when i need to retrieve it, so i need a way to cast all my objects to a single type when i want to to use getById() or delete some local object. Something like:


```
public E getById(Long id) {

  for (E object : getAll() {
    if ( ( (MyModel) object).getId() == id) {
      return object; // the MyModel is a way to know that all classes have an id method
    }
  }

  return null;
}
```

I tried to use reflection too, but reflection cant get parent methods, the other approach would be to pass a comparable.

  You can get this class if you have become interested, [its among this project](https://github.com/sagits/android-fast-dao) (its named under LocalDao) its a volley library with loadings, parsing and offline caching (unfortunally the project is not working by itself by now, so you would need to copy/paste the .java on your project).

**Comment by jonisaa** [comment]
@sagits You can use Reflection to verify if all your model class have the @Table annotation, and if this is true, obtain the id. 
Check in this class the code:
https://github.com/satyan/sugar/blob/master/library/src/main/java/com/orm/util/ReflectionUtil.java

I think you can get some piece of code useful for your needs, Hope it helps!
