### ISSUE TITLE
Why getSugarDb method is protected?

### ISSUE THREAD

**Issue by yjwfn** [satyan/sugar#530]
```java
public class SugarContext {
 
   .....
    // How to get this SugarDb?
    protected SugarDb getSugarDb() {
        return sugarDb;
    }

   .....
}
```

**Comment by yjwfn** [comment]
How to get this SugarDb?

**Comment by sibeliusseraphini** [comment]
@jonisaa maybe he want to provide some specific functions that Sugar does not support out of the box

**Comment by jonisaa** [comment]
I understand but, he can fork the project and made the change.

**Comment by sibeliusseraphini** [comment]
maybe it is only useful for one of his projects

**Comment by jonisaa** [comment]
@yjwfn Well, in the case you want to obtain the SugarDb what you have to do is something like extending the SugarContext, and adding a public getter: 

```java
public class MySugarContext extends SugarContext {

        public SugarDb getDefaultSugarDb() {
                  return getSugarDb();
        }
} 
```
And then use it in your Application class: 

```java
public class MyApp extends Application {
      @Override 
      protected void onCreate() {
              super.onCreate();
              MySugarContext.init(this);
      }
 
      @Override 
      protected void onTerminate() {
            super.onTerminate();
            MySugarContext.terminate();
      }
}
```
And at the end in your android manifest file put this line:

```xml
<application android:label="@string/app_name" android:icon="@drawable/icon"
**android:name="com.yourpackage.MyApp"**>
       ...
</application>
```

**Comment by yjwfn** [comment]
@jonisaa The constructor of "SurgarContext" is private  so I had to fork the project.  Thank you for help me.

**Comment by jonisaa** [comment]
@yjwfn if you need something else just re open the issue!
