### ISSUE TITLE
No such table error

### ISSUE THREAD

**Issue by MiguelFale** [satyan/sugar#531]
# **UPDATE**
It seems like the casing is irrelevant, and so is the method of doing the query. We obtain the same errors regardless. We've pretty much exausted all our options at this point, including cleaning and rebuilding the project. We're considering switching for another ORM if this problem persists.

> Hi! I'm using sugar 1.4.
> 
> I'm having errors such as these:
> 
> android.database.sqlite.SQLiteException: no such table: DEVICES (code 1): , while compiling: SELECT * FROM DEVICES WHERE field = ?
> 
> from this line of code:
>   List<Devices> dids = devices.find(devices.class, "field = ?", field);
> 
> I have a persistence sugar class called "devices" (yes, it is lowercase). Would the casing of the class be a problem for sugar? Would the Select.from approach face the same issue?
> 
> For the record, the devices class has an empty constructor, and I have the following metadata tags in the manifest.
> 
> <meta-data
>             android:name="DATABASE"
>             android:value="databaseresc.db" />
>         <meta-data
>             android:name="VERSION"
>             android:value="3" />
>         <meta-data
>             android:name="QUERY_LOG"
>             android:value="true" />
>         <meta-data
>             android:name="DOMAIN_PACKAGE_NAME"
>             android:value=(correct path to package containing the persistence classes) />
> 
> Thanks in advance!

**Comment by MiguelFale** [comment]
For the record, the devices class has an empty constructor, and I have the following metadata tags in the manifest.

<meta-data
            android:name="DATABASE"
            android:value="databaseresc.db" />
        <meta-data
            android:name="VERSION"
            android:value="3" />
        <meta-data
            android:name="QUERY_LOG"
            android:value="true" />
        <meta-data
            android:name="DOMAIN_PACKAGE_NAME"
            android:value=(correct path to package containing the persistence classes) />

**Comment by jonisaa** [comment]
Show me your Devices class please!

**Comment by MiguelFale** [comment]
//imports....
public class Devices extends SugarRecord  {

	private String macAddress;

	private String gcmRegid;

	private String mode;

    private String model;

	private Users user;

    private int api_level;

	public Devices() {
	}

	public Devices(String mac_address, int user_id, String gcm_regid, String mode, String model, int api_level){
        this.macAddress = mac_address;

        List<Users> uids = Select.from(Users.class).where(Condition.prop("uid").eq(user_id)).list();
        this.user = uids.get(0);

        this.gcmRegid = gcm_regid;
        this.mode = mode;
        this.model = model;
        this.api_level = api_level;
	}
//getters and setters...
}

**Comment by jonisaa** [comment]
Would you have a time to make a little project to reproduce the error?

**Comment by MiguelFale** [comment]
@jonisaa Sorry, unfortunately we had to change our ORM.

Thanks for your time!

**Comment by firasalkafri** [comment]
Instant Run now works #564
