### ISSUE TITLE
Error on compile

### ISSUE THREAD

**Issue by x4vl** [satyan/sugar#532]
I use the gradle dependency and this is the class:
```
public class City extends SugarRecord {
    int id;
    String name;

    public City() {}
}
```

When I try to retrieve all the cities in this way:
```
List<City> cities = City.findAll(City.class);
```

I got the error:

```
Error:(40, 46) error: incompatible types: no instance(s) of type variable(s) T exist so that Iterator<T> conforms to List<Italy>
where T is a type-variable:
T extends Object declared in method <T>findAll(Class<T>)
```

**Comment by jonisaa** [comment]
Would you like to show me your AndroidManifest.xml metadata? Did you try a:
```gradle
gradle clean build
```

**Comment by x4vl** [comment]
Clean build does not fix the error.

Here is my Manifest.xml

```
<meta-data android:name="DATABASE" android:value="countries.db" />
<meta-data android:name="VERSION" android:value="1" />
<meta-data android:name="QUERY_LOG" android:value="true" />
<meta-data android:name="DOMAIN_PACKAGE_NAME" android:value="com.xxx.app" />
```

I tried this domain package name too, as model package is `com.xxx.app.db`:

```
<meta-data android:name="DOMAIN_PACKAGE_NAME" android:value="com.xxx.app.db" />
```

But I got the same error:

```
Error:(40, 45) error: incompatible types: no instance(s) of type variable(s) T exist so that Iterator<T> conforms to List<City>
where T is a type-variable:
T extends Object declared in method <T>findAll(Class<T>)
```

**Comment by jonisaa** [comment]
Try this, refactor the int id to something else.

**Comment by jonisaa** [comment]
@x4vl can you solve the problem, or still have the same trouble?

**Comment by x4vl** [comment]
Not yet. 
`find` is working but `findAll` throws me that error.

`City.find(City.class, "visible = 1");`  is OK
`City.findAll(City.class);`  throws the error

I'm using: `City.find(City.class, null);`

**Comment by maslick** [comment]
Same problem here
