### ISSUE TITLE
gradle error

### ISSUE THREAD

**Issue by george9105** [satyan/sugar#534]
Hello I'm getting this error when i try to gradle my code 

i'm using: compile 'com.github.satyan:sugar:1.4'

Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.7.0_79\bin\java.exe'' finished with non-zero exit value 2

any suggestion??

**Comment by PadaliaRushabh** [comment]
I think this is a MultiDex error. You might have crossed the 65k reference limit. 
[Refer here](http://developer.android.com/tools/building/multidex.html).

Also checkout the[ stackoverflow post ](http://stackoverflow.com/questions/33717886/errorexecution-failed-for-task-apptransformclasseswithdexfordebug) for solution.

**Comment by george9105** [comment]
Thanks @PadaliaRushabh  i followed the post and it works !!!!

**Comment by PadaliaRushabh** [comment]
you are welcome!
