### ISSUE TITLE
no such table in [com.android.tools.build:gradle:2.0.0-beta6]

### ISSUE THREAD

**Issue by s90304a123** [satyan/sugar#536]
I found in  [com.android.tools.build:gradle:2.0.0-beta6] 
always get No such table error...
I trace the source to here class : `com.orm.util.ReflectionUtil`
`getAllClasses` method always return 0 length
Could you fix this bug?

**Comment by jonisaa** [comment]
@s90304a123 show me your model classes! Have they an empty constructor? How is defined the AndroidManifest metadata?

**Comment by s90304a123** [comment]
@jonisaa I'm pretty sure model classes have an empty constructor. And my AndroidManifest metadata like this :   
```
 <meta-data  android:name="DATABASE"   android:value="ccv.db"/>
 <meta-data  android:name="VERSION"  android:value="3"/>
 <meta-data android:name="QUERY_LOG" android:value="true"/>
 <meta-data  android:name="DOMAIN_PACKAGE_NAME"  android:value="db"/>
```
I change android plugin version to : `com.android.tools.build:gradle:1.5.0`
and grandle version to: 2.6
does not appear this bug

**Comment by jonisaa** [comment]
@s90304a123 When you where working with the plugin version 1.5.0 of gradle, your code works correctly?

**Comment by s90304a123** [comment]
@jonisaa Yes, when I downgrade to 1.5 version  of `com.android.tools.build:gradle`, everything is perfect.
I guess the problem is Reflection.

**Comment by jonisaa** [comment]
@s90304a123 It's strange, because I have a project with the latest gradle beta plugin working fine. When working with gradle beta plugin, which version of gradle do you use?

**Comment by mikecole20** [comment]
I'm also seeing this issue.

**Comment by mikecole20** [comment]
I realized that I'm using Sugar 1.3. I'm in the progress of updating to 1.5. I'll report back with results.

**Comment by mikecole20** [comment]
Ok, I have confirmed this is an issue with Sugar 1.5 as well.

**Comment by sibeliusseraphini** [comment]
@mikecole20 could you share your logs?

could you create a repo on github with this problem? so we can reproduce it?

**Comment by WoogieNoogie** [comment]
I've run into a similar problem, but it's only an issue if I build from Android Studio - everything is fine if I build from command line. Not sure if there's anything else I can contribute.

**Comment by ed-george** [comment]
I also experienced this issue (see #542) and found that disabling the experimental 'Instant Run' feature resolved it.

**Comment by WoogieNoogie** [comment]
Thanks for the tip @ed-george - disabling instant run did fix it. I've also updated to 2.1.0-alpha1 and this fix works there as well.

**Comment by ed-george** [comment]
No problem @WoogieNoogie, for the meantime I would suggest that disabling the feature is the current workaround and should be documented as such.

Currently in which channel is 2.1.0-alpha1 available? I will try to verify that too.

**Comment by WoogieNoogie** [comment]
It's up on Jcenter, you can use it without updating Android Studio, but the version of AS that forces the update to it is in the Canary channel.

**Comment by ed-george** [comment]
@mikecole20 I can confirm that the issue only occurred once the app was uninstalled, however the AS version migration I had problems with was from 2.0.0-beta4 to 2.0.0-beta6. 2.0.0-beta4 seemed to work as expected for me.

**Comment by rkj1515** [comment]
Android Instant run is a problem. disable it and remove your build folder.
Do a fresh install and all set

**Comment by firasalkafri** [comment]
Any updates on this issue?

**Comment by sibeliusseraphini** [comment]
use sugar 1.5

**Comment by firasalkafri** [comment]
1.5 didn't solve the InstantRun issue

**Comment by sibeliusseraphini** [comment]
have you guys added the following information in the manifest http://satyan.github.io/sugar/getting-started.html

and in the Application?

**Comment by firasalkafri** [comment]
@sibeliusseraphini yes definitely, I didn't just start using SugarORM

**Comment by firasalkafri** [comment]
Instant Run now works #559

**Comment by sibeliusseraphini** [comment]
fixed with https://github.com/satyan/sugar/pull/564 @firasalkafri

**Comment by davidruizdiaz** [comment]
gracias @ ed-george me ayudó mucho
