### ISSUE TITLE
No such table exeption

### ISSUE THREAD

**Issue by iqorlobanov** [satyan/sugar#537]
Sugar orm works perfectly on Android <5, but on Android 5> it crashes.
I am using version 1.4

Please help me.

`Error: android.database.sqlite.SQLiteException: no such table: AUDIO (code 1): , while compiling: SELECT * FROM AUDIO`

```
#Sugar
-keep class me.lobanov.mp3downloadsfree.models.** { *; }
```

```
package me.lobanov.mp3downloadsfree.models;

import com.orm.SugarRecord;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
public class Audio extends SugarRecord {
    private long aud_id;
    private String aud_artist;
    private String aud_title;
    private String aud_url;
    private long aud_duration;

    public Audio() {
    }

    public Audio(long aud_id, String aud_artist, String aud_title, String aud_url, long aud_duration){
        this.aud_id = aud_id;
        this.aud_artist = aud_artist;
        this.aud_title = aud_title;
        this.aud_url = aud_url;
        this.aud_duration = aud_duration;
    }
}


public class App extends SugarApp {
    @Override
    public void onCreate() {
        super.onCreate();
    }
}

<meta-data android:name="DATABASE" android:value="mp3downloadsfree.db" />
        <meta-data android:name="VERSION" android:value="5" />
        <meta-data android:name="QUERY_LOG" android:value="true" />
        <meta-data android:name="DOMAIN_PACKAGE_NAME" android:value="me.lobanov.mp3downloadsfree.models" />
```

**Comment by carlosrc** [comment]
Same error here in Android Studio 2.0 Beta 6.

**Comment by sibeliusseraphini** [comment]
@carlosrc could you try with version 1.5

**Comment by iqorlobanov** [comment]
@sibeliusseraphini  nothing change, i'm using Android Studio 2.0 Beta 6 too

**Comment by sibeliusseraphini** [comment]
@iqorlobanov is your android studio 2.0 beta 6 using all your resources (100% cpu and a lot of memory)?

**Comment by sibeliusseraphini** [comment]
It is working on version 1.5 and master version using android studio 2.0 beta 6

Maybe you should also set your application name on your manifest

```xml
<application
        android:name=".MyApp"
        android:allowBackup="true"
        tools:replace="android:icon">
```

```java
public class MyApps extends SugarApp
```

**Comment by iqorlobanov** [comment]
@sibeliusseraphini works well only on Android <5

**Comment by sibeliusseraphini** [comment]
@iqorlobanov could you clean your project, uninstall your app from your device and install it again?

**Comment by sibeliusseraphini** [comment]
I don't know how Sugar works with lombok

**Comment by iqorlobanov** [comment]
@sibeliusseraphini i did everything but it dont work :(

**Comment by iqorlobanov** [comment]
@sibeliusseraphini works well only on Android 4.4

**Comment by sibeliusseraphini** [comment]
are you using multidex?

**Comment by iqorlobanov** [comment]
@sibeliusseraphini no

**Comment by sibeliusseraphini** [comment]
could you grab your database using this - https://gist.github.com/sibeliusseraphini/b060c415604c52c2a94e

and check whether Sugar is creating your tables correctly

**Comment by luyzfernando** [comment]
First, sorry for bad English. =)

I had the same problem, but with the 5.0 version of Android.

Previously I was using version 1.4, but always occurred a problem with versions < 5.

I downloaded version "master" with support "MultiDex" and the problem had been solved, until this morning.

However, the error happened today and version 5 of Android. (I am using AS 2.0 Beta 6)

To solve the problem right away and not take more risks, I decided to change the library "sugar" locally and manually add classes.

> It's not pretty, is not cool, but I'm sure that no user will complain =D

**Comment by jonisaa** [comment]
@iqorlobanov could you solve your problem?

**Comment by iqorlobanov** [comment]
@jonisaa , no :(

**Comment by jonisaa** [comment]
@iqorlobanov okey, so let's try this. I don't know Lombok, for the moment delete all @Setter, @Getter and @ToString Annotations. Do a clean project command and rebuild it. 

Deploy the project again in your mobile device and let me know if it still throw the same problem.

**Comment by TianLiJun** [comment]
I have  the same issue。 
`
 android.database.sqlite.SQLiteException: no such table: BEAN (code 1): , while compiling: INSERT OR REPLACE  INTO BEAN(ID,BEAN_ID,NAME) VALUES (?,?,?)
`
this is my mainfest
`
   <meta-data android:name="DATABASE"  android:value="enterpriseedition.db" />
        <meta-data android:name="VERSION"   android:value="1" />
        <meta-data android:name="QUERY_LOG" android:value="true" />
        <meta-data android:name="DOMAIN_PACKAGE_NAME"  android:value="com.enterpriseedition" />

`

**Comment by XxPixX** [comment]
I had the same issue. In the end I disabled instant run, uninstalled the app (remember to uninstall for all users!), removed multidex and then cleaned the project and it worked.

Using gradle 2.0.0 beta 6 and the latest android studio preview

**Comment by jeffhtli** [comment]
I have same issue with "Instant Run" enable:

AS 2.0 beta 6
multidex NOT enable
Nexus 5X_API_23 emulator

It works fine if I disable "Instant Run" in Settings.

**Comment by firasalkafri** [comment]
Instant Run now works #559

**Comment by sibeliusseraphini** [comment]
fixed with https://github.com/satyan/sugar/pull/564 @firasalkafri

**Comment by sfilatov96** [comment]
Hi guys, i have the same error.  I could create first table but when i decided to create 2nd table, i got this error "No such table .........".
I Found solution. Just remove your app from your phone and than install your app again!!It really works!
Good Luck :)
