### ISSUE TITLE
How to listen for db changes?

### ISSUE THREAD

**Issue by frakc** [satyan/sugar#541]
loader manages gave us grate ability to get fresh contant as soon as it wos updated. Is that feature implemanted in sugar?

**Comment by jonisaa** [comment]
@frakc No, this is not actually implemented on Sugar. In the case you want fresh content you will have to generate your own loader class extending from [AsyncTaskLoader](http://developer.android.com/reference/android/content/AsyncTaskLoader.html). 

We are working on Sugar v2.0 which will use RxJava Observables to listen for DB changes on CRUD operations. 

Let me know if this help you!

**Comment by frakc** [comment]
@JonatanSalas did nto success on making my own loader, thus still using contentproviders.
I am really wating for Sugar v2.0, I was surprised  how much cleaner and smother was development with Sugar.

**Comment by JonatanSalas** [comment]
@frakc why don't you succeed on making a loader?

**Comment by JonatanSalas** [comment]
@frakc I will close it. If you need something else please re open it.
