### ISSUE TITLE
Not creating tables in Android Studio 2.0 beta 6

### ISSUE THREAD

**Issue by ed-george** [satyan/sugar#542]
I noticed today that after upgrading from Android Studio 2.0 beta 4 to beta 6, that `SugarRecord` tables are not being created through fresh app install, database migration through version change, database migration through database name change and all other methods.

I believe this is to do with the '[Instant Run](http://tools.android.com/tech-docs/instant-run)' feature as disabling this seems to resolve the issue.

I am not sure if there is anything that can be done by Sugar resolve this, but as it is likely to crop up in future, I believe it should be added to the README or associated documentation to warn others.

**Comment by jonisaa** [comment]
Yes, this problem is generated by InstantRun feature. We will work to improve compatibility with this Android Studio 2 feature.

**Comment by ed-george** [comment]
Thanks for your response @jonisaa, is there any current work around that enables Instant Run to be enabled?

**Comment by jonisaa** [comment]
For the moment, I don't know a possible workaround to solve this trouble. Let me invest some time to find the root cause of the trouble and solve it. 

I think the main problem is how InstantRun generate the .classes files and how It deploys to the runing device.

**Comment by tentypwtk** [comment]
After upgrading Android Studio to 2.1 (Preview 1) this problem is now occuring.
Any solution apart from downgrading to previous studio / going back to gradle 2.0.0-beta6?

**Comment by squeeish** [comment]
I migrated from ActiveAndroid because it wasn't creating tables too. Glad someone pointed it out!

**Comment by firasalkafri** [comment]
Any updates on this issue?

**Comment by jdochez** [comment]
The issue seems to be linked to this code :
https://github.com/satyan/sugar/blob/master/library/src/main/java/com/orm/util/MultiDexHelper.java

in InstantRun mode, we do not deliver the dex files in the main APK but inside an instant-run.zip file located in the root on the APK.

so the code above should be adapted to iterate over the content of the instant-run.zip (which will be a bunch of dex files) and getAllClassNames from it. 

If you need more information, please contact jedo@google.com

**Comment by sibeliusseraphini** [comment]
@jdochez do you know how to fix this?

**Comment by firasalkafri** [comment]
@jdochez thank you so much, I will be contacting you soon for more information if needed 

@sibeliusseraphini I am working on it, will be submitting a pull request soon

**Comment by sibeliusseraphini** [comment]
@firasalkafri that's great

**Comment by chandu4ugandhi** [comment]
@firasalkafri Is there any update for this problem.. I am facing the same issue for not creating the table like this:

android.database.sqlite.SQLiteException: no such table: FAVOURITE

**Comment by firasalkafri** [comment]
@chandu4ugandhi I have submitted a pull request #559 with the solution and waiting for the repository's maintainers to review and merge it

**Comment by chandu4ugandhi** [comment]
@firasalkafri then it would be new version for the sugar library? if yes then what it would be? let me know asap... my whole app stuck due to this bug. I am not able to work further currently.

**Comment by firasalkafri** [comment]
@chandu4ugandhi You either wait for the next release or use the library from source code including my changes.

**Comment by chandu4ugandhi** [comment]
@firasalkafri can you give me the link of your changed library so i can use as source code in my app.

**Comment by firasalkafri** [comment]
https://github.com/firasalkafri/sugar

**Comment by ed-george** [comment]
@chandu4ugandhi please see #536 - There is discussions around a temporary work around through disabling the Instant Run feature.

**Comment by firasalkafri** [comment]
@ed-george I'm talking about a solution, no need for work arounds.

**Comment by chandu4ugandhi** [comment]
@ed-george how to disable the instant run feature in android studio

**Comment by chandu4ugandhi** [comment]
@firasalkafri how to use the source code as library to my app that I downloaded from the url that you given.

**Comment by firasalkafri** [comment]
@chandu4ugandhi Simple, just read the documentation.

**Comment by chandu4ugandhi** [comment]
@firasalkafri there is a line about the eclipse.. no android studio help... give me the proper link where it can help me to import the source code as library.

**Comment by JonatanSalas** [comment]
This is solved in PR #564
