### ISSUE TITLE
Suggested improvement: setLocale

### ISSUE THREAD

**Issue by falkontre** [satyan/sugar#546]
Hi,

I have some columns storing decimal number, but in Europe we use the comma as decimal separator so it would be nice to call the setLocal on the database when creating tables.

**Comment by JonatanSalas** [comment]
I will take care about that! Thanks for your suggestion!

**Comment by falkontre** [comment]
thank you! BTW, the method is setLocale and not setLocal ;)

**Comment by JonatanSalas** [comment]
I will submit a pull request today. Which is the best way to setLocale, using: 

```java
db.setLocale(Locale.getDefault());
```

Or using metadata parameter? 

I think the first approach is the best but I would like to look at any suggestion.

**Comment by JonatanSalas** [comment]
I have submitted a PR #566! If I'am able to merge you will have the solution. But you wil have to use Sugar master branch in your project!

**Comment by falkontre** [comment]
I suggest to have a method like db.setLocale(Locale.<COUNTRY>) and a method db.setDefaultLocale(Locale.getDefault()).

**Comment by JonatanSalas** [comment]
I have done like 

```java
db.setLocale(Locale.getDefault()); 
```

**Comment by JonatanSalas** [comment]
@falkontre I have submitted a new PR #569 which solves this using a class called SugarDbConfiguration.

**Comment by JonatanSalas** [comment]
This has been solved by the PR I have submitted. This code it's not released yet, use from master branch. 

You can use SugarDBConfiguration class and passing in the SugarApp init method.

But take care because I will make a change to pass the Locale through metadata configuration over the AndroidManifest file.
