### ISSUE TITLE
Update db schema : recreate table ? 

### ISSUE THREAD

**Issue by CallisteHanriat** [satyan/sugar#552]
Hi, 

I have added one entity to my User class. And then, I have deleted all my current Users. After that, I've added one to the version of my db in the manifest. But when i compile my app, I have the error of non existent column in my table. So how can I recreate totally a table ? 

Thanks in advance, 

CallisteHanriat

**Comment by sibeliusseraphini** [comment]
@CallisteHanriat could you give more explanation? or an example?

**Comment by CallisteHanriat** [comment]
Hi, 

I've finally get the solution : To update our schema, we just have to add elements and what we want in java code and then, uninstall the app to delete `.db` file. 

After new compilation, we've the new table !
