### ISSUE TITLE
It is a bug?

### ISSUE THREAD

**Issue by strongmanb** [satyan/sugar#555]
When I use sugar to save a object, it crash

at com.orm.util.ReflectionUtil.getDomainClass(ReflectionUtil.java:274)

**Comment by sibeliusseraphini** [comment]
@strongmanb 1.5?

**Comment by strongmanb** [comment]
yes. It is 1.5. It run ok in the android emulator,but  it crash when I run in the real phone.

**Comment by sibeliusseraphini** [comment]
@strongmanb could you provide more info about the error? the full stack trace

**Comment by JonatanSalas** [comment]
Yes, this was a bug and now it's solved by PR #565

**Comment by JonatanSalas** [comment]
You have to use the branch master of Sugar. I will close the issue. If you need something related to this, please re open!
