### ISSUE TITLE
find with boolean value in where condition didn't worked

### ISSUE THREAD

**Issue by shashi2459** [satyan/sugar#558]
Hello there, 
 In a model, I have a boolean member var and I tried to access the model on this boolean constraints.
And I didn't get any record even if it was having the matching row at DB.
But when I tried to get List of all, I got all rows.
And when I changed the boolean type to string I got the model.
My code was like this.
I tried this in 3 different ways, but didnt worked for me.

`Table.find(Table.class, "deleted=?", "false");`
`Table.findWithQuery(Table.class, "select * from TABLE where deleted=?", "false");`
`Select.from(Table.class).where(Condition.prop("deleted").eq("false")).list();`

**Comment by JonatanSalas** [comment]
Actually boolean search is not working with true/false or "true"/"false". 
You have to pass as method parameter 1/0 integer values. 
Yeah, it sucks. But there is a PR that we are analizing to integrate which solves this trouble! 

Hope it helps!

**Comment by sibeliusseraphini** [comment]
@shashi2459 could you test this PR (https://github.com/satyan/sugar/pull/553)

It address this issue, let me know if this is working, and then I can mege with master

**Comment by shashi2459** [comment]
@sibeliusseraphini , I would like to use the PR(#553).
But I cant modify the library code since I haven`t  downloaded the source instead i used Gradle .
I gone through PR(#553), and it will work, rather it has to work.

**Comment by JonatanSalas** [comment]
@shashi2459 I have merged PR #553 try using the Master branch to add Sugar. I will close it because in fact the PR solves this. If you found a trouble or something, please re open this issue. Good luck!
