### ISSUE TITLE
heritage of class and save elements

### ISSUE THREAD

**Issue by CallisteHanriat** [satyan/sugar#560]
Hi, 

I've a class like that : 
`Person` which is the mother class : contains sex, age, name.

tow subclass : 
`Student` and `Teacher`

I've saved differents students and teachers and I would like to get every Peron entities with code like that : 
`Person.listAll(Person.class)`

But it doesn't work. i feel that Sugar doesn't understand the domain of heritage.

Any ideas ? 

thanks

**Comment by JonatanSalas** [comment]
What you can do it's to put a flag to indicate if a person is student or teacher. Or you can make separated classes.

**Comment by CallisteHanriat** [comment]
Hi, I've finnaly find a solution, 

I've created a static function findAll into the mother class to get all subclasses.ListAll element !


thanks for your suggestion !
