### ISSUE TITLE
NO SUCH TABLE with gradle dependency 2.0

### ISSUE THREAD

**Issue by aditya122931** [satyan/sugar#571]
with the new gradle dependency 2.0.0
com.android.tools.build:gradle:2.0.0,
dexfile.entries() files no longer contain application classes, so every time sugar tries to create tables in onCreate of SugarDb, domainClasses are returned empty and hence no tables are created resulting in NO SUCH TABLE error. i had to spend 3 hours debugging it line by line to locate the problem and finaly reverted back to gradle 1.5.0.

it is important we support gradle 2.0 for its performance enhancements.

**Comment by scognito** [comment]
I had the same issue upgrading to Android Studio 2.0 :/

**Comment by JonatanSalas** [comment]
This issue is actually solved by PR satyan/sugar#564.

**Comment by JonatanSalas** [comment]
The problem is that you have to use the master branch of Sugar for having this support. I have talked to @satyan if he could launch a release v1.5.1 of sugar. For now the solution is to import master branch in your project.
