### ISSUE TITLE
No such table Exception on Android Studio with Instant Run enabled

### ISSUE THREAD

**Issue by fertwo** [satyan/sugar#575]
Hi guys, I was working without any problems with Sugar ORM until I upgraded Android Studio to 2.0 version. 
Isuue: The application does not create tables and throws "NoSuchTableException" every time. Solution: Disable instant run.
Question: Will you do something to fix this issue in future releases?

Tnx!

**Comment by JonatanSalas** [comment]
Yes, this is solved in PR #564! But there is no release yet.

**Comment by JonatanSalas** [comment]
I will close the issue! If you need something else related to this please re open!
