### ISSUE TITLE
Android Studio 2.0 Instant Run causes problems

### ISSUE THREAD

**Issue by deano2390** [satyan/sugar#576]
The new instant run feature of Android Studio 2.0 causes some issues with the initial database creation code.

For me in version 1.5 of Sugar, the problem lies in ReflectionUtil.java at line 299 - MultiDexHelper.getAllClasses(context);

MultiDexHelper.getAllClasses(context) now only returns just a handful of classes which all appear to be some sort of wrapper/runtime around your real app which deals with the code hotswapping. None of your own classes are returned by this method anymore so none of your entity classes get detected and the corresponding SQL tables never get created.

The short term workaround is to disable the hot swap feature (at least for the initial deployment of your app, I guess it should work fine for subsequent runs).

**Comment by sibeliusseraphini** [comment]
fixed with this PR https://github.com/satyan/sugar/pull/564

use master version please
