### ISSUE TITLE
version 1.5 not support instant-run.zip

### ISSUE THREAD

**Issue by WuZhenXing** [satyan/sugar#581]
0 = "com.android.tools.fd.common.Log$Logging"
1 = "com.android.tools.fd.common.Log"
2 = "com.android.tools.fd.common.ProtocolConstants"
3 = "com.android.tools.fd.runtime.AbstractPatchesLoaderImpl"
4 = "com.android.tools.fd.runtime.AndroidInstantRuntime$1"
5 = "com.android.tools.fd.runtime.AndroidInstantRuntime$Logging"
6 = "com.android.tools.fd.runtime.AndroidInstantRuntime"
7 = "com.android.tools.fd.runtime.AppInfo"
8 = "com.android.tools.fd.runtime.ApplicationPatch"
9 = "com.android.tools.fd.runtime.BasicType"
10 = "com.android.tools.fd.runtime.BootstrapApplication$1"
11 = "com.android.tools.fd.runtime.BootstrapApplication"
12 = "com.android.tools.fd.runtime.FileManager"
13 = "com.android.tools.fd.runtime.IncrementalChange"
14 = "com.android.tools.fd.runtime.IncrementalClassLoader$1"
15 = "com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader"
16 = "com.android.tools.fd.runtime.IncrementalClassLoader"
17 = "com.android.tools.fd.runtime.InstantReloadException"
18 = "com.android.tools.fd.runtime.MonkeyPatcher"
19 = "com.android.tools.fd.runtime.PatchesLoader"
20 = "com.android.tools.fd.runtime.PatchesLoaderDumper"
21 = "com.android.tools.fd.runtime.Paths"
22 = "com.android.tools.fd.runtime.Restarter$1"
23 = "com.android.tools.fd.runtime.Restarter$2"
24 = "com.android.tools.fd.runtime.Restarter$3"
25 = "com.android.tools.fd.runtime.Restarter"
26 = "com.android.tools.fd.runtime.Server$1"
27 = "com.android.tools.fd.runtime.Server$SocketServerReplyThread"
28 = "com.android.tools.fd.runtime.Server$SocketServerThread"
29 = "com.android.tools.fd.runtime.Server"
30 = "com.android.tools.ir.api.DisableInstantRun"

`
MultiDexHelper.getAllClasses(context) run result`

**Comment by JonatanSalas** [comment]
Actually this is solved in branch master by PR #564

**Comment by JonatanSalas** [comment]
We are waiting for release a v1.5.1 to patch it.

**Comment by WuZhenXing** [comment]
@JonatanSalas 
`  public static List<String> getSourcePaths(Context context) throws PackageManager.NameNotFoundException, IOException {
        ApplicationInfo applicationInfo = context.getPackageManager().getApplicationInfo(context.getPackageName(), 0);
        File sourceApk = new File(applicationInfo.sourceDir);
        File dexDir = new File(applicationInfo.dataDir, SECONDARY_FOLDER_NAME);
        ZipFile zf = new ZipFile(applicationInfo.sourceDir);
        ZipEntry ze = zf.getEntry("instant-run.zip");
        InputStream is = zf.getInputStream(ze);
        File instantFile = new File("/storage/sdcard0/instantFile.zip");
        if(!instantFile.exists())
            instantFile.createNewFile();
        StreamUtils.copy(is, new FileOutputStream(instantFile));
        zf.close();
        zf = new ZipFile(instantFile);
        Enumeration eee = zf.entries();
        while(eee.hasMoreElements()){
            ZipEntry zz = (ZipEntry)eee.nextElement();
            System.out.println(zz.getName());
        }
        return null;
    }`

**Comment by JonatanSalas** [comment]
You have a possible workaround. On first app deploy disable Instant Run, then, enable it. The problem is only when trying to generate the tables.
