### ISSUE TITLE
No tables are created

### ISSUE THREAD

**Issue by friedger** [satyan/sugar#582]
in `MultiDexHelper.getAllClasses` only some com.android classes are returned.

I am running Android 5.1.1 on a One Plus One.

**Comment by JonatanSalas** [comment]
The problem is around Instant Run feature. This has been solved by PR #564. That branch has been merged with master. The possible workaround is to use sugar from master or disable Instant Run on first app deployment.

**Comment by friedger** [comment]
Thanks
