### ISSUE TITLE
Using sugar orm and google analytics at one project

### ISSUE THREAD

**Issue by HosseinKurd** [satyan/sugar#586]
How to Use sugar orm and other libraries use class extends application in one project

**Comment by JonatanSalas** [comment]
@HosseinKurd what you can do it's to extend SugarApp class which is a class that extends the application class. Then register the class you extend in the android manifest file. 

```java
public class MyApp extends SugarApp {
       //Here you do the stuff of register google analytics...
}
```
And in your androidManifest.xml file: 

```xml
<application android:label="@string/app_name" android:icon="@drawable/icon" android:name="MyApp">

</application>
```
Let me know if this helps you

**Comment by HosseinKurd** [comment]
i tested it before, not works and shows fore close
But now it doesn't save any thing!
and after i remove app and test with
`android:name="com.orm.SugarApp"`
it works but my stuf doesn't

**Comment by HosseinKurd** [comment]
I Solved It


public class Manage extends SugarApp {

    @Override
    public void onCreate() {
        super.onCreate();
        SugarContext.init(this); // Here This Method Called
        LTH.dLog("Manage_TAG", "On Create Manage Class");
    }

    @Override
    public void onTerminate() {
        super.onTerminate();
        SugarContext.terminate(); // Here This Method Called
        LTH.dLog("Manage_TAG", "On Terminate Manage Class");
    }
}
