### ISSUE TITLE
unique on multiple columns

### ISSUE THREAD

**Issue by moallemi** [satyan/sugar#587]
How can I define unique on multiple columns with sugar?

CREATE TABLE a (i INT, j INT, UNIQUE(i, j) ON CONFLICT REPLACE);

**Comment by JonatanSalas** [comment]
You can define a multi unique sqlite table with the usage of @MultiUnique on top of a Sugar model. 

Take the following code as an example:

'''Java
@MultiUnique
public class MyEntity extends SugarRecord { }
'''

**Comment by moallemi** [comment]
thanks
