### ISSUE TITLE
Error:Gradle DSL method not found: 'isReleaseBuild()'

### ISSUE THREAD

**Issue by meeximum** [satyan/sugar#589]
When I try to integrate in a fresh new Android 2.0 project, as described here
[https://github.com/satyan/sugar#how-to-use-master-version]

I got the error message
Error:Gradle DSL method not found: 'isReleaseBuild()'
Stacktrace
Caused by: org.gradle.api.internal.MissingMethodException: Could not find method isReleaseBuild() for arguments [] on project ':sugar'.

**Comment by sibeliusseraphini** [comment]
just comment this line please https://github.com/satyan/sugar/blob/master/library%2Fbuild.gradle#L2

**Comment by meeximum** [comment]
perfect, thx

**Comment by jaibatrik** [comment]
@sibelius Instead of that comment solution, can't we have something in the library itself?

**Comment by sibelius** [comment]
@jaibatrik could u try to send a PR to solve this?

**Comment by jaibatrik** [comment]
@sibelius I am not entirely familiar with how this works... What I was thinking is that we can keep the line commented in master; while creating a tag, we can uncomment it and check-in into the tag. Then again comment it and push to master.

Does this sound reasonable to you?
