### ISSUE TITLE
No such table problem

### ISSUE THREAD

**Issue by tibuurcio** [satyan/sugar#592]
Hello,

I'm trying to use SugarORM in my application but keep getting "No such table" error whenever I try to execute any save/access/delete method. I've tried using both 1.4 as stated in the github site and 1.5 as stated in the github README.md file. I've also tried changing the VERSION of the database and erasing my app's saved data and it didn't work. I've tried both extending `SugarRecord` and using annotation `@Table` but nothing works.

**Comment by MDXDave** [comment]
It`s an problem related to the "Instant Run" feature of Android Studio 2.1, see MR #564
