### ISSUE TITLE
Query Building

### ISSUE THREAD

**Issue by homer123** [satyan/sugar#6]
Hi

Is there a simple way to query the database with complicated "finders" than the ones shows in the "Extra sugar" example ? For example, how does one find objects which satisfy criteria over different member variables ? On a related note... are you planning to add query building features like this in another android orm 

http://greendao-orm.com/documentation/queries/

Any help you provide is much appreciated.

Thank You

**Comment by emashara** [comment]
does sugar ORM support query like this 

elect PRODUCT from PRODUCT_TAGS where TAGS = 1 intersect Select PRODUCT from PRODUCT_TAGS where TAGS = 5;   how do i pass this using sugar orm . @satyan @whoshuu @homer123 @tobykurien @allieus please can some one help me .
