### ISSUE TITLE
listAll() problem

### ISSUE THREAD

**Issue by Rexota** [satyan/sugar#61]
Hey, when I list the datas with listAll(), the response is :
package.name@421d9f28, 
package.name@421da700, 
package.name@421dad40

My database contain :public Bets(Context context, int betid, int dicef, int dicet, int dices, int betamount,  String worl)

How can I correct this ?

Thanks.

**Comment by whoshuu** [comment]
I believe you're using an outdated version of the library. If the master branch doesn't fix your issues, let me know.
