### ISSUE TITLE
can not create table

### ISSUE THREAD

**Issue by waitinghc** [satyan/sugar#618]
why can not create table?? please help me

 <meta-data
            android:name="DATABASE"
            android:value="test.db"/>
        <meta-data
            android:name="VERSION"
            android:value="1"/>
        <meta-data
            android:name="QUERY_LOG"
            android:value="true"/>
        <meta-data
            android:name="DOMAIN_PACKAGE_NAME"
            android:value="com.test.bean"/>

application oncreate code
   @Override
    public void onCreate() {
        super.onCreate();

        SugarContext.init(this);

    }

**Comment by cutiko** [comment]
Maybe this could help https://github.com/satyan/sugar/issues/613#issuecomment-223300514

**Comment by JonatanSalas** [comment]
Do you have empty constructors in all your model classes? 

The data that you have put in the manifest is under or inside the application tag?

**Comment by lmvinicius** [comment]
I have the same problem here, I have empty constructors in all my model classes, all the configs in the manifest, instant run disabled. Tried with targetsdk 21 and 23, gradle 1.5 and 2.0, nothing works. Using Sugar 1.5. I always get an error saying that the table doesn't exist.
