### ISSUE TITLE
problem with sdk version 23

### ISSUE THREAD

**Issue by mreram** [satyan/sugar#647]
sugarorm not working with compile sdk version 23 and targetsdkversion 23
... plz help to debug it
what is problem with sdk version 23
i cannt change to sdk 21 please helppppppp me

**Comment by cutiko** [comment]
Maybe this thread help you https://github.com/satyan/sugar/issues/613#issuecomment-223300514

**Comment by mreram** [comment]
@cutiko i read all issues and i use 
class ApplicationLoader extends SugarApp 
and gradle 1.5 and disable instant run but not solve my problem
...

**Comment by mreram** [comment]
i write meta-data out of application in manifest and solved my problem !! 
thank u 

```
<meta-data
    android:name="VERSION"
    android:value="3" />
<meta-data
    android:name="QUERY_LOG"
    android:value="true" />
<meta-data
    android:name="DATABASE" android:value="owner.db" />
<meta-data
    android:name="DOMAIN_PACKAGE_NAME"
    android:value="....bizOwner.store" />

<meta-data
    android:name="com.google.android.gms.version"
    android:value="@integer/google_play_services_version" />
<meta-data
    android:name="com.google.android.maps.v2.API_KEY"
    android:value="@string/google_maps_key" />

<application
    android:name=".ApplicationLoader"....
```

......
