### ISSUE TITLE
One to many Relationship in 1.4

### ISSUE THREAD

**Issue by DarkLord44** [satyan/sugar#651]
Hi, want ot save two objects (Object A and Object B) with an one to many relationship. I want to save Object B in an Array of Objects B in Object A. I tried this now a long time and read the topics in this forum. But I didnt find a soultion. I looked in the SQLite Database and it seems, that the connection will be saved, but if i load the Object A by findById, i my Array of Object B is null. 
Does anybody have experience with one to many relationships and have maybe some tips for me?

**Comment by cutiko** [comment]
Save the array childs as SugarRecord objects individually after saving the Object A so you can set the id of parent A to each child B (parent_id).

You can do this:

- Manually by looping an array
- Override save method in the Object B class
- Override save method in Object A to do it so

Then to get your Object B array from Object A, use a getter in which a query based on `"parentId = ?",  String.valueOff(parentId)`

Note: you will want to add the ignore annotation in the array of B objects in the Object A class to avoid conflicts.

I have always have the same problem and this is not the first thread about it, glad I had time to share now. Hope to help.

**Comment by DarkLord44** [comment]
Thanks you very much cutiko, I have solved it now. Glad to here, that i not only have problems with it ;)
