### ISSUE TITLE
problem with select all

### ISSUE THREAD

**Issue by msoltanian** [satyan/sugar#654]
hi friends
I need to query with group by and get max value of each group..

SELECT NAME, MAX(SALARY) FROM COMPANY GROUP BY NAME;

please helpp me.

**Comment by NitramTasu** [comment]
You can do:
SELECT * FROM COMPANY GROUP BY NAME ORDER BY SALARY DESC LIMIT 1

In Sugar is:
List<Company> companyList = Company.find(Company.class, "", "", "name", "salary DESC", "1");

**Comment by sibelius** [comment]
tks @NitramTasu
