### ISSUE TITLE
Delete all data from all tables in Sugar ORM

### ISSUE THREAD

**Issue by moallemi** [satyan/sugar#657]
I am using Sugar 1.5 in my app and I want to clear all info when the user logoff.
Is there any safe method to delete all tables from database and create it again?

**Comment by peshkira** [comment]
I have a GenericDAO which has the following method inside

```
  @Override
  public void removeAll() {
    T.deleteAll(mClazz);
    T.executeQuery("DELETE FROM SQLITE_SEQUENCE WHERE NAME = '" + NamingHelper.toSQLName(mClazz) + "'");
  }
```

T is the generic type and mClazz is the current Class of T. This removes all data from the table for T and then resets the sequence, so that the ids start again at 1.

I hope it helps

**Comment by sibelius** [comment]
@peshkira this method looks really great

this could work
