### ISSUE TITLE
Insert a list of sugar records?

### ISSUE THREAD

**Issue by BoldijarPaul** [satyan/sugar#658]
Is there a way to insert a list of sugar records? Instead of iterating over the list and inserting object by object, like

```
List<PersonRecord> list=new List<PersonRecord>();
list.add(new PersonRecord("Joe"));
list.add(new PersonRecord("Joe"));
SugarRecord.saveList(list);
```

**Comment by ExtroNovosib** [comment]
https://github.com/satyan/sugar
Bulk Insert

List<Book> books = new ArrayList<>();
books.add(new Book("isbn123", "Title here", "2nd edition"))
books.add(new Book("isbn456", "Title here 2", "3nd edition"))
books.add(new Book("isbn789", "Title here 3", "4nd edition"))
SugarRecord.saveInTx(books);

**Comment by sibelius** [comment]
tks @ExtroNovosib

**Comment by BoldijarPaul** [comment]
@ExtroNovosib @sibelius  it's deprecated.
