### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by ChristopherSunith** [satyan/sugar#660]
Dear Satya, 

I created an app on android studio to make a List of items and store it. Used Sugar ORM to store the items that I may view it later. But after gradle build on Android Studio, it installs the apk on my phone(Using my phone directly to execute programs) and then the app fails to open on my phone. No errors found or I am not able to find errors. The App runs without Sugar ORM if I use common.jar as a library and write the list of items onto a text file. Do let me know if you need screenshots. Would really appreciate it if you could provide a solution for this. Thank you.

**Comment by sibelius** [comment]
do u have any stack trace? could u post a repo so we can reproduce this steps?

**Comment by ChristopherSunith** [comment]
Actually, I got this working. All I had to do is remove the sugar.java file from the libs folder of my project. And uncheck the "enable instant run to hot swap code" Under Settings >> Build >> Instant  Run.

**Comment by sibelius** [comment]
great
