### ISSUE TITLE
[REQUEST-FEATURE] Where is OFFSET parameter in SugarRecord::find method

### ISSUE THREAD

**Issue by kasim1011** [satyan/sugar#737]
Android `SQLite` database supports `OFFSET` keyword [1:- [here](http://stackoverflow.com/a/30458949/3702021), 2:- [here](https://www.sqlite.org/lang_select.html#limitoffset)]. There's no `OFFSET` parameter available in `SugarRecord::find` method.

Currently is there any way if I want to use `OFFSET`?

**Comment by kigen** [comment]
I believe this is  currently possible by writing a raw SQL query
Example: 
```
        Users.findWithQuery(Users.class, "SELECT * FROM USERS LIMIT ? OFFSET ?","10","0");
```

**Comment by kasim1011** [comment]
@kigen Thanks.
