### ISSUE TITLE
Does the master branch include the sugar-cipher features also?

### ISSUE THREAD

**Issue by brspurri** [satyan/sugar#750]
In the changelog, (https://github.com/chennaione/sugar/blob/ca5dd14df77d4a78047197f223eaf1b0f6c50c16/CHANGELOG.md) is is stated that sqlcipher is integrated to v1.3 of the `sugar-cipher` branch. Does anyone know if this was merged? The branch itself is 377 commits behind master, so seems hard to leverage v1.5 **and** sqlcipher.

**Comment by JonatanSalas** [comment]
@brspurri sugar-cipher isn't merged with the master branch. In the feature requests I have added the support for cipher..

**Comment by brspurri** [comment]
Great, thanks! In the meantime, I'll try to follow the approach outlined in #512 .

**Comment by Liar1995** [comment]
Hello Jonatan,I would like to know how to use the  **sugar-cipher**  ,where did you provide support? @JonatanSalas
