### ISSUE TITLE
Sugar doesn't seem to be saving entries on all devices

### ISSUE THREAD

**Issue by sadelbrid** [satyan/sugar#761]
I'm having an issue with Sugar ORM. First off, it works great on my device and many other devices. However I'm seeing crash logs from my users that indicate it isn't saving entries on all devices. Here is the class I am saving to the database:

    public class Alarm extends SugarRecord {
    @Unique
    public int requestCode;
    public int hour;
    public int minute;
    public int repeatDays;
    public int status;
    public int snooze;
    public float volume;
    public String song = Settings.EMPTY_MODULE;
    public String name = Settings.EMPTY_MODULE;
    public long millis;

    public Alarm(){}

    public Alarm(int requestCode, int hour, int minute, int repeatDays, int status,
                 int snooze, float volume, String song, String name, long millis) {
        this.requestCode = requestCode;
        this.hour = hour;
        this.minute = minute;
        this.repeatDays = repeatDays;
        this.status = status;
        this.snooze = snooze;
        this.volume = volume;
        this.song = song;
        this.name = name;
        this.millis = millis;
        }
    }

Here is how I save it:
    Alarm addAlarmSql(int requestCode, int hour, int minute, int repeatDays, long millis, int snooze, 
            float volume, String name, String song) {
            Alarm alarm = new Alarm(requestCode, hour, minute, repeatDays,
                AlarmStatus.ALARM_ON.value, snooze, volume, song, name, millis);
            alarm.save();
            return alarm;
    }

Like I said, it seems to work great on most devices including my own. **However the following call returns null for some users:**
`
            Alarm alarm = Select.from(Alarm.class).where(Condition.prop("request_code").eq(requestCode)).first();
`

For completion, here is the Sugar initialization in my Application onCreate:
`
            SugarContext.init(getApplicationContext());
`
And here are the lines related to it in my manifest:
`
    <meta-data android:name="DATABASE" android:value="*********.db" />
        <meta-data android:name="VERSION" android:value="2" />
        <meta-data android:name="QUERY_LOG" android:value="true" />
        <meta-data android:name="DOMAIN_PACKAGE_NAME" android:value="com.*********.*************.*********.schema" />
`

And my application extends SugarApp. So I'm fairly certain I've set it up correctly. One might simply say my issue is that my requestCode sent to that call is wrong and therefore Sugar can't find any entries. That's fair. I'm also searching my code to find if there's any way the requestCode is changed or perhaps the wrong value is sent. So far I haven't found anything like that. That aside, does anyone think the issue could be elsewhere?

**Comment by hamada147** [comment]
@sadelbrid I'm not able to use the Unique annotation in any of my models. It says it don't exist. How are you able to make it work on your end.
