### ISSUE TITLE
Bug: Caused by: android.database.sqlite.SQLiteException: no such table: BOOK (code 1): , while compiling: INSERT OR REPLACE  INTO BOOK(ID,NAME) VALUES (?,?)

### ISSUE THREAD

**Issue by b7woreo** [satyan/sugar#772]
I follow official tutorial, but always caused crash.
``` Caused by: android.database.sqlite.SQLiteException: no such table: BOOK (code 1): , while compiling: INSERT OR REPLACE  INTO BOOK(ID,NAME) VALUES (?,?) ```

[My sample code](https://github.com/chenjar/SugarSample) 

Is there any wrong?

**Comment by b7woreo** [comment]
It occur most probability in Android Version: 4.4 in my other online app.
I found a strange problem, I use ```count()``` method on a empty table, it return -1 on Android Version: 4.4, and return 0 on other Android Version.

**Comment by lyldding** [comment]
try this.

`@Table
public class Book extends SugarRecord{
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}`


`Book book = new Book();
book.setName("test");
book.save();`

**Comment by b7woreo** [comment]
Thanks, I have found reason for this problem. Because I use multi dex, and in 4.4 version, it seem to be not found all SugarRecord in all dex file, so I try to reduce method count, I work normal after I close multi dex.

**Comment by karuhanga** [comment]
Kindly close the issue if it worked out :)
