### ISSUE TITLE
adding new column to existing table

### ISSUE THREAD

**Issue by quensh93** [satyan/sugar#774]
hello,
this is my class : 
public class UserInfoDb extends SugarRecord
{
    public boolean isChecked ;
    public boolean isShowChanges ;
    public String Packages ;

    public UserInfoDb(){

    }
}
now, i`m trying to add new string to this class like this :

public String TestField ;

i changed db version and create a sql file in asset/sugar_upgrades.

i tried this :
alter table user_info_db add test_field TEXT;

also :
alter table user_info_db add column  test_field TEXT;

also i tried to create new table and copy old table to new table and drop old table too,
after that all, seems sugar will do updates but when i`m trying to work with new column i will get this : 

Failed to read row 0, column -1 from a CursorWindow which has 1 rows, 4 columns

any idea?

**Comment by karuhanga** [comment]
Hey,
You need to add the new column/field to your class.
Also, when you're simply adding new columns, you're not supposed to write update scripts. So you should delete that update file.
Just add the field to the class and update the db version.

**Comment by quensh93** [comment]
i`ts worked, now i can work with new field but this way will drop all data in table and i avoid data loss,
so is it possible ?!

**Comment by karuhanga** [comment]
No it will not drop the data.
It simply adds the column automatically for you and puts a default value in that field for your previous records.
For strings that should be "".

**Comment by quensh93** [comment]
no it is not, i try it and it drop all data in that table, i`m using sugar-1.3

**Comment by quensh93** [comment]
it worked on sugar 1.5, tnx

**Comment by karuhanga** [comment]
Ohhh awesome then.
Good luck.
And please close the issue if everything's working great. :)
