### ISSUE TITLE
W/System.err: when using Query Builder but didn't close the app

### ISSUE THREAD

**Issue by fauzipadlaw** [satyan/sugar#775]
I try to get list with this code : 
`List<Track> listInDb = Track.find(Track.class, "track_id = ?", track.getTrackId());` 

And I got this Error : 
` W/System.err:     at domain.MainActivity.saveToDB(MainActivity.java:65)`
`W/System.err:     at domain.MainActivity$1.onResponse(MainActivity.java:106)`
`W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)`
`W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`
But this error did not stop the App;

`track.getTrackId()` return a String value;
`Log.d("MAIN", "Track ID yang ditemukan : " +track.getTrackId());`
I made a Log to show this value, and its showed `D/MAIN: Track ID yang ditemukan : 138454173`

I have no clue why this is happened;

**Comment by karuhanga** [comment]
Hey,
Sorry about that,
I think your problem might be the missing quotations around the question mark since your data is a string.
`List<Track> listInDb = Track.find(Track.class, "track_id = '?' ", track.getTrackId());`

**Comment by fauzipadlaw** [comment]
Hmm. I dont think so. I forgot to create an empty constructor LOL. Thanks for the answer :)
