### ISSUE TITLE
E/SQLiteLog: (1) no such table: LINKED_HASH_MAP

### ISSUE THREAD

**Issue by jack2799** [satyan/sugar#777]
I/Sugar: Error in saving in transaction no such table: LINKED_HASH_MAP (code 1): , while compiling: INSERT OR REPLACE  INTO LINKED_HASH_MAP(VALUES_COLLECTION,KEY_SET,ACCESS_ORDER) VALUES (?,?,?)

I have done everything 
from 
https://stackoverflow.com/questions/33031570/android-sugar-orm-no-such-table-exception?noredirect=1&lq=1
https://stackoverflow.com/questions/41605824/getting-no-such-table-error-with-sugarorm-1-4-in-android

`  List<UserFriends> userFriendsList = mapper.readValue(data, List.class);
  SugarRecord.saveInTx(userFriendsList);`

This is code where i am trying to save.

Any suggestions please

**Comment by karuhanga** [comment]
Could you post the actual error log?

**Comment by jack2799** [comment]
@Karuhanga Heading and first line are actually log lines. There is nothing more in the log.

**Comment by karuhanga** [comment]
Are other tables working or does it fail for all?

**Comment by jack2799** [comment]
@Karuhanga  There is only one table.

**Comment by karuhanga** [comment]
@jack2799 I hope you don't mind the troubleshooting questions.
Okay so what are the current meta values in your manifest?
Also what is the class name of the objects you're trying to save?
I seem to see UserFriends so I'm wondering where LINKED_HASH_MAP pops up from.

**Comment by jack2799** [comment]
@Karuhanga 
meta values
` <meta-data
            android:name="DATABASE"
            android:value="user_friends.db" />
        <meta-data
            android:name="VERSION"
            android:value="1" />
        <meta-data
            android:name="QUERY_LOG"
            android:value="true" />
        <meta-data
            android:name="DOMAIN_PACKAGE_NAME"
            android:value="in.cherrybits.friendsinmytrain" />`

Class is 
`public class UserFriends extends SugarRecord{
    public UserFriends(){}
    public long  id;
    public String name;
}`

**Comment by karuhanga** [comment]
@jack2799 
So my best guess is the problem might not be from Sugar ORM.

I believe you're using the Jackson-Object-Mapper.
If so, then if you're trying to deserialize JSON and get a list, the guide [here](http://www.baeldung.com/jackson-object-mapper-tutorial) suggests using;

`List<UserFriends> userFriendsList = mapper.readValue(data, new TypeReference<List<UserFriends>>(){}); `
rather than;
`List<UserFriends> userFriendsList = mapper.readValue(data, List.class); `

This is assuming your data is actually a JSON array.

**Comment by jack2799** [comment]
@Karuhanga but userFriendsList get data correct, its definetely from Sugar ORM

**Comment by jack2799** [comment]
@Karuhanga Thanks, that solved the problem.

**Comment by karuhanga** [comment]
Glad I could help.
About the id... To be safe you'd rather not use it.
Someone did a pull changing the SugarRecord id to _id but I don't think it was ever merged.
