### ISSUE TITLE
Query return java.lang.NoSuchMethodException

### ISSUE THREAD

**Issue by ZeRodolfo** [satyan/sugar#780]
Dear,
I am using Sugar 1.5, however every time I run a query, "Listall", "Find" or "first" for example, the following error appears below, I already tried other versions of suck and the error remained, I already did a clean of the project and a rebuild

> 12-26 11:55:36.442 2974-2974/ D/SQL Log: SQLiteQuery: SELECT * FROM SERVICE
12-26 11:55:36.443 2974-2974/ W/System.err: java.lang.NoSuchMethodException: <init> []
12-26 11:55:36.444 2974-2974/ W/System.err:     at java.lang.Class.getConstructor(Class.java:531)
12-26 11:55:36.444 2974-2974/ W/System.err:     at java.lang.Class.getDeclaredConstructor(Class.java:510)
12-26 11:55:36.444 2974-2974/ W/System.err:     at com.orm.SugarRecord.getEntitiesFromCursor(SugarRecord.java:212)
12-26 11:55:36.444 2974-2974/ W/System.err:     at com.orm.SugarRecord.find(SugarRecord.java:204)
12-26 11:55:36.444 2974-2974/ W/System.err:     at com.orm.SugarRecord.listAll(SugarRecord.java:127)

**Comment by ZeRodolfo** [comment]
I just forgot to create the default sugar builder, I did not realize it was necessary to create it

// Default constructor is necessary for SugarRecord
public Service() {
}

**Comment by ilhamfidatama** [comment]
can i see you're code?

**Comment by ilhamfidatama** [comment]
can i see you're code?
because i have same problem with you, i'm used kotlin
i got some error
`D/SQL Log: SQLiteQuery: SELECT * FROM PRODUCT_SUGAR_ORM
W/System.err: java.lang.NoSuchMethodException: <init> []
        at java.lang.Class.getConstructor(Class.java:531)
        at java.lang.Class.getDeclaredConstructor(Class.java:510)
        at com.orm.SugarRecord.getEntitiesFromCursor(SugarRecord.java:212)
        at com.orm.SugarRecord.find(SugarRecord.java:204)
        at com.orm.SugarRecord.listAll(SugarRecord.java:127)`

and this is my code
`data class ProductSugarORM(
        var base_price: Double,
        var category: Int,
        val created_on: String,
        var description: String,
        val id: Int,
        var name: String,
        var sell_price: Double,
        var stock: Int,
        val store: Int,
        val type: String,
        val updated_on: String
):SugarRecord(){
    fun ProductSugarORM(){}
}`

i want to see the result using `Log.w("load-local", "${SugarRecord.listAll(ProductSugarORM::class.java)}")`

it doesn't work
