### ISSUE TITLE
How Add New Table?

### ISSUE THREAD

**Issue by HuiBest** [satyan/sugar#782]
I want add new table ,but I don't konw SQL ,thanks !

**Comment by HuiBest** [comment]
.......need help ......

**Comment by karuhanga** [comment]
Kindly take a look at the documentation before opening an issue.
You seem to be misusing this section.

**Comment by HuiBest** [comment]
I can't find some Example ,so I oppeing is issue....

**Comment by kkannan-carecloud** [comment]
@HuiBest  Here is the link to the documentation - http://satyan.github.io/sugar/getting-started.html 

Also, here is the example that is mentioned in the documentation on how to "create a table". 

Please close this issue. 
```
Extend SugarRecord for all the classes that you need persisted. That's it. Sugar takes care of table creation for you.

Note: Please retain the default constructor.

public class Book extends SugarRecord<Book> {
  String title;
  String edition;

  public Book(){
  }

  public Book(String title, String edition){
    this.title = title;
    this.edition = edition;
  }
}

```

**Comment by bigntallmike** [comment]
To be fair, you don't actually add new tables.  You simply add the extension of SugarRecord to any objects you want to be stored in the database.  The tables are generated for you.

**Comment by HuiBest** [comment]
@kkannan-carecloud @bigntallmike Thanks，I need to add a new table to the database, add table objects and upgrade the database version, but I can make a mistake.

**Comment by nikitoSha** [comment]
Why you are setting dislikes? Fore example, I need to clear DB:

		List<EventOrder> eventOrders = EventOrder.listAll(EventOrder.class);
		EventOrder.deleteAll(EventOrder.class);

And, as you know, we get error: 

> android.database.sqlite.SQLiteException: no such table: EVENT_ORDER (code 1): , while compiling: SELECT * FROM EVENT_ORDER

So, I don't want to add first row into table (maybe I have no data yet), but I must??
